Enterprise-CMCS/macpro-mdct-qmr

LICENSE.md
services/uploads/serverless.yml

Open attachment to mpr

---

services/ui-src/src/views/DemoMeasure/questions/DataSource.tsx

Created a quick PR of Padma's QA findings such as misspellings and incorrect labels when comparing to the figma
https://qmacbis.atlassian.net/jira/software/c/projects/OY2/boards/208?modal=detail&selectedIssue=OY2-14080

fixed padmas QA findings to match figma completely

---

services/ui-src/src/components/MonthPicker/calendarPopup.tsx

Fixes to monthPicker issues
ticket: https://qmacbis.atlassian.net/browse/OY2-8208?atlOrigin=eyJpIjoiMjQ0MzdhMDJiMjNlNGU4N2FmNjY2NDg0ZDA5NzMyY2UiLCJwIjoiaiJ9
instance: https://d1jseh8apirhpm.cloudfront.net
- if the input is changed, the monthPicker now adjusts to reflect this
- if the inputs are cleared the default calendar is set to current month/year
- if a year with less than four digits is input it is ignored for display purposes

Oy2 8208 - monthPicker fixes 

---

services/ui-src/src/views/AddHHCoreSet/index.tsx
services/ui-src/src/views/DemoMeasure/index.test.tsx
services/ui-src/src/views/DemoMeasure/questions/MeasurementSpecification.tsx

Added small changes that were found during QA for the two issues linked below
https://qmacbis.atlassian.net/jira/software/c/projects/OY2/boards/208?modal=detail&selectedIssue=OY2-14489
https://qmacbis.atlassian.net/jira/software/c/projects/OY2/boards/208?modal=detail&selectedIssue=OY2-14510

Oy2 14510 fix

---

services/ui-src/src/components/InputWrapper/index.tsx
services/ui-src/src/components/Inputs/NumberInput/index.test.tsx
services/ui-src/src/components/Inputs/NumberInput/index.tsx
services/ui-src/src/components/MonthPicker/calendarPopup.tsx
services/ui-src/src/views/DemoComponents/index.tsx
services/ui-src/src/views/DemoMeasure/index.tsx
services/ui-src/src/views/DemoMeasure/questions/WhyAreYouNotReporting.tsx

Resolving issues found in Quality. Reintroducing number masking for number input.
ticket-daterange: https://qmacbis.atlassian.net/browse/OY2-8208?atlOrigin=eyJpIjoiZmM5ZGE2MTRjMTI3NGE2ODgyY2Y5ZDY3Mzk0ZGM2MzkiLCJwIjoiaiJ9
ticket-whynotreporting: https://qmacbis.atlassian.net/browse/OY2-14450?atlOrigin=eyJpIjoiNjRiZTc2MmI1ZDFhNDk2YjgzMGU0ZDFkMzFmYWExOWUiLCJwIjoiaiJ9

Oy2 14450 - Fixes for quality of Why Not Reporting and DateRange

---

services/ui-src/src/views/StateHome/AddCoreSetCards.tsx
services/ui-src/src/views/StateHome/__tests__/index.test.tsx

Small copy update to state home page

Update state home copy

---

services/ui-src/src/views/CoreSet/index.tsx
services/ui-src/src/views/StateHome/index.tsx

UI updates to closer match the figma following Padma's comments

OY2-14512/ 14514 - fix

---

services/ui-src/src/components/Rate/index.test.tsx
services/ui-src/src/measures/2021/FUAAD/index.tsx
services/ui-src/src/measures/2021/FUAAD/questions/DateRange.tsx
services/ui-src/src/measures/2021/FUAAD/questions/index.tsx
services/ui-src/src/measures/schema.ts
services/ui-src/src/measures/types.tsx
services/ui-src/src/views/DemoMeasure/index.tsx
services/ui-src/src/views/DemoMeasure/questions/DateRange.tsx
services/ui-src/src/views/DemoMeasure/questions/index.tsx

Add Date Range Comp to demo and fuaad

---

services/ui-src/src/measures/schema.ts
services/ui-src/src/measures/types.tsx
services/ui-src/src/views/DemoMeasure/questions/OptionalMeasureStratification.tsx

quality fixes for [ticket](https://qmacbis.atlassian.net/browse/OY2-14501?atlOrigin=eyJpIjoiNzcyYzI4MGVlNjM5NDg0ZmIxMzI5NjA1NTViZGQzNzYiLCJwIjoiaiJ9)
- Added AgeRates to every object and schema of this component
- Fixed misspelled or missing text in questions and labels
- adding radio buttons for aggregated/independent data for additional race categories
- added missing data category

oy2 14501 fixes

---

services/ui-src/src/measures/2021/FUAAD/index.tsx
services/ui-src/src/measures/2021/FUAAD/questions/DateRange.tsx
services/ui-src/src/views/DemoMeasure/index.tsx
services/ui-src/src/views/DemoMeasure/questions/DateRange.tsx

adds date range link
cant decide on using a type prop or url param? posting pr for feedback

Add link to DateRange question

---

services/ui-src/src/measures/2021/FUAAD/index.tsx

Moved additional notes to the end of FUAAD but also all future measures down the road. Also, only show combined rates and optional measurement stratification when the user clicks yes
https://qmacbis.atlassian.net/jira/software/c/projects/OY2/boards/208?modal=detail&selectedIssue=OY2-15100

Oy2-15102 - additional notes rearrangement 

---

services/ui-src/src/measures/2021/FUAAD/index.tsx

This will conditionally hide and show Performance Measure questions in FUAAD
https://qmacbis.atlassian.net/browse/OY2-15099

Conditionals to render performance measure in FUAAD

---

services/ui-src/src/components/MeasureWrapper/index.tsx
services/ui-src/src/measures/2021/FUAAD/index.tsx
services/ui-src/src/views/CoreSet/index.tsx

Fixed the back button when inside a specific measure and should take you back to the list of measures

fixed back button when inside a measure

---

services/ui-src/src/measures/2021/FUAAD/questions/DataSource.tsx

This will match up more closely with Figma prototype for the Data Source question.
https://qmacbis.atlassian.net/browse/OY2-15093

Move Text Areas for Data Source Other Selections to Match Figma Prototype

---

services/ui-src/src/measures/schema.ts

Fixed issue where additional notes was throwing an error when touched and left empty. This is a fix based on Padma's feedback
https://qmacbis.atlassian.net/browse/OY2-15102

OY2-15102 fixed issue where additional notes was still throwing validation error

---

services/uploads/serverless.yml

Bucket policy change to s3 bucket that will receive uploaded files

bucket policy fix

---

services/ui-auth/serverless.yml
services/ui-src/src/components/LocalLogins/index.tsx
services/uploads/serverless.yml

Fixed some issues regarding s3 write policy

Fix s3 write policy

---

services/ui-auth/serverless.yml
services/uploads/serverless.yml

* fix deploy issues
* fix s3 stuff
* revert
* fix auth
* testing
* testing2
* testing3
* testing4
* testing5
* testing3
* testing removing encryption on lambda bucket
* testing
* testing
* testing
* testing
* testing
* testing
* testing
* testing
* testing
* testing
* testing

Fix s3 write policy (#376)

---

services/ui-src/src/components/Footer/index.tsx
services/ui-src/src/views/AddHHCoreSet/index.tsx
services/ui-src/src/views/CoreSet/index.test.tsx
services/ui-src/src/views/CoreSet/index.tsx
services/ui-src/src/views/StateHome/actions.ts

add-hh style updates
button text change
remove export from coreset kabob
remove percentage from measures list page
update one test

Updates during meeting

---

services/uploads/serverless.yml

* bring back kms
* push changes
* remove encryption temporarily
* Update services/ui-src/src/components/LocalLogins/index.tsx
Co-authored-by: 13bfrancis <40218571+13bfrancis@users.noreply.github.com>
Co-authored-by: 13bfrancis <40218571+13bfrancis@users.noreply.github.com>

Mpr s3 kafka (#393)

---

.github/workflows/deploy.yml
deploy.sh
services/app-api/handlers/authUtils/checkAuth.ts
services/app-api/handlers/measures/update.ts
services/app-api/serverless.yml
services/ui-src/src/hooks/api/useAddCoreSet.tsx
services/ui-src/src/hooks/api/useDeleteCoreSet.tsx
services/ui-src/src/hooks/api/useGetCoreSets.tsx
services/ui-src/src/hooks/api/useGetMeasures.tsx
services/ui-src/src/hooks/authHooks/ApiProvider.tsx
services/ui-src/src/libs/api.ts
services/ui-src/src/views/ApiTester/index.tsx

Dev is failing right now because CORS on the master branch doesn't allow custom headers, I've removed the custom headers and put regular CORS rules back in place. The User State and User Role are now passed in in the body of the request

Api rewrite

---

services/app-api/handlers/authUtils/checkAuth.ts
services/ui-src/src/App.tsx
services/ui-src/src/Routes.tsx
services/ui-src/src/components/LocalLogins/index.tsx
services/ui-src/src/types.ts
services/ui-src/src/types.tsx
services/ui-src/src/views/Home/index.test.tsx
services/ui-src/src/views/Home/index.tsx

add BO user remove deprecated use of user info

---

services/ui-src/src/components/Breadcrumbs/index.tsx

- couldn't have non-breadcrumb children of breadcrumb
- changed to not use breadcrumb

fix: lastChildOf for breadcrumb issue

---

services/app-api/serverless.yml

Update serverless yaml

---

services/ui-src/src/measures/2021/FUAAD/index.tsx

This will add validations and conditional logic and validations to Data Source.
https://qmacbis.atlassian.net/jira/software/c/projects/OY2/boards/208?modal=detail&selectedIssue=OY2-15099

Data Source/Measurement Specifications Validations

---

services/ui-src/src/measures/2021/FUAAD/questions/OptionalMeasureStratification.tsx
services/ui-src/src/measures/2021/FUAAD/validation/schema.ts
services/ui-src/src/measures/2021/FUAAD/validation/types.ts
services/ui-src/src/measures/schema.ts
services/ui-src/src/measures/types.tsx

New Ticket information from Karen and Marc on additional race needing sub-cat options, a base NDR, and no radio button options

Oy2 14501 q4

---

tests/cypress/cypress.json
tests/cypress/cypress/integration/common/steps.js
tests/cypress/cypress/integration/oy2_15504_Measure_validation_Error_Creation_Updates.feature
tests/cypress/support/pages/FUAADPage.js
tests/cypress/support/pages/Homepage.js
tests/cypress/support/pages/Landingpage.js
tests/cypress/support/pages/LoginPage.js

Automation for ticket OY2-15504

Oy2 15504 automation

---

tests/cypress.json
tests/cypress/cypress.json
tests/cypress/cypress/integration/common/steps.js
tests/cypress/cypress/integration/oy2_14767_Allow_files_to_be_uploaded_to_s3.feature
tests/cypress/cypress/integration/oy2_15672_HEDIS_dropdown_update.feature
tests/cypress/support/pages/FUAADPage.js

Merging tests for oy2-15672tests

Oy215672tests

---

services/ui-src/src/measures/2021/FUAAD/index.tsx
services/ui-src/src/measures/2021/FUAAD/questions/OptionalMeasureStratification.tsx

[ticket](https://qmacbis.atlassian.net/browse/OY2-15927?atlOrigin=eyJpIjoiNmZmMDU3ZjU3ZDM5NGZhNjljOWZjMjVjOGYzZGZlZjMiLCJwIjoiaiJ9)
Additional/Sub-Category is only intended to be below different race options, not the main race option
TODO Note added about issue in data loading which should be handled in [this](https://qmacbis.atlassian.net/browse/OY2-15889?atlOrigin=eyJpIjoiNzNiZGU4MGY1Njk0NDRlZjkzOTU3YjRmMzQ4MmY2OTciLCJwIjoiaiJ9)

Oy2 15927 - spike to remove sub-category from upper checkbox portion

---

services/uploads/serverless.yml
services/uploads/src/clamav.js

Fix av scan

---

tests/cypress/cypress/integration/common/steps.js
tests/cypress/cypress/integration/oy2_15212_qmr_mdct_logo.feature
tests/cypress/support/pages/AdultCoreSetMeasuresPage.js
tests/cypress/support/pages/FUAADPage.js
tests/cypress/support/pages/Homepage.js

Automation test for ticket OY2-15212

Oy2 15212 automation

---

tests/cypress/cypress/integration/common/steps.js
tests/cypress/cypress/integration/oy2_15013_Update_user_auth_handling_in_ui.feature
tests/cypress/support/pages/AdultCoreSetMeasuresPage.js
tests/cypress/support/pages/FUAADPage.js
tests/cypress/support/pages/Landingpage.js
tests/cypress/support/pages/LoginPage.js

Oy2 15013 tests

---

services/uploads/serverless.yml

Update Clamav version to fix upload issue

update clamav layer

---

services/uploads/serverless.yml
services/uploads/src/clamav.js
services/uploads/src/constants.js

Fix av issues

---

services/app-api/handlers/coreSets/create.ts

Await createDependedMeasures

---

services/app-api/handlers/coreSets/get.ts
tests/cypress/cypress/integration/OY2_8937_Measure_04_IET_AD.spec.js
tests/cypress/support/pages/AdultCoreSetMeasuresPage.js

Ietad tests

---

tests/cypress/cypress/integration/common/steps.js
tests/cypress/cypress/integration/oy2_8945_CCP_AD.feature
tests/cypress/support/pages/AdultCoreSetMeasuresPage.js
tests/cypress/support/pages/CCPadPage.js

Ccp ad automation

---

services/app-api/handlers/dynamoUtils/measureList.ts
services/ui-src/src/measures/measuresList.ts
tests/cypress/cypress/integration/OY2_8937_Measure_04_IET_AD.spec.js

Quick PR to fix measure names that were misspelled

fixed misspelled measure names

---

services/ui-src/src/components/InputWrapper/index.tsx
services/ui-src/src/components/Inputs/Checkbox/index.tsx
services/ui-src/src/components/Inputs/NumberInput/index.tsx
services/ui-src/src/components/Inputs/RadioButton/index.tsx
services/ui-src/src/components/Inputs/Select/index.tsx
services/ui-src/src/components/Inputs/TextArea/index.tsx
services/ui-src/src/components/Inputs/TextInput/index.tsx
services/ui-src/src/components/Notification/index.tsx
services/ui-src/src/components/Rate/index.tsx
services/ui-src/src/components/Table/columns/coreSets.tsx
services/ui-src/src/components/Table/columns/measures.tsx
services/ui-src/src/components/Table/index.tsx
services/ui-src/src/components/Upload/index.tsx

adding data-cy attributes to inputs, buttons and links

Add data cy

---

services/ui-src/src/measures/2021/OUDAD/index.tsx

Fix some quick issues with oudad showing multiple buttons

push fixes for oudad

---

tests/cypress/support/pages/CPAADPage.js

Quick fix for CPA test failures

attempt to fix cpa test issues

---

.github/workflows/deploy.yml
tests/cypress/cypress/integration/oy2_16228_Date_Range_Adjustment.spec.js

Automation test for ticket oy2-16228

Oy2 16228auto

---

.github/workflows/deploy.yml
tests/cypress/cypress/integration/oy2_16411_Restructuring_Data_Source_Text_boxes.spec.js

Oy2 16411tests

---

.github/workflows/deploy.yml
tests/cypress/cypress/integration/oy2_16342_Add_Validation_to_Rate_when_user_selects_multiple_Data_Sources.spec.js

tests for oy2-16342

---

.github/workflows/deploy.yml
tests/cypress/cypress/integration/oy2_16265_Validation_text_appear_in_CHAD.spec.js

automation test for ticket oy2-16265 

Oy2 16265test

---

services/ui-src/src/measures/2021/CCPAD/data.ts
services/ui-src/src/measures/2021/CCWAD/data.ts
services/ui-src/src/measures/2021/FUAAD/data.ts
services/ui-src/src/measures/2021/FUMAD/data.ts
services/ui-src/src/measures/2021/IETAD/data.ts
services/ui-src/src/measures/2021/MSCAD/data.ts
services/ui-src/src/measures/2021/PQI01AD/data.ts
services/ui-src/src/measures/2021/PQI05AD/data.ts
services/ui-src/src/measures/2021/PQI08AD/data.ts
services/ui-src/src/measures/2021/PQI15AD/data.ts
services/ui-src/src/measures/CommonQuestions/PerformanceMeasure/data.ts
services/ui-src/src/measures/CommonQuestions/PerformanceMeasure/index.tsx

fix: text fields weren't rendering properly

---

services/ui-src/src/components/MeasureWrapper/index.tsx
services/ui-src/src/dataConstants.ts
services/ui-src/src/measures/2021/CCPAD/index.tsx
services/ui-src/src/measures/2021/CCWAD/index.tsx
services/ui-src/src/measures/2021/CPAAD/index.tsx
services/ui-src/src/measures/2021/FUAAD/index.tsx
services/ui-src/src/measures/2021/FUMAD/index.tsx
services/ui-src/src/measures/2021/IETAD/index.tsx
services/ui-src/src/measures/2021/MSCAD/index.tsx
services/ui-src/src/measures/2021/OUDAD/index.tsx
services/ui-src/src/measures/2021/PQI01AD/index.tsx
services/ui-src/src/measures/2021/PQI05AD/index.tsx
services/ui-src/src/measures/2021/PQI08AD/index.tsx
services/ui-src/src/measures/2021/PQI15AD/index.tsx
services/ui-src/src/measures/CommonQuestions/AdditionalNotes/index.tsx
services/ui-src/src/measures/CommonQuestions/CombinedRates/index.tsx
services/ui-src/src/measures/CommonQuestions/DataSource/index.tsx
services/ui-src/src/measures/CommonQuestions/DateRange/index.tsx
services/ui-src/src/measures/CommonQuestions/DefinitionsOfPopulation/index.tsx
services/ui-src/src/measures/CommonQuestions/DeviationFromMeasureSpecification/index.tsx
services/ui-src/src/measures/CommonQuestions/types.ts
services/ui-src/src/measures/index.tsx
tests/cypress/cypress/integration/oy2_16411_Restructuring_Data_Source_Text_boxes.spec.js

update question types for Definition of Population

Update question types

---

services/ui-src/src/measures/CommonQuestions/DefinitionsOfPopulation/index.tsx

fix def pop bug logic where show delivery systems was never being shown

Fix def pop bug

---

.github/workflows/deploy.yml
services/ui-src/src/components/KebabMenu/index.tsx
services/ui-src/src/measures/2021/FUHCH/validation.ts
tests/cypress/cypress/integration/fuhch.spec.js
tests/cypress/cypress/integration/oy2-9959_PQI15_AD.spec.js
tests/cypress/cypress/integration/oy2_16411_Restructuring_Data_Source_Text_boxes.spec.js
tests/cypress/support/commands.js

Adding automation to FUHCH branch

FUHCH Automation

---

services/ui-src/src/measures/CommonQuestions/OptionalMeasureStrat/data.ts
services/ui-src/src/measures/CommonQuestions/OptionalMeasureStrat/omsNodeBuilder.tsx

Quality noted some minor issues in OMS

fix: wrong name and missing question text

---

services/ui-src/src/measures/CommonQuestions/OptionalMeasureStrat/additionalCategory.tsx
services/ui-src/src/measures/CommonQuestions/OptionalMeasureStrat/data.ts
services/ui-src/src/measures/CommonQuestions/OptionalMeasureStrat/index.tsx

small text changes

---

.github/workflows/deploy.yml
tests/cypress/cypress/integration/oy2_9929_PPC_AD.spec.js

PPC automated

---

services/ui-src/src/measures/2021/PPCAD/data.ts
services/ui-src/src/measures/2021/PPCAD/index.tsx
services/ui-src/src/measures/2021/PPCAD/types.ts
services/ui-src/src/measures/2021/PPCAD/validation.ts
services/ui-src/src/measures/2021/index.tsx
services/ui-src/src/measures/CommonQuestions/DefinitionsOfPopulation/index.tsx
services/ui-src/src/measures/globalValidations/dataDrivenTools.ts
services/ui-src/src/measures/globalValidations/validationsLib.tsx
services/ui-src/src/measures/measuresList.ts

oy2 9929 PPC-AD
https://qmacbis.atlassian.net/jira/software/c/projects/OY2/boards/208?modal=detail&selectedIssue=OY2-9929

Oy2 9929 - PPC-AD

---

.github/workflows/deploy.yml
services/ui-src/src/measures/2021/AMRAD/validation.ts
tests/cypress/cypress/integration/amrAD.spec.js

Added validation to OY2-9913 AMR-AD

Oy2 9913 automation

---

.github/workflows/deploy.yml
tests/cypress/cypress/integration/oy2_9947_HPC_AD.spec.js

Oy2 9947tests

---

services/ui-src/src/measures/2021/CBPAD/data.ts
services/ui-src/src/measures/2021/CISCH/data.ts
services/ui-src/src/measures/2021/PPCAD/data.ts

https://qmacbis.atlassian.net/jira/software/c/projects/OY2/boards/208?modal=detail&selectedIssue=OY2-17348
Fixing a few hybrid measures

adding missing hybrid medical sections

---

.github/workflows/deploy.yml
tests/cypress/cypress/integration/DEVCH.spec.js

add e2e cypress testing to DEV-CH measure

Add devch cypress tests

---

package.json
services/app-api/package.json
services/app-api/serverless.yml
services/app-api/yarn.lock
services/database/package.json
services/database/yarn.lock
services/stream-functions/package.json
services/stream-functions/yarn.lock
services/ui-auth/package.json
services/ui-auth/yarn.lock
services/ui-src/package.json
services/ui-src/yarn.lock
services/ui/package.json
services/ui/serverless.yml
services/ui/yarn.lock
services/uploads/package.json
services/uploads/yarn.lock
yarn.lock

Devsecops fixes

---

services/ui-src/src/views/StateHome/index.tsx

this should resolve the data persisting issue when removing and re-adding coresets/measures.

Resolve persisting data bug from react-query

---

destroy.sh

we are grabbing too many versions to delete at once so lowering the threshold will help resolve this issue

lower threshold for versions grabbed for destroy script

---

.github/workflows/deploy.yml
services/ui-src/src/components/MeasureWrapper/index.tsx
services/ui-src/src/measures/2021/FUHAD/data.ts
services/ui-src/src/measures/2021/FUHAD/index.tsx
services/ui-src/src/measures/2021/FUHAD/types.ts
services/ui-src/src/measures/2021/FUHAD/validation.ts
services/ui-src/src/measures/2021/FUHCH/data.ts
services/ui-src/src/measures/2021/FUHCH/validation.ts
services/ui-src/src/measures/2021/index.tsx
services/ui-src/src/measures/globalValidations/omsValidationsLib.tsx
services/ui-src/src/measures/measuresList.ts
tests/cypress/cypress/integration/fuhad.spec.js
tests/cypress/cypress/integration/fuhch.spec.js

This will complete the following measure: FUH-AD
https://qmacbis.atlassian.net/browse/OY2-8943

Implement fuh-ad measure and add oms validations

---

.github/workflows/deploy.yml
tests/cypress/cypress/integration/oy2_9953_PC01_AD.spec.js

Automation test for oy2-9953PC01-AD

Oy2 9953test

---

.github/workflows/deploy.yml
tests/cypress/cypress/integration/oy2_9921_ADD_CH.spec.js

Automation test for oy2-9921 ADD-CH

Oy2 9921test

---

services/ui-src/src/components/CompleteMeasureFooter/index.tsx

change submit button type to disallow form submit on 'enter'

Update submit button type in measures

---

.github/workflows/deploy.yml
tests/cypress/cypress/integration/oy2_8979_CDF_CH.spec.js

Automation test for ticket oy2_8979_CDF_CH

Cdf chtest

---

.github/workflows/deploy.yml
tests/cypress/cypress/integration/oy2_9922_AUD_CH.spec.js
tests/cypress/cypress/integration/oy2_9929_PPC_AD.spec.js

Automation test for ticket oy2_9922_AUD_CH

Aud chtest2

---

.github/workflows/deploy.yml
tests/cypress/cypress/integration/measures/CCPCH.spec.js

Adds Cypress tests for CCP-CH
Closes [CCP-CH](https://qmacbis.atlassian.net/jira/software/c/projects/OY2/boards/208?modal=detail&selectedIssue=OY2-17654)

[OY2-8944] Measure 11: CCP-CH automated Cypress tests

---

services/ui-src/src/components/MeasureWrapper/index.tsx

Quick fix to show measure description only if it exists

fix measure wrapper undefined title text

---

.github/workflows/deploy.yml
tests/cypress/cypress/integration/measures/APPCH.spec.js

Adds Cypress tests for APP-CH
Closes [OY2-17698](https://qmacbis.atlassian.net/browse/OY2-17698)

Add Cypress tests for APP-CH

---

services/ui/serverless.yml

Reverts CMSgov/cms-mdct-qmr#811

Revert "OY2-14497 Add Logging to CloudFront Bucket for QMR"

---

services/app-api/package.json
services/app-api/serverless.yml
services/app-api/yarn.lock

Val to Prod

---

.github/workflows/deploy.yml
services/ui-src/src/measures/2021/APMCH/data.ts
services/ui-src/src/measures/2021/APMCH/index.tsx
services/ui-src/src/measures/2021/APMCH/types.ts
services/ui-src/src/measures/2021/APMCH/validation.ts
services/ui-src/src/measures/2021/index.tsx
tests/cypress/cypress/integration/measures/APMCH.spec.js
tests/cypress/cypress/integration/measures/APMCH.spec.ts

Create the measure APM-CH.
[Oy2-9914](https://qmacbis.atlassian.net/browse/OY2-9914)

[Oy2-9914] Create APM-CH Measure

---

.github/workflows/deploy.yml
tests/cypress/cypress/integration/measures/WCVCH.spec.js
tests/cypress/support/commands/commands.js

Automation test for ticket oy2-9916 WCV-CH

Oy2 9916test

---

tests/cypress/cypress.json
tests/cypress/cypress/integration/measures/CCWCH.spec.ts
tests/cypress/cypress/integration/measures/CHLAD.spec.ts
tests/cypress/helper.d.ts

Update cypress to prevent false negatives

Chlad test fix

---

services/ui-auth/serverless.yml
services/ui-src/package.json
services/ui-src/src/libs/api.ts
services/ui-src/src/query.tsx
services/ui-src/yarn.lock

Updating amplify package
adding default query options to refetch queries in background
add logging

Adjust query refresh rate

---

.github/workflows/deploy.yml
services/ui-src/src/measures/globalValidations/tests/validateOneDataSource.test.ts
tests/cypress/cypress/integration/features/user_must_select_a_data_source_selection_validation.spec.ts

Testing for https://qmacbis.atlassian.net/browse/OY2-17347

Data src valtest

---

services/ui-src/src/views/AddChildCoreSet/index.tsx
services/ui-src/src/views/AddHHCoreSet/index.tsx

This will fix the background color of the button not being the proper color

fix button background color

---

services/ui-src/src/measures/2021/PC01AD/data.ts
services/ui-src/src/measures/2021/PC01AD/validation.ts

Includes a copy update to the Performance Measure label and the removal of an unnecessary validation.
[Oy2-17867](https://qmacbis.atlassian.net/browse/OY2-17867?atlOrigin=eyJpIjoiYjBlNGRiOTdkN2I3NDE4YWJiMmM2ZDFmMGVmYjg2ZDUiLCJwIjoiaiJ9)

[Oy2-17867] PC01-AD Label and Validation changes

---

services/ui-src/src/dataConstants.ts
services/ui-src/src/measures/2021/FUAHH/data.ts
tests/cypress/cypress/integration/measures/FUAHH.spec.ts

Create a Cypress test for FUA-HH
[Oy2-17981](https://qmacbis.atlassian.net/browse/OY2-17981)

[Oy2-17981] Testing ticket for Oy2-8939 (FUA-HH)

---

services/ui-src/src/measures/2021/SFMCH/validation.ts

remove extra validation causing cypress sfmch test to fail

remove extra validation

---

services/ui-auth/libs/users.json

Add more users for health home checks

Add more users

---

.github/workflows/deploy.yml
tests/cypress/cypress.json
tests/cypress/cypress/integration/measures/PCRHH.spec.ts

Oy2 9908 1 tests

---

.github/workflows/deploy.yml
tests/cypress/cypress/integration/measures/PQI92HH.spec.ts

Adds cypress tests to check the measure contains expected health home components, rate values and totals are calculated correctly, and specific validation errors are flagged.

add cypress tests

---

.github/workflows/deploy.yml
tests/cypress/cypress/integration/measures/QUALIFIERS_healthhome.spec.ts

HH Qualifier Automation

---

tests/cypress/cypress/integration/measures/PCRHH.spec.ts

Data Not Reporting Automation

---

services/ui-src/src/views/Qualifiers/Adult/index.tsx
services/ui-src/src/views/Qualifiers/Child/index.tsx
services/ui-src/src/views/Qualifiers/ChildCHIP/index.tsx
services/ui-src/src/views/Qualifiers/ChildMedicaid/index.tsx
services/ui-src/src/views/Qualifiers/HealthHome/index.tsx

Save button not working for all Qualifiers on QMR DEV. We are now refetching when the user saves
https://qmacbis.atlassian.net/jira/software/c/projects/OY2/boards/208?modal=detail&selectedIssue=OY2-18102

Save button not working for all Qualifiers on QMR DEV.

---

services/ui-auth/libs/users.json
services/ui-src/src/views/AddHHCoreSet/index.tsx

https://qmacbis.atlassian.net/browse/OY2-18225
Removing max width to allow for longer SPA-IDs for Health Home Drop down selection box

Increase width on add health home drop down

---

services/ui-src/src/measures/globalValidations/dataDrivenTools.ts

Bug fix for error in validations. This is currently causing OMS validations to fail for certain checks.

important check missing

---

.github/workflows/deploy.yml
tests/cypress/cypress/integration/measures/CBPHH.spec.ts

Adding automation to CBP-HH
Not deploying because of `ServerlessError: Maximum number of client certificates has been reached. Please contact AWS support if you need additional client certificates.`
However you can pull to see for yourself that it works. 
Let me know if I should add anything else

CBPHH Automation

---

destroy.sh

https://qmacbis.atlassian.net/browse/OY2-18073

allow destroy script to delete client certs associated with branch

---

destroy.sh

Reverts CMSgov/cms-mdct-qmr#1103

Revert "allow destroy script to delete client certs associated with branch"

---

services/ui-src/src/measures/2021/IETAD/validation.ts
services/ui-src/src/measures/globalValidations/validateOneCatRateHigherThanOtherCat/index.test.ts
services/ui-src/src/measures/globalValidations/validateOneCatRateHigherThanOtherCat/index.ts

Copy of other branch but fixing the build
https://qmacbis.atlassian.net/browse/OY2-18448

add back in validation

---

.github/workflows/deploy.yml
tests/cypress/cypress/integration/measures/FUHHH.spec.ts

laid out automation testing

---

destroy.sh

Reverts CMSgov/cms-mdct-qmr#1126

Revert "Delete Client Certs when destroying branch"

---

services/ui-src/src/components/Inputs/RadioButton/index.test.tsx
services/ui-src/src/components/Inputs/RadioButton/index.tsx
services/ui-src/src/measures/CommonQuestions/DefinitionsOfPopulation/index.tsx

Changes Radio Button component to allow for array based form data to allow consistency across Adult and Child measures Definition of Denominator data.
[Ticket to close](https://qmacbis.atlassian.net/browse/OY2-18425?atlOrigin=eyJpIjoiZDkxYmZlZTI5MjhjNGFkYzhiYmE1ZjAxYmIyNGY5NjMiLCJwIjoiaiJ9)
The handler for onChange was edited to have an valueAsArray flag that will change the radio button's values to be in an array for consistency in our validations. Unit test was partially updated to reflect this.

Oy2 18425 dod array issue

---

services/ui-src/src/measures/2021/PQI92HH/validation.ts

add in validation on totals to the measure
https://qmacbis.atlassian.net/browse/OY2-18391

Fix totals validation for PQ192-HH

---

services/ui-src/src/measures/2021/AMBCH/validation.ts
services/ui-src/src/measures/2021/FUAAD/validation.ts

Remove validation from AMB-CH
https://qmacbis.atlassian.net/browse/OY2-18392

remove validation from AMB-CH

---

.github/workflows/deploy.yml
tests/cypress/cypress/integration/measures/OUDHH.spec.ts

Create an automation test for OUDHH

Oy2 9905 automation

---

destroy.sh

Reverts CMSgov/cms-mdct-qmr#1160

Revert "master to val"

---

destroy.sh

Reverts CMSgov/cms-mdct-qmr#1150

Revert "Delete Certs "

---

.github/workflows/deploy.yml
destroy.sh
services/ui-src/src/measures/2021/OUDHH/data.ts
services/ui-src/src/measures/2021/OUDHH/index.tsx
services/ui-src/src/measures/2021/OUDHH/types.ts
services/ui-src/src/measures/2021/OUDHH/validation.ts
services/ui-src/src/measures/2021/index.tsx
tests/cypress/cypress/integration/measures/OUDHH.spec.ts

Val Deploy

---

services/app-api/serverless.yml
services/ui-auth/serverless.yml
services/ui-src/configureLocal.sh
services/ui-src/serverless.yml
services/ui/serverless.yml
services/uploads/serverless.yml
services/uploads/src/dynamoSync/handler.js
yarn.lock

Reverts CMSgov/cms-mdct-qmr#794

Revert "Oy2 17311 - Add encryption to Uploads S3 bucket and share encryption key with Mathematica"

---

services/ui-src/src/components/PCRRate/index.test.tsx
services/ui-src/src/components/PCRRate/index.tsx
tests/cypress/cypress/integration/measures/PCRHH.spec.ts

Make the outlier rate consistent between PCR-AD and PCR-HH
https://qmacbis.atlassian.net/browse/OY2-18570

Fix PCR-HH Rate Calculation

---

services/ui-src/src/components/MonthPicker/calendarPopup.tsx
services/ui-src/src/components/MonthPicker/index.tsx
services/ui-src/src/components/PCRRate/index.test.tsx
services/ui-src/src/components/PCRRate/index.tsx
services/ui-src/src/views/Qualifiers/HealthHome/costSavingsData.tsx
services/ui-src/src/views/Qualifiers/HealthHome/index.tsx
tests/cypress/cypress/integration/measures/PCRHH.spec.ts

Dev -> Val
- fix for autosave on file uploads for HH qualifiers
- Update date picker for current measure year
- Fix PCRHH outlier rate calculation

Dev -> Val

---

services/app-api/handlers/coreSets/create.ts
services/ui-auth/libs/users.json
services/ui-src/src/views/CoreSet/index.tsx
services/ui-src/src/views/StateHome/helpers.ts
yarn.lock

We are creating this PR to add additional information to the Health home coreset property which is used for routing. By adding the state suffix on both the front end and database coreset property we will correctly route our state users to the right Health Home by state. Some of these state health homes share the same ids
https://qmacbis.atlassian.net/jira/software/c/projects/OY2/boards/208?modal=detail&selectedIssue=OY2-18573

Oy2 18573 - incorrectly routing to Maine's HH SPA measure list (#133)

---

tests/cypress/cypress/integration/measures/QUALIFIERS_healthhome.spec.ts

HH Qualifier validation

---

tests/cypress/cypress/integration/features/state_specific_measures.spec.ts
yarn.lock

Automation created for state specific measures

Oy2 12731 automation Add State Specific Measures

---

tests/cypress/cypress/integration/measures/IETHH.spec.ts

Added tiny changes to existing IETTH spec file

IETHH edit automation

---

services/ui/serverless.yml
tests/cypress/cypress/integration/measures/QUALIFIERS_healthhome.spec.ts

The solution was that we removed put bucket acl permissions that were given to external accounts  
https://qmacbis.atlassian.net/jira/software/c/projects/OY2/boards/208?modal=detail&selectedIssue=OY2-18766

Cloudfront S3 Bucket Policy needs to be updated to not give excess permissions to outside accounts

---

services/ui-src/src/components/MonthPicker/calendarPopup.tsx

Some measures require data 2 years ago from the reporting year

Date range to go back 2 years

---

tests/cypress/cypress/integration/measures/SSHH.spec.ts
tests/cypress/helper.d.ts
tests/cypress/support/commands/commands.ts

Create test for functionality contained in [Oy2-18446](https://qmacbis.atlassian.net/browse/OY2-18446).
[Oy2-19030](https://qmacbis.atlassian.net/browse/OY2-19030).

[Oy2-18446] Custom State Specific Measure - Cypress Test

---

.github/workflows/deploy.yml
tests/cypress/cypress/integration/measures/AIFHH.spec.ts

AIFHH Automation

---

services/app-api/libs/authorization.ts
services/ui-auth/libs/users.json

Fix for multi role users in api authorization function
https://qmacbis.atlassian.net/browse/OY2-19198

Multi role users

---

README2.md

list api stuff

---

services/ui-src/src/index.scss
services/ui-src/src/measures/2021/AIFHH/index.tsx
services/ui-src/src/measures/2021/globalValidations/ComplexValidations/ComplexValidateNDRTotals/index.tsx

https://qmacbis.atlassian.net/browse/OY2-19139
Fixes to AIFHH
Application endpoint:  https://d39kgamyj7k51f.cloudfront.net/

AIFHH Fixes

---

README2.md

Documenting steps for Cypress under the `Testing` section of new README.
N/A
Documentation!
N/A
N/A

Cypress Testing Documentation

---

services/ui-src/src/measures/2022/OEVCH/index.tsx

Update instances of Total to match the qualifier in Performance Measure validations and Deviation from Measure Spec.
[Oy2-19141](https://qmacbis.atlassian.net/browse/OY2-19141?atlOrigin=eyJpIjoiMGZhMDMzNTgxYjRiNGQ3YWE3MTNlZjYwNWIyZmFlOTMiLCJwIjoiaiJ9)
After:

[Oy2-19141] Fix Issues with OEV-CH

---

services/ui-src/src/measures/2021/SSHH/data.ts

Remove string "(Both can be selected)" from SS-HH Hybrid Data Source.
[Oy2-19134](https://qmacbis.atlassian.net/browse/OY2-19134?atlOrigin=eyJpIjoiZjU4MGQ0NmJhOTk2NDRjZGEzNWI0ZDdiZDkxNWMyNTMiLCJwIjoiaiJ9)
To test this work, create and open a SS-HH measure. Click the checkbox for Hybrid Data Source. Confirm that the application matches the After screenshot shown below.
Before:
After:

[Oy2-19134] Update SS-HH Data Source Text

---

services/ui-src/src/components/AutocompletedMeasureTemplate/index.test.tsx
services/ui-src/src/components/AutocompletedMeasureTemplate/index.tsx
services/ui-src/src/components/MeasureButtons/index.tsx
services/ui-src/src/components/MeasureWrapper/index.tsx

https://qmacbis.atlassian.net/browse/OY2-19497
moves print button to header of autocompleted measures
Application endpoint:  https://d4zri6q1uksju.cloudfront.net/

Non state users are unable to Print fix

---

services/ui-src/src/measures/2022/FUMHH/index.tsx
yarn.lock

Add Additional notes comp to FUM-HH 2022 measure
https://qmacbis.atlassian.net/browse/OY2-19660
Including a dependabot update in this pr as well

Add additional notes to fum-hh

---

services/ui-src/src/measures/2022/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx

Showing duplicated Rates under the OMS sections of the Adult measures FY2022.
Application Endpoint: https://d1mr30gdstgocv.cloudfront.net/
Closes [MDCT-483](https://qmacbis.atlassian.net/browse/MDCT-483).

MDCT-483: Removing Extra Rate component from OMS Section

---

.env_example
README.md
services/ui-src/.env_example
src/dev.ts

I have not seen QMR local work without these changes. Just putting these here to make it easier for new devs. These changes were recently tested by Nathan when he was getting his environment set up.

Fix local dev

---

services/ui-src/src/measures/2021/HPCMIAD/data.ts
services/ui-src/src/measures/2022/AIFHH/data.ts
services/ui-src/src/measures/2022/COLHH/data.ts
services/ui-src/src/measures/2022/HPCMIAD/data.ts
services/ui-src/src/measures/2022/OUDHH/data.ts

Couple of text updates based on feedback from the business owners.
Closes [MDCT-1829](https://qmacbis.atlassian.net/browse/MDCT-1829).

MDCT-1829: BO Feedback Updates (ii)

---

services/ui-src/src/measures/2021/globalValidations/ComplexValidations/ComplexValidateDualPopInformation/index.tsx
services/ui-src/src/measures/2021/globalValidations/validateDualPopInformation/index.ts
services/ui-src/src/measures/2022/globalValidations/ComplexValidations/ComplexValidateDualPopInformation/index.tsx
services/ui-src/src/measures/2022/globalValidations/validateDualPopInformation/index.ts
src/dev.ts

Duplicating "Warning" error type.
Application endpoint: https://d2i6sdy4antu38.cloudfront.net/
Continues on [MDCT-496](https://qmacbis.atlassian.net/browse/MDCT-496).

MDCT-496.0.1: Duplicating "Warning" to Second PM Message

---

services/ui-src/src/measures/2021/Qualifiers/data.ts
services/ui-src/src/measures/2022/Qualifiers/data.ts

Correct some text for Child Core Set Questions for Medicaid and Chip individually
https://qmacbis.atlassian.net/browse/MDCT-1838
Endpoint: TBD

Update text in child qualifiers

---

services/ui-src/src/components/SubmitCoreSet/index.test.tsx
services/ui-src/src/components/SubmitCoreSet/index.tsx
services/ui-src/src/measures/2021/Qualifiers/data.ts
services/ui-src/src/measures/2022/Qualifiers/data.ts
services/ui-src/src/views/CoreSet/index.tsx

Addresses the comments Padma had in this ticket's comment section https://qmacbis.atlassian.net/browse/MDCT-1838

Label Updates for Child Core Sets

---

services/ui-src/src/measures/2021/CCPAD/validation.ts
services/ui-src/src/measures/2022/CCPAD/validation.ts

Replicating a CCP-AD validation fix to OMS validations.
Application endpoint: https://dk5e2xbd8pnpi.cloudfront.net/
Closes [MDCT-464](https://qmacbis.atlassian.net/browse/MDCT-464).

MDCT-464: Validation for CCP-AD (Replicating to OMS)

---

services/ui-src/src/measures/2022/AIFHH/index.test.tsx
services/ui-src/src/measures/2022/AMBHH/index.test.tsx
services/ui-src/src/measures/2022/CBPHH/index.test.tsx
services/ui-src/src/measures/2022/CDFHH/index.test.tsx
services/ui-src/src/measures/2022/COLHH/index.test.tsx
services/ui-src/src/measures/2022/FUAHH/index.test.tsx
services/ui-src/src/measures/2022/FUHHH/index.test.tsx
services/ui-src/src/measures/2022/FUMHH/index.test.tsx
services/ui-src/src/measures/2022/IETHH/index.test.tsx
services/ui-src/src/measures/2022/IUHH/index.test.tsx
services/ui-src/src/measures/2022/OUDHH/index.test.tsx
services/ui-src/src/measures/2022/PCRHH/index.test.tsx
services/ui-src/src/measures/2022/PQI92HH/index.test.tsx

To Add integration tests for health home measures
https://qmacbis.atlassian.net/browse/MDCT-495

Add Integration Tests For Health Home Measures

---

services/ui-auth/libs/users.json

Add state user alaska

---

services/ui-src/.env_example

This will remove developer login for prod

Fix Prod and remove 

---

services/ui-src/src/measures/2022/SSHH/questions/PerformanceMeasure.tsx

https://qmacbis.atlassian.net/browse/MDCT-501
including fix from 2021 so that it also is fixed for 2022 state specific health home measures.

Missing NDR sets in saved state specific measures for 2022

---

services/app-api/serverless.yml
services/ui-src/src/components/PCRRate/index.tsx

Releasing a fix for a Lambda timeout when generating PDFs.

VAL Release (8 September 2022)

---

services/app-api/serverless.yml
services/ui-auth/libs/users.json

Additional users as backups for Mathematica users
TY @davidkoger

Test users to val

---

services/ui-src/src/measures/2021/CommonQuestions/DateRange/index.test.tsx
services/ui-src/src/measures/2021/CommonQuestions/DateRange/index.tsx
services/ui-src/src/measures/2022/CommonQuestions/DateRange/index.test.tsx
services/ui-src/src/measures/2022/CommonQuestions/DateRange/index.tsx

Closes [MDCT-1946](https://qmacbis.atlassian.net/browse/MDCT-1946).
Update links for Measurement Period Tables in FY2021 and FY2022.

 MDCT-1946: Update Links on Measurement Period Table

---

.github/PULL_REQUEST_TEMPLATE.md

Updating PR Template

---

services/ui-src/src/components/MeasureWrapper/index.tsx
tests/cypress/cypress/integration/measures/APMCH.spec.ts
tests/cypress/cypress/integration/measures/QUALIFIERS_adult.spec.ts
tests/cypress/cypress/integration/measures/WCCCH.spec.ts

`val` Release:
* Updated PR template
* [MDCT-1961](https://qmacbis.atlassian.net/browse/MDCT-1961): Fix for SS-HH measures not loading on refresh

VAL Release

---

.github/PULL_REQUEST_TEMPLATE.md
services/ui-src/src/components/MeasureWrapper/index.tsx
tests/cypress/cypress/integration/measures/APMCH.spec.ts
tests/cypress/cypress/integration/measures/QUALIFIERS_adult.spec.ts
tests/cypress/cypress/integration/measures/WCCCH.spec.ts

`val` -> `prod`
* Updated PR template
* [MDCT-1961](https://qmacbis.atlassian.net/browse/MDCT-1961): Bug Fix for State-Specific Health Home Measures

PROD Release (27 September 2022)

---

.github/PULL_REQUEST_TEMPLATE.md
services/ui-src/src/components/MeasureWrapper/index.tsx
tests/cypress/cypress/integration/measures/APMCH.spec.ts
tests/cypress/cypress/integration/measures/QUALIFIERS_adult.spec.ts
tests/cypress/cypress/integration/measures/WCCCH.spec.ts

Reverts CMSgov/cms-mdct-qmr#1525

Revert "VAL Release"

---

.github/PULL_REQUEST_TEMPLATE.md
services/ui-src/src/components/MeasureWrapper/index.tsx
tests/cypress/cypress/integration/measures/APMCH.spec.ts
tests/cypress/cypress/integration/measures/QUALIFIERS_adult.spec.ts
tests/cypress/cypress/integration/measures/WCCCH.spec.ts

Reverts CMSgov/cms-mdct-qmr#1527

Revert "PROD Release (27 September 2022)"

---

.github/CODEOWNERS

Can't believe Karla wasn't on here

add more owners!

---

services/app-api/yarn.lock
services/ui-src/yarn.lock
services/uploads/yarn.lock
yarn.lock

All the pending dependabot updates

Dependabot batch

---

.github/CODEOWNERS

add thomas to codeowners

---

services/uploads/serverless.yml

Skipping master with its other changes -- trying to make this as risk free as possible

Isolating change from val to skip other content in master

---

services/ui/serverless.yml

TLS update, going to dev, then will verify

COMP: Updated TLS for QMR

---

services/ui/serverless.yml
services/uploads/serverless.yml

Changes the bucket policies. Need to review in a deployed environment.
Let it deploy and check the bucket policy on the buckets.  Compare the bucket policies in prod where there are warnings in security hub to the same named buckets in dev and you should see a policy in dev where in prod you see

WIP: S3 bucket root level not covered under policy

---

.github/workflows/deploy.yml

adding the branchname hash required for dependabot (#1606)

---

services/uploads/src/clamav.js

ClamAV scan was reported as not flagging malicious files.
See related fix: https://github.com/CMSgov/managed-care-review/pull/1483/files
We'll get this in dev and val, then use a vm to upload and test file.
N/A

Fix for AVScan failure

---

services/ui-auth/libs/users.json

Add New State User (Hawaii)

---

.github/PULL_REQUEST_TEMPLATE.md
.gitignore
.pre-commit-config.yaml
README.md
package.json

This PR makes a handful of updates related to repo migration from CMSgov organization to Enterprise-CMCS organization.
_Note: This PR should be merged through prod to finalize repo migration due to some related needed changes to AWS IAM trust policies that need to be deployed._
n/a
n/a
n/a

make updates related to repo migration

---

services/app-api/serverless.yml
src/dev.ts

Managed to have 2 breaking changes to local app-api in last PR.
Verify you can deploy code locally.

fixing app-api local twice.

---

services/ui-src/src/measures/2023/shared/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx
services/ui-src/src/measures/2023/shared/CommonQuestions/OtherPerformanceMeasure/index.test.tsx
services/ui-src/src/measures/2023/shared/CommonQuestions/OtherPerformanceMeasure/index.tsx
services/ui-src/src/measures/2023/shared/CommonQuestions/PerformanceMeasure/index.test.tsx

Merging val/impl→ prod. 
In this deployment:
- Add option to delete a rate ([1663](#1663))
- Add additional line break fix for formula ([1665](#1665))
n/a
n/a
n/a

val → prod

---

services/ui-src/src/measures/2023/shared/globalValidations/ComplexValidations/ComplexValidateNDRTotals/index.tsx

let users input 0 and blanks and successfully validate

---

services/ui-src/src/measures/2023/shared/CommonQuestions/DefinitionsOfPopulation/index.tsx

text change

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE/test-to-val-deployment.md
.github/PULL_REQUEST_TEMPLATE/val-to-prod-deployment.md

Updating PR templates and codeowners
n/a
n/a
n/a

update PR templates & codeowners

---

services/ui-src/src/measures/2023/PQI01AD/data.ts
services/ui-src/src/measures/2023/PQI05AD/data.ts
services/ui-src/src/measures/2023/PQI08AD/data.ts
services/ui-src/src/measures/2023/PQI15AD/data.ts

Measure description has been updated in the following measures:
- PQI01-AD
- PQI05-AD
- PQI08-AD
- PQI15-AD
shorten branch name so that the deploy will run
MDCT-2354
MDCT-2355
MDCT-2356
MDCT-2357
---
See Jira ticket for new text for:
PQI01-AD [MDCT-2354]
PQI05-AD [MDCT-2355]
PQI08-AD [MDCT-2356]
PQI15-AD [MDCT-2357]
---
---

measure description updates

---

services/ui-src/src/measures/2023/CCPAD/data.ts
services/ui-src/src/measures/2023/COLAD/data.ts
services/ui-src/src/measures/2023/FUAAD/data.ts
services/ui-src/src/measures/2023/IETAD/data.ts
services/ui-src/src/measures/2023/NCIDDSAD/index.tsx
services/ui-src/src/measures/2023/rateLabelText.ts
services/ui-src/src/measures/measureDescriptions.ts

A lot of small text changes for different 2023 measures. First batch.
MDCT-2346
MDCT-2353
MDCT-2348
MDCT-2349
MDCT-2350
MDCT-2352
---
View these measures on 2023 reports, refer to JIRA ticket for text update
AAB-AD [MDCT-2346]
1) Title update to: AAB-AD - Avoidance of Antibiotic Treatment for Acute Bronchitis/Bronchiolitis: Age 18 And Older
NCIDDS-AD [MDCT-2353]
1) Title update & description change
CCP-AD [MDCT-2348]
1) Description update
COL-AD [MDCT-2349]
1) New N/D/R:  Ages 46 to 49
FUA-AD [MDCT-2350]
1) Title update & description change
IED-AD [MDCT-2352]
1) Title update & description change
---
---

Batch text changes

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE/test-to-val-deployment.md
.github/PULL_REQUEST_TEMPLATE/val-to-prod-deployment.md
services/ui-src/src/components/DateRange/index.test.tsx
services/ui-src/src/components/DateRange/index.tsx
services/ui-src/src/components/MeasureWrapper/index.tsx
services/ui-src/src/dataConstants.ts
services/ui-src/src/measures/2021/CommonQuestions/PerformanceMeasure/index.test.tsx
services/ui-src/src/measures/2023/BCSAD/data.ts
services/ui-src/src/measures/2023/CCPAD/data.ts
services/ui-src/src/measures/2023/COLAD/data.ts
services/ui-src/src/measures/2023/FUAAD/data.ts
services/ui-src/src/measures/2023/IETAD/data.ts
services/ui-src/src/measures/2023/NCIDDSAD/index.tsx
services/ui-src/src/measures/2023/PQI01AD/data.ts
services/ui-src/src/measures/2023/PQI05AD/data.ts
services/ui-src/src/measures/2023/PQI08AD/data.ts
services/ui-src/src/measures/2023/PQI15AD/data.ts
services/ui-src/src/measures/2023/SSHH/index.test.tsx
services/ui-src/src/measures/2023/SSHH/questions/PerformanceMeasure.tsx
services/ui-src/src/measures/2023/rateLabelText.ts
services/ui-src/src/measures/2023/shared/CommonQuestions/DefinitionsOfPopulation/index.tsx
services/ui-src/src/measures/2023/shared/CommonQuestions/OtherPerformanceMeasure/index.tsx
services/ui-src/src/measures/2023/shared/CommonQuestions/PerformanceMeasure/index.test.tsx
services/ui-src/src/measures/2023/shared/CommonQuestions/PerformanceMeasure/index.tsx
services/ui-src/src/measures/2023/shared/globalValidations/ComplexValidations/ComplexValidateNDRTotals/index.tsx
services/ui-src/src/measures/measureDescriptions.ts
services/ui-src/yarn.lock
yarn.lock

I am a pull request. I fix a merge conflict.

Pull request

---

README.md

Just updating some language in the README.
n/a
---
n/a
n/a
---
---

remove eua job code language

---

.github/PULL_REQUEST_TEMPLATE/test-to-val-deployment.md
.github/PULL_REQUEST_TEMPLATE/val-to-prod-deployment.md

Simple updates to PR template
n/a
---
n/a
n/a
---
---

pr template updates

---

.github/PULL_REQUEST_TEMPLATE/test-to-val-deployment.md
.github/PULL_REQUEST_TEMPLATE/val-to-prod-deployment.md

test → val

---

services/ui-src/src/measures/2023/APMCH/data.ts
services/ui-src/src/measures/2023/APMCH/index.tsx
services/ui-src/src/measures/2023/CISCH/data.ts
services/ui-src/src/measures/2023/IMACH/data.ts

Added new Electronic Clinical Data Systems (EDCS) to APM-CH, CIS-CH & IMA-CH for Reporting Year 2023.
MDCT-2396
MDCT-2397
MDCT-2398
---
1) Login & Select Reporting Year 2023
2) Add Child Core Set, I don't think it matters if combined or separated 
3) Go into Child Core Set Measures
4) Open APM-CH measures, scroll to Data Source and look for **Electronic Clinical Data Systems (EDCS)** checkbox
5) Repeat for CIS-CH & IMA-CH 
---
---

New Data Source in CH

---

services/ui-src/src/measures/2023/ADDCH/data.ts
services/ui-src/src/measures/2023/CCPCH/data.ts
services/ui-src/src/measures/2023/FUACH/data.ts
services/ui-src/src/measures/2023/PPCCH/data.ts
services/ui-src/src/measures/2023/rateLabelText.ts
services/ui-src/src/measures/measureDescriptions.ts

The smallest of text changes across different child measures.
- ADD-CH - added a data source and the word "a"
- CCP-CH - changed 60 to 90
- FUA-CH - title and measure description update
- PPC-CH - Added two commas
- CCP-CH - N/D/R - Changed Sixty to Ninety
MDCT-2362
MDCT-2363
MDCT-2365
MDCT-2367
MDCT-2369
---
1) Sign in and go to Reporting Year 2023
2) Create Add Child Core Set, (choose either separate or combined)
Note: For each measures, select the first radio button in the first 3 questions to have measure description reveal itself
3) Go to ADD-CH, 
- look at data source for checkbox Electronic Clinical Data Systems (ECDS),  
- look at ticket for measure description update [MDCT-2362]
4) Go to CCP-CH, look at ticket for measure description update [MDCT-2363]
5) Go to FUA-CH look at …

Child Measure Descriptions

---

services/ui-src/src/measures/2023/rateLabelText.ts

Swap first and last items in Performance Measures for MSC-AD
MDCT-2255
---
I think the best way to test this is to fill out the form and in the code swap the order and see that the numbers are still with their correct label. 
---
---

MDCT-2255 swap list order

---

.github/build_vars.sh
.github/workflows/codeql-analysis.yml
.github/workflows/cypress-workflow.yml
.github/workflows/deploy.yml
.github/workflows/destroy.yml
.github/workflows/pre-commit.yml
.github/workflows/pull-request.yml
.github/workflows/unittest-workflow.yml

- Fixes a CodeQL warning
- Adds automatic author assignment for PRs
- Gets unit tests running on all branches again
- Removes unnecessary CodeClimate test reporter ID
n/a
---
n/a
n/a
---
---

fix codeql warning & add author assignment

---

.github/workflows/pull-request.yml

Adding a check for missing deploys to limit confusion on why Cypress Tests fail in the Pull Request Workflow
---
All the magic happens in the build pipeline. 
---
---

Bugfix pr workflow3

---

.github/workflows/deploy.yml

Trying to fix unit tests so they run on every branch.
n/a
---
n/a
n/a
---
---

get codeclimate reporting working

---

services/ui-src/src/measures/2023/PQI92HH/data.ts

Text changes for PQI92-HH (specifically FFY 2023 measures)
MDCT-2380
---
- Login using the stateuser4@test.com user
- Add health home core data set in 2023
- Open health home core data set, navigate to PQI92-HH
- See corresponding text changes
- Measure description change: Choose AHRQ under "Measurement Specification", navigate down to Performance Measure section and confirm text changes
---
---

Tech Spec Changes - PQI92-HH

---

services/ui-src/src/measures/measureDescriptions.ts

Quick update to change NCIDDS-AD title from **National Core Indicators Survey-Intellectual and Developmental Disabilities** to **National Core Indicators Survey**
MDCT-2438
---
2) Select Reporting Year 2023
3) Open Adult Core Set Measures
4) Scroll to NCIDDS-AD and check for the title change
N/A
---
---

Update NCIDDS-AD Title

---

.github/workflows/pull-request.yml

Existence is suffering.
n/a
---
n/a
n/a
---
---

reverting a previous change because CI/CD is a mirage and workflows are a prison

---

services/database/yarn.lock
services/ui-src/src/measures/2023/rateLabelText.ts

Updated from David's comment:
> One minor change and this is on me, can we make the order of the labels be Percentage of current smokers and tobacco users → Advising Smokers and Tobacco Users to Quit ->Discussing Cessation Medications → Discussing Cessation Strategies?
MDCT-2255
---
Go to MSC-AD in 2023, answer first three questions, see in the Performance Measures that the order is as follows:
Percentage of Current Smokers and Tobacco Users
Advising Smokers and Tobacco Users to Quit
Discussing Cessation Medications
Discussing Cessation Strategies
---
---

reorder per David Ks comment

---

services/app-api/handlers/dynamoUtils/measureList.ts
services/ui-src/src/measures/2023/AABCH/data.ts
services/ui-src/src/measures/2023/AABCH/index.test.tsx
services/ui-src/src/measures/2023/AABCH/index.tsx
services/ui-src/src/measures/2023/AABCH/types.ts
services/ui-src/src/measures/2023/AABCH/validation.ts
services/ui-src/src/measures/2023/index.tsx
services/ui-src/src/measures/2023/rateLabelText.ts
services/ui-src/src/measures/measureDescriptions.ts

MDCT-2425
---
1. Log into stateuser4
2. Add a child core set in 2023
3. Open the child core set and open AAB-CH
4. Match with ticket specs
---
---

[QMR] New Measure - AAB-CH

---

destroy.sh

Add destroy fix to QMR
MDCT-2647
---
N/A
---
---

Add destroy fix to QMR

---

services/ui-src/src/libs/spaLib.ts
tests/cypress/cypress/integration/measures/adult/HBDAD.spec.ts

Updates made to a few SPA ID numbers
Iowa | Iowa Health Home Services | IA 20-0010 -> IA 22-0003
Maine | Maine Health Home for Beneficiaries Receiving Medication Assisted Treatment for Opioid Addiction | ME 18-0032 -> ME 22-0018
Michigan | Opioid Health Home | MI 20-1501 -> MI 22-1501
New York | Health Home for High-Cost, High-Needs Enrollees | 
NY 20-0054 -> NY 21-0072
New York | New York I/DD Health Home Services | NY 17-0025 -> NY 22-0073
Rhode Island | Rhode Island Opioid Treatment Program Health Home Services | 
RI 16-006 -> RI 21-0025
MDCT-2472
---
Log in as one of the state users above (eg: stateuserNY@test.com) and go to 2023, add Heath Home measures, see the drop downs match the requested changes, and that the changes are in the HH headers as well.
---
---
_convert to a different …

label changes

---

services/ui-src/package.json
services/ui-src/yarn.lock

[Dependabot 22](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/22)
[Dependabot 23](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/23)
[Dependabot 32](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/32)
[Dependabot 60](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/60)
---
---
---

Dependabot Alert #22, #23, #32, #60: node-forge Vulnerabilities

---

services/ui-src/package.json
services/ui-src/yarn.lock

[Dependabot 13](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/13)
---
---
---

Dependabot Alert #13: Inefficient Regular Expression Complexity in nth-check

---

services/ui-src/package.json
services/ui-src/yarn.lock

[Dependabot 5](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/5)
---
---
---

Dependabot Alert #5: Code Injection in pac-resolver

---

services/uploads/package.json
services/uploads/yarn.lock

[Dependabot 127](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/127)
[Dependabot 128](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/128)
[Dependabot 153](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/153)
---
---
---

Dependabot Alerts #127, #128, #153: jsonwebtoken Vulnerabilities

---

services/ui-src/package.json
services/ui-src/yarn.lock

[Dependabot 36](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/36)
---
---
---

Dependabot Alert #36: node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor

---

services/ui-src/package.json
services/ui-src/yarn.lock

[Dependabot 105](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/105)
---
---
---

Dependabot Alert #105: Code Injection in pac-resolver

---

services/ui-src/package.json
services/ui-src/yarn.lock

[Dependabot 110](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/110)
---
---
---

Dependabot Alert #110: minimatch ReDoS vulnerability

---

services/ui-src/package.json
services/ui-src/yarn.lock

[Dependabot 58](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/58)
[Dependabot 59](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/59)
---
---
---

Dependabot Alerts #58 + #59: Improper Verification of Cryptographic Signature in node-forge

---

.github/workflows/git-secrets.yaml
.gitleaks.toml
.pre-commit-config.yaml
SECRETSCANNING.md

Adding Secret Scanning tools Gitleaks and Pre-commit

---

.github/workflows/snyk-test.yml

Two workflow Jobs
Runs during PR creation on main and outputs the findings in GitHub Workflow console
Runs on Cron and creates JIRA ticket based on findings
JIRA ticket behavior
Existing ticket check is set to default 60days, this can be adjusted as needed.
The same Vulnerability can re-exist after the resolution when a the same package is added for this reason there is a check for Closed or Cancelled ticket and based on that a ticket get created.
SNYK Ignore
There is a .snyk file in the root directory that can hold a list of snyk ignore ids, a vulnerability can be manually added there following the same synaxt in the file, so when Snyk scan runs all the vulnerabilities in .snyk file will be ignored.
Important updates
Author checklist
I have performed a self-review of my code
I have added …

updated snyk custom action version

---

README.md

PR to kick another deploy action off
---
---
---

Val: force action run

---

services/ui-src/src/components/IETRate/index.test.tsx

Second time's the charm at getting the unit test for IETRate to calculate.
MDCT-2558
---
N/A
N/A
---
---

Unit Test for Cross Category Calculation

---

README.md
package.json
services/app-api/package.json
services/app-api/yarn.lock
services/database/package.json
services/database/yarn.lock
services/stream-functions/package.json
services/stream-functions/yarn.lock
services/ui-auth/package.json
services/ui-auth/yarn.lock
services/ui-src/package.json
services/ui-src/yarn.lock
services/ui/package.json
services/ui/yarn.lock
services/uploads/package.json
services/uploads/yarn.lock
yarn.lock

CMS repos are migrating to Enterprise-CMCS. Update any references to the moved repos.
MDCT-2753
---
Run it locally, everything still works
---
---

Update CMS repos

---

destroy.sh

- improved bucket cleanup (doesn't silent fail when bucket has too many objects)
- remove acl for clean app-api destruction
- remove hanging log groups
---
Create a branch
Destroy it using script
Win

Add improvements from other destroy scripts

---

services/app-api/types.ts
services/ui-auth/libs/users.json
services/ui-src/src/types.ts
services/ui-src/src/views/Home/index.tsx

QMR is getting a read-only Internal User just like the other apps. The application should treat the Internal User role exactly the same as the Help Desk role (the only difference between the two lies in IDM permissions outside of our system).
n/a
---
1. Log in as Internal User (see `users.json`). Confirm that everything is read-only, the exact same as Help Desk user.
n/a
---
---

internal user initial setup

---

tests/cypress/cypress/e2e/measures/adult/AMRAD.spec.ts
tests/cypress/cypress/e2e/measures/adult/BCSAD.spec.ts
tests/cypress/cypress/e2e/measures/adult/CBPAD.spec.ts
tests/cypress/helper.d.ts

Mdct 2554 cy2023 2

---

tests/cypress/cypress.config.ts
tests/cypress/cypress/e2e/measures/adult/FUMAD.spec.ts
tests/cypress/cypress/e2e/measures/adult/FVAAD.spec.ts
tests/cypress/cypress/e2e/measures/adult/HBDAD.spec.ts
tests/cypress/cypress/e2e/measures/adult/HPCMIAD.spec.ts

Mdct 2554 cy2023 ad 5

---

tests/cypress/cypress/e2e/measures/adult/OHDAD.spec.ts
tests/cypress/cypress/e2e/measures/adult/OUDAD.spec.ts

Mdct 2554 cy2023 ad 7

---

tests/cypress/cypress/e2e/measures/adult/PCRAD.spec.ts
tests/cypress/cypress/e2e/measures/adult/PPCAD.spec.ts

Mdct 2554 cy2023 ad 8

---

tests/cypress/cypress/e2e/measures/adult/PQI01AD.spec.ts
tests/cypress/cypress/e2e/measures/adult/PQI05AD.spec.ts
tests/cypress/cypress/e2e/measures/adult/PQI08AD.spec.ts
tests/cypress/cypress/e2e/measures/adult/PQI15AD.spec.ts

Mdct 2554 cy2023 ad 9

---

tests/cypress/cypress/e2e/measures/adult/QUALIFIERS_adult.spec.ts
tests/cypress/cypress/e2e/measures/adult/SAAAD.spec.ts
tests/cypress/cypress/e2e/measures/adult/SSDAD.spec.ts

Mdct 2554 cy2023 ad 10

---

tests/cypress/cypress/e2e/init/create_delete_healthhome.spec.ts
tests/cypress/cypress/e2e/measures/healthhome/AIFHH.spec.ts
tests/cypress/cypress/e2e/measures/healthhome/CBPHH.spec.ts
tests/cypress/cypress/e2e/measures/healthhome/CDFHH.spec.ts
tests/cypress/cypress/e2e/measures/healthhome/FUAHH.spec.ts
tests/cypress/cypress/e2e/measures/healthhome/FUHHH.spec.ts
tests/cypress/cypress/e2e/measures/healthhome/IETHH.spec.ts
tests/cypress/cypress/e2e/measures/healthhome/IUHH.spec.ts
tests/cypress/cypress/e2e/measures/healthhome/OUDHH.spec.ts
tests/cypress/cypress/e2e/measures/healthhome/PCRHH.spec.ts
tests/cypress/cypress/e2e/measures/healthhome/PQI92HH.spec.ts
tests/cypress/cypress/e2e/measures/healthhome/QUALIFIERS_healthhome.spec.ts
tests/cypress/cypress/e2e/measures/healthhome/SSHH.spec.ts

Mdct 2554 cy2023 health home measure updates

---

services/ui-src/src/measures/2023/rateLabelText.ts
tests/cypress/cypress/e2e/measures/child/ADDCH.spec.ts
tests/cypress/cypress/e2e/measures/child/AMBCH.spec.ts
tests/cypress/cypress/e2e/measures/child/AMRCH.spec.ts
tests/cypress/cypress/e2e/measures/child/APMCH.spec.ts
tests/cypress/cypress/e2e/measures/child/CCPCH.spec.ts

Mdct 2554 cy2023 ch 1

---

tests/cypress/cypress/e2e/measures/child/CCWCH.spec.ts
tests/cypress/cypress/e2e/measures/child/CDFCH.spec.ts
tests/cypress/cypress/e2e/measures/child/CHLCH.spec.ts
tests/cypress/cypress/e2e/measures/child/CISCH.spec.ts
tests/cypress/cypress/e2e/measures/child/CPCCH.spec.ts

Mdct 2554 cy2023 ch 2

---

tests/cypress/cypress/e2e/measures/child/DEVCH.spec.ts
tests/cypress/cypress/e2e/measures/child/FUHCH.spec.ts
tests/cypress/cypress/e2e/measures/child/IMACH.spec.ts
tests/cypress/cypress/e2e/measures/child/PPCCH.spec.ts
tests/cypress/cypress/e2e/measures/child/SFMCH.spec.ts

Mdct 2554 cy2023 ch 3

---

tests/cypress/cypress/e2e/init/create_delete_child.spec.ts
tests/cypress/cypress/e2e/measures/child/APPCH.spec.ts
tests/cypress/cypress/e2e/measures/child/QUALIFIERS_child.spec.ts
tests/cypress/cypress/e2e/measures/child/W30CH.spec.ts
tests/cypress/cypress/e2e/measures/child/WCCCH.spec.ts
tests/cypress/cypress/e2e/measures/child/WCVCH.spec.ts

remaining child measure test

---

services/ui-src/src/measures/2023/rateLabelText.ts
tests/cypress/cypress/e2e/features/PRINT.spec.ts
tests/cypress/cypress/e2e/features/partially_completed_validation.spec.ts
tests/cypress/cypress/e2e/features/reporting_in_FY21_tag_for_alt_data_sources.spec.ts
tests/cypress/cypress/e2e/features/restructuring_data_source_text_boxes.spec.ts
tests/cypress/cypress/e2e/features/state_specific_measures.spec.ts
tests/cypress/cypress/e2e/features/submit_coreset.spec.ts
tests/cypress/cypress/e2e/features/update_user_auth_handling_in_ui.spec.ts
tests/cypress/cypress/e2e/features/user_must_select_a_data_source_selection_validation.spec.ts
tests/cypress/cypress/e2e/measures/adult/CDFAD.spec.ts
tests/cypress/cypress/e2e/measures/adult/CHLAD.spec.ts
tests/cypress/cypress/e2e/measures/adult/PQI05AD.spec.ts

Mdct 2554 cy2023 features 2

---

.github/workflows/snyk-test.yml

Description
Two workflow Jobs
Runs during PR creation on main and outputs the findings in GitHub Workflow console
Runs on Cron and creates JIRA ticket based on findings
Here is a sample JIRA output
https://qmacbis.atlassian.net/browse/MDCT-2579
JIRA ticket behavior
Exisitng ticket check is set to default 60days, this can be adjusted as needed.
The same Vulnerability can re-exist after the resoultion when a the same package is added for this reason there is acheck for Closed or Cancelled ticket and based on that a ticket get created.
SNYK Ignore
There is a .snyk file in the root directory that can hold a list of snyk ignore ids, a vulnerabiity can be manually added there following the same synaxt in the file, so when Snyk scan runs all the vulnerabilities in .snyk file will be ignored. …

updated action and added assignee

---

services/ui-auth/libs/users.json

---
- Adding a new `Virginia` state user

test → val (18 August 2023)

---

.github/workflows/scan_security-hub-jira-integration.yml
.github/workflows/scan_snyk-jira-integration.yml
.github/workflows/snyk-test.yml

The workflow wasn't running when we wanted it to, was erroneously assigning @BearHanded instead of @kx6z, and needed to have custom field selection IDs updated.
Changes made:
- Snyk & SecurityHub workflow cron jobs updated to run daily at 6am UTC.
- Auto-assignee is now Rehman instead of Brendan.
- Custom `Application` field selection ID is now correct for this app.
- Update workflow filenames to be more descriptive.
PS - Do you like this PR? If so, you're in luck -- there's a matching one in each repo for you to review and approve!
n/a
---
n/a
n/a
---
---

update security scan / jira integration workflows

---

.gitignore
tests/cypress/cypress/e2e/features/kebab_menu_measures.spec.ts

This kebab e2e test was relying on some stuff that just wasn't cutting it. Had to fix it up.
n/a
---
n/a
n/a
---
---

fix kebabs

---

.github/workflows/deploy.yml
.github/workflows/scan_security-hub-jira-integration.yml
.github/workflows/scan_snyk-jira-integration.yml
.github/workflows/snyk-auto-merge.yml

updated Both snyk and security hub workflow configurations with Jira Enterprise values
---
---

updated to jira ent

---

services/ui-src/yarn.lock

Dependabot https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/36
[Broken PR](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/pull/440)
---
- QMR starts up ok. All tests pass.

Dependabot workaround for node fetch

---

.github/build_vars.sh
.github/waf-controller.sh
.github/workflows/cypress-workflow.yml
.github/workflows/deploy.yml
services/ui/package.json
services/ui/serverless.yml
services/ui/yarn.lock

CMDCT-3171 - Apply VPN restriction to dev
After the release validate Val works without the VPN

Dev -> Val : VPN restriction

---

services/ui-src/src/measures/2024/PQI92HH/types.ts
services/ui-src/src/measures/2024/shared/globalValidations/dataDrivenTools.test.ts

A couple of references to FFY2023 were pulled into FFY2024, this is cleaning them up.
CMDCT-3291
---
N/A
---
---

CMDCT-3291: Update References from FFY2023 to FFY2024

---

services/ui-auth/handlers/createUsers.js

Set flag to see if Cognito will not try to send emails through SES using the account default address which has a low daily limit
CMDCT-
I didn't create a ticket....
---
---
---

Attempt to suppress email

---

services/ui-src/src/measures/2024/CDFCH/data.ts
services/ui-src/src/measures/2024/CISCH/data.ts

Text change in CIS-CH
- Remove the word "separate"
Text change in CDF-CH
- Change "eligible" to "qualifying"
CMDCT-3326
CMDCT-3327
---
2) Create child measure
3) Go to CIS-CH
4) In Measure Specification section, select the first bullet
5) Scroll down to performance measure and check to make sure the text matches the ticket: https://jiraent.cms.gov/browse/CMDCT-3327
6) Repeat step 5 & 6 for CDF-CH: https://jiraent.cms.gov/browse/CMDCT-3326
---
---

CIS-CH & CDF-CH: Update text

---

services/ui-src/src/measures/2024/OEVCH/data.ts
services/ui-src/src/measures/2024/rateLabelText.ts

CMDCT-3332
---
Create child core set
go to OEV-CH
Select first option in performance measures
see text matches AC
---
---

cmdct-3332 - OEV-CH text changes

---

services/app-api/handlers/dynamoUtils/measureList.ts
services/ui-src/src/measures/2024/PPC2CH/data.ts
services/ui-src/src/measures/2024/PPC2CH/index.test.tsx
services/ui-src/src/measures/2024/PPC2CH/index.tsx
services/ui-src/src/measures/2024/PPC2CH/validation.ts
services/ui-src/src/measures/2024/index.tsx
services/ui-src/src/measures/2024/rateLabelText.ts
services/ui-src/src/measures/measureDescriptions.ts

PPC-CH is now PPC2-CH and there are some content & rate label changes.
CMDCT-3333
---
2) Create a child coreset
3) There should be no PPC-CH and it should be PPC2-CH in the measure list.
4) Select PPC2-CH
5) In Measure Specification section, select the first bullet to open up Performance Section
6) Refer to ticket for content changes: https://jiraent.cms.gov/browse/CMDCT-3333
N/A
---
---

PPC-CH Content and Rate updates

---

.env_example
.github/branchNameValidation.sh
services/app-api/handlers/dynamoUtils/measureList.ts
services/app-api/handlers/prince/pdf.ts
services/app-api/handlers/prince/tests/pdf.test.ts
services/app-api/package.json
services/app-api/serverless.yml
services/app-api/yarn.lock
services/ui-src/src/measures/2024/ADDCH/data.ts
services/ui-src/src/measures/2024/CDFCH/data.ts
services/ui-src/src/measures/2024/CISCH/data.ts
services/ui-src/src/measures/2024/FUMCH/data.ts
services/ui-src/src/measures/2024/OEVCH/data.ts
services/ui-src/src/measures/2024/PPC2CH/data.ts
services/ui-src/src/measures/2024/PPC2CH/index.test.tsx
services/ui-src/src/measures/2024/PPC2CH/index.tsx
services/ui-src/src/measures/2024/PPC2CH/validation.ts
services/ui-src/src/measures/2024/index.tsx
services/ui-src/src/measures/2024/rateLabelText.ts
services/ui-src/src/measures/2024/shared/CommonQuestions/PerformanceMeasure/data.ts
services/ui-src/src/measures/2024/shared/CommonQuestions/PerformanceMeasure/index.tsx
services/ui-src/src/measures/measureDescriptions.ts
services/ui-src/yarn.lock

---
- PPC-CH to PPC2-CH: Content and Rate updates ([CMDCT-3333](https://jiraent.cms.gov/browse/CMDCT-3333))
- FUM-CH Text Changes ([CMDCT-3331](https://jiraent.cms.gov/browse/CMDCT-3331))
- OEV-CH Text Changes ([CMDCT-3332](https://jiraent.cms.gov/browse/CMDCT-3332))
- CIS-CH & CDF-CH: Text Changes ([CMDCT-3326](https://jiraent.cms.gov/browse/CMDCT-3326), [CMDCT-3327](https://jiraent.cms.gov/browse/CMDCT-3327))
- ADD-CH Content Updates ([CMDCT-3324](https://jiraent.cms.gov/browse/CMDCT-3324))
- Fix branch name validation script ([CMDCT-3222](https://jiraent.cms.gov/browse/CMDCT-3222))
- DocRaptor PDF Gen ([CMDCT-3249](https://jiraent.cms.gov/browse/CMDCT-3249))

Master -> Val

---

services/ui-src/src/measures/2024/CCPCH/data.ts

Updating the Performance Measure description section of CCP-CH to include numbering as seen below:
CMDCT-3325
---
- Add child core sets
- Navigate to CCP-CH
Verify that the Performance Measures description matches the screenshot.
---
---

CMDCT-3325.I: Content Updates for CCP-CH

---

services/ui-src/src/measures/2024/CCSAD/data.ts

Text change to CCS-AD 2024
CMDCT-3384
---
Login as any user -> go to CCS-AD
Make these selections
See that text in Performance Measures matches the card
---
---

text change CCS-AD 2024

---

services/ui-src/src/measures/2024/CDFAD/data.ts

Text change CDF-AD
CMDCT-3385
---
Login as any user -> CCS-AD
Make these selections
See that the text in Performance Measures matches the card
---
---

cmdct-3385 text change CDF-AD

---

services/ui-src/src/measures/2024/COLAD/data.ts
services/ui-src/src/measures/2024/rateLabelText.ts

Text changes COL-AD 2024
CMDCT-3386
---
Login as any user, go to COL-AD, make these selections:
See that the text and rate labels in the Performance Measures match the card
---
---

cmdct-3386 text changes COL-AD 2024

---

services/ui-src/src/measures/2024/HBDAD/data.ts
services/ui-src/src/measures/2024/rateLabelText.ts
tests/cypress/cypress/e2e/measures/adult/HBDAD.spec.ts

updates to HBD-AD 2024

---

services/ui-src/src/measures/2024/OUDAD/data.ts

text update to OUD-AD 2024
CMDCT-3388
---
---
---

cmdct-3394 text update to OUD-AD 2024

---

services/app-api/handlers/dynamoUtils/measureList.ts
services/ui-src/src/measures/2024/PPC2AD/data.ts
services/ui-src/src/measures/2024/PPC2AD/index.test.tsx
services/ui-src/src/measures/2024/PPC2AD/index.tsx
services/ui-src/src/measures/2024/PPC2AD/validation.ts
services/ui-src/src/measures/2024/index.tsx
services/ui-src/src/measures/2024/rateLabelText.ts
services/ui-src/src/measures/measureDescriptions.ts
tests/cypress/cypress/e2e/a11y/ppc2adPage.spec.ts
tests/cypress/cypress/e2e/a11y/ppcadPage.spec.ts
tests/cypress/cypress/e2e/measures/adult/PPC2AD.spec.ts
tests/cypress/support/constants.ts

PPC-AD is now PPC2-AD and there are some content & rate label changes.
CMDCT-3395
---
2. Create a child coreset
3. There should be no PPC-CH and it should be PPC2-AD in the measure list.
4. Select PPC2-AD
5. In Measure Specification section, select the first bullet to open up Performance Section
6. Refer to ticket for content changes: https://jiraent.cms.gov/browse/CMDCT-3395
N/A
---
---

PPC-AD to PPC2-AD

---

.github/workflows/deploy.yml

This typo has been bugging me. No end user impact.
n/a
---
Look at the deploy logs for this branch
n/a
---
- ~[ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary~

Fix a typo in deploy.yml

---

services/ui-src/package.json
services/ui-src/yarn.lock

Pac Resolver was likely manually installed to resolve a different issue but 7.0.1 has an exploit. Remove the package.
N/A (which is odd, a ticket should exist, it is flagged in snyk?)
---
Deployed Branch: https://d1ubgplp6abhb3.cloudfront.net/
Successful deploy, this package is normally used in the deploy process by serverless.
---
---
---

Remove Pac-Resolver manual install

---

.github/workflows/scan_snyk-jira-integration.yml

* Creates tickets with major versions only

Update Snyk Version

---

.github/workflows/audit-account.yml
.github/workflows/codeql-analysis.yml
.github/workflows/cypress-workflow.yml
.github/workflows/deploy.yml
.github/workflows/pullrequest-precommit-check.yml
.github/workflows/unittest-workflow.yml

The [code-climate action](https://github.com/paambaati/codeclimate-action) we use recently had an [upgrade to node 20](https://github.com/paambaati/codeclimate-action/issues/731). That was one of the lingering Node 16 actions across our apps so I'm taking this opportunity to bump actions across our apps.
CMDCT-3577
---
All actions pass and there are no warnings about Node 16 actions! 🎉 
No code changes
---

Bump action versions

---

services/ui-src/src/measures/2024/AABAD/data.ts

Remove "The" from the beginning of the performance measure description
CMDCT-3558
---
See deployed env: https://d1avepy1vtvixr.cloudfront.net)https://d1avepy1vtvixr.cloudfront.net/
Go to adult measures -> AAB-AD
Click the first option in the second and third questions.
Go to performance measures and verify the description text starts with "Percentage"
---

AAB-AD 2024 content change

---

services/ui-src/src/measures/2024/CCPAD/data.ts
services/ui-src/src/measures/2024/CCWAD/data.ts
services/ui-src/src/measures/2024/CCWCH/data.ts
services/ui-src/src/measures/2024/shared/CommonQuestions/PerformanceMeasure/index.tsx

This is a small styling change, from a bulleted list to a numbered list, within a few measures' descriptions. The capability to render numbered lists already existed, making this change trivially easy.
CMDCT-3562
---
* Go into each of these measures, filling out the first three questions
* Observe the numbered lists
n/a
---
- ~[ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary~
---
- ~[ ] These changes are significant enough to require an update to the SIA.~
- ~[ ] These changes are significant enough to require a penetration test.~

Switch to numbered list for description of CCP-AD, CCW-AD, CCW-CH

---

services/ui-src/src/measures/2024/rateLabelText.ts

CMDCT-3565
---
Confirm that the text "for mental illness" does not show up for FUM-AD, FUM-CH, FUM-HH (2024)
---
---
---

[QMR] FUM Measures - Content Change

---

services/ui-src/src/components/IETRate/index.test.tsx
services/ui-src/src/components/IETRate/index.tsx
services/ui-src/src/measures/2024/IETAD/data.ts
services/ui-src/src/measures/2024/IETHH/data.ts
services/ui-src/src/measures/2024/shared/CommonQuestions/PerformanceMeasure/index.tsx

Due to the react hook upgrade through snyk, the component (IETRate) doing calculations for IET-AD & IET-HH have been rendered unusable.
This is PR is more of a bandage to get the IETRate working again and meet snyk upgrade requirements. There will be a larger refactoring for how we call and use rate calculations in QMR as part of the efforts to upgrade this.
A mural flow to explain things
https://app.mural.co/t/coforma8350/m/coforma8350/1715009783840/c91064f51e3c869583eba7427d13767f6cb23960?sender=u66d9aeebc714573cd17a9651
Here are the original tickets pertaining to the creation of IETRate:
https://github.com/Enterprise-CMCS/macpro-mdct-qmr/pull/1803 
https://github.com/Enterprise-CMCS/macpro-mdct-qmr/pull/1823
CMDCT-3571
---
1. Login to a user with Health Home access (e.g. …

IETRate component fix for react hook upgrade

---

services/ui-src/src/measures/2024/CBPAD/data.ts
services/ui-src/src/measures/2024/CBPHH/data.ts
services/ui-src/src/measures/2024/CCSAD/data.ts
services/ui-src/src/measures/2024/DEVCH/data.ts
services/ui-src/src/measures/2024/HBDAD/data.ts
services/ui-src/src/measures/2024/HPCMIAD/data.ts
services/ui-src/src/measures/2024/IMACH/data.ts
services/ui-src/src/measures/2024/LSCCH/data.ts
services/ui-src/src/measures/2024/PPC2AD/data.ts
services/ui-src/src/measures/2024/PPC2CH/data.ts
services/ui-src/src/measures/2024/WCCCH/data.ts

CMDCT-3566
---
Confirm that for these measures (2024 only), we are seeing the following text change:
- DEV-CH
- IMA-CH
- LSC-CH
- PPC2-CH
- WCC-CH
- CBP-AD
- CCS-AD
- HBD-AD
- HPCMI-AD
- PPC2-AD
- CBP-HH
---
---
---

[QMR] Hybrid Measure changes

---

services/ui-src/src/measures/2024/HBDAD/index.test.tsx
services/ui-src/src/measures/2024/HBDAD/validation.ts

This PR adds a validation to the HBD-AD measure to ensure the Denominators for shared age groups are the same.
This validation existed in shared global and was simply added to existing validations and using the default error message.
CMDCT-3568
---
1. Sign in with a test user
2. Select any state
3. Click on `Adult Core Set Measures`
4. Click on measure `HBD-AD`
5. To avoid seeing unrelated validation errors, answer the following questions:
> - Are you reporting on this measure?
> - Status of Data Reported -- What is the status of the data being reported?
> - Measurement Specification
> - Data Source
> - Date Range
> - Definition of Population Included in the Measure
- Ensure you multi select `Denominator includes Medicaid population` AND `Denominator includes Medicare and Medicaid …

QMR-3568 Add validation for HBD-AD

---

services/ui-src/src/views/AdminHome/index.tsx
services/ui-src/src/views/StateHome/index.tsx

Fix banner styling
CMDCT-3601
---
Create a banner as an admin, confirm that banner matches the width of everything else in the state user home page and admin user home page.
---
---
---

[QMR]: Fix banner styling

---

services/ui-src/src/components/Banner/Banner.tsx

[Code scanning found a security issue](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/code-scanning/4), this is the fix for it. I didn't know what to do so I followed what someone who did know what to do, which was @ntsummers1 who fixed the same [issue for CARTS](https://github.com/Enterprise-CMCS/macpro-mdct-carts/pull/139626).
[DOM text reinterpreted as HTML](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/code-scanning/4)
---
_This is for checking to make sure the functionality hasn't changed_
1) Sign into QMR admin account ([adminuser@test.com](mailto:adminuser@test.com))
2) Create a banner with a link
3) After the banner is created, click the link
4) You should be redirected by the link
N/A
---
---
_If either of the following are true, notify the team's ISSO …

Fix DOM text reinterpreted as HTML

---

services/ui/serverless.yml

Add header to cloudfront function

---

services/ui-src/src/labels/2024/commonQuestionsLabel.tsx
services/ui-src/src/shared/commonQuestions/DataSource.tsx
services/ui-src/src/shared/types/TypeDataSource.tsx

A warning banner is now added when user selects ECDS (Electronic Clinical Data Systems (ECDS)) as a data source. The measure with ECDS as data source are: **BCS-AD, COL-AD, COL-HH, ADD-CH, APM-CH, CIS-CH, IMA-CH.**
There's a new key in `labels/{year}/commonQuestionsLabel.tsx`.
The Data Source component will check to see if there's a warning set for that data source and if there is, it will generate the alert message set in there. 
✅ product
CMDCT-3629
---
Deploy Link: https://d1wysw1og6vv2k.cloudfront.net/
2) Select any measure from the list of measures above.
3) Select Electronic Clinical Data Systems (ECDS) in the Data Source section and make sure the alert is there.
---
---
_If either of the following are true, notify the team's ISSO (Information System …

ECDS-Eligible measures - Warning Banner

---

services/ui-src/README.md
services/ui-src/package.json

Remove references to [react-scripts, which has been removed](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/pull/2237)
---
Nothing to test. We removed a command we didn't use.

Remove react scripts command

---

services/ui-src/src/measures/2024/PPC2AD/validation.ts
services/ui-src/src/measures/2024/PPC2CH/validation.ts

PPC2-AD & PPC-CH measures both needed the a validation check to make sure the values in the denominator are the same. If they are different, the warning banner below should pop up.
✅ product
CMDCT-3623
---
Deploy Link: https://d1cap8z2s8vq3s.cloudfront.net/
2) Select PPC2-AD
3) In the Measure Specification Section, select the first drop down
4) Scroll to Performance Measure and have the denominator the categories be different
5) Validate and you should see the error
6) Change the denominator values to be the same
7) Validate again and the error should be gone.
8) Repeat for PPC2-CH
N/A
---
---
--- …

PPC2-AD and PP2-CH Denom Validation 

---

services/app-api/libs/kafka-source-lib.js
services/database/scripts/syncKafka2024.ts

Make the same config changes we're making elsewhere and create a qmr/.ts script to do the same thing as the work in SEDS and CARTS.
Yes, no one consumes QMR topics to date, but they should be correct.
Adds a "lastSynced" field to items it wants to resend on the topic. This pattern is used in other apps, the field can generally be ignored and is just a simple way to trigger the database stream -> handler.
Companion PR to CMDCT-3674 in SEDS
---
Locally:
Run local, 
Run the command at the top of the script file from within the scripts folder: `npx tsx syncKafka2024.ts`
Verify lastSynced is added to the items touched in this year.
Locally you can modify a timestamp to be earlier if you want proof it won't touch older items
Deployed:
Get aws credentials
Run the command at the top of the script …

Unmarshall options and 2024 re-sync script

---

.env.tpl
run
src/run.ts

- Remove pragma comments when running `./run update-env` or `./run local --update-env`.
---
1. Run `./run local --update-dev` to update your local .env and start QMR
2. Verify there are no pragma comments in `.env`
3. Verify QMR works as normal
4. Run `./run update-env` and verify there are no pragma comments in `.env`

Remove pragma comments with update-env

---

services/ui-src/yarn.lock

Braces library needs to be up to date but snyk and yarn were having trouble resolving the new version in the lockfile. Removed the braces ref and re-ran yarn for that service.
N/A
---
Deployed app keeps on working.  https://d3lkzl0bxks972.cloudfront.net/
---
---
---

Resolve Braces Dependency - Close Snyk Finding

---

services/ui-src/yarn.lock

Per snyk - A nested dependency in cms design system needed to be updated. Let yarn regenerate the refs.
N/A
---
https://d2wyhonelf64ks.cloudfront.net/
Nothing has changed.
---
---
---

Snyk: update nested micromatch dependencies

---

services/ui-src/src/measures/2024/CPCCH/index.test.tsx
services/ui-src/src/measures/2024/CPCCH/index.tsx
services/ui-src/src/measures/2024/CPCCH/questions/DataSource.tsx
services/ui-src/src/measures/2024/CPCCH/questions/DefinitionOfPopulation.tsx
services/ui-src/src/measures/2024/CPCCH/questions/HowDidYouReport.tsx
services/ui-src/src/measures/2024/CPCCH/types.ts

Updating various questions for 2024 CPC-CH measure as noted in [this](https://jiraent.cms.gov/browse/CMDCT-3686) ticket
---
1. Navigate to a 2024 child core set (medicaid, CHIP or combined)
2. Click on the CPC-CH measure
3. Make sure that the questions match the changes requested in [CMDCT-3686](https://jiraent.cms.gov/browse/CMDCT-3686)
---
---
---

CMDCT-3686: updating questions for CPCCH 2024 measure

---

services/ui-src/src/measures/2024/CPCCH/index.test.tsx
services/ui-src/src/shared/commonQuestions/DataSouceInformationBanner/DataSourceInformationBanner.test.tsx
services/ui-src/src/shared/commonQuestions/DataSouceInformationBanner/DataSourceInformationBanner.tsx
services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.tsx

Currently in the Combined Rates Measure's page, the data source is not capturing text from the nested textbox in some of the nested data sources. 
and currently it shows it like this:
but it should look like this:
CMDCT-3767
---
Deploy Link: https://d21hn70r788qf7.cloudfront.net/
1) Sign into QMR, any split user i.e. ([stateuser1@test.com](mailto:stateuser1@test.com))
2) Select WCC-CH, this measure has a lot of nested Data Sources.
3) Fill out the Data Source section in the measure for both CHIP and Medicaid. 
- Especially the data sources with textboxes
4) Find the measure in the Combined Rates page and make sure the Data Source Info box is showing all the information that was selected and entered.
- If any data source textbox was selected but left empty, it should say Not Answered
N/A …

Combined Rates - Data Source Nested Textboxes Info

---

services/ui-src/src/measures/2024/CPCCH/index.test.tsx
services/ui-src/src/shared/commonQuestions/CombinedRateNDR/CombinedRateNDR.tsx
services/ui-src/src/theme.ts

Adding responsiveness to the Combined Rates N/D/R table.
Figma: https://www.figma.com/design/CaKupDWdVLgmnFZyhBSdGm/MDCT_QMR?node-id=2-3051&t=7mz43Bqacc32dq4c-4
Here's how the table looks like currently:
Here's how the table looks like in mobile mode:
CMDCT-3769
---
Deploy Link: https://d2xvckao8l272m.cloudfront.net/
1) Sign into QMR, i.e. [stateuser1@test.com](mailto:stateuser1@test.com)
2) Select Adult CHIP and pick any measure, i.e: AAB-AD
3) Fill out measure
- Make sure to select Administrative Data in the Data Source Section
- Fill out an N/D/R
4) Save or Validate the measure
5) Select Adult Medicaid and fill out the same measure as before. Repeat step 2 - 4
6) Go to the Combined Rates page and find the measure you've filled out
7) View it in mobile mode and make sure the table is …

Combined Rates - Mobile Combine Rates Table

---

services/app-api/handlers/rate/calculations/rateCalculation.ts
services/app-api/utils/constants/math.ts

Using .toFixed() for rounding seems to cause a weird issue were it only rounds half the time, so I'm switching to good ol' shift forward by two decimals, round and then shift back by two decimals. We've all seen and hate this, if anyone knows a better way, please let me know!
[This explains the issue well](https://stackoverflow.com/questions/77144696/seemingly-inconsistent-tofixed-behavior). Scroll to the **toFixed(1) example** example
CMDCT-3780
---
1) Sign into QMR, any separate user. i.e. [stateuser1@test.com](mailto:stateuser1@test.com)
2) Enter ADD-CH: Medicaid
3) Fill out Measure Specification to trigger the Performance Measure layer
4) For the Data Source: Select Administrative Data.
5) In the Performance Measure Section:
- Enter Numerator: 305 
- Enter Denominator: 10000
- The …

Inconsistent Rounding

---

services/ui-src/src/shared/commonQuestions/OptionalMeasureStrat/NDR/ndrCheckboxes.tsx
services/ui-src/src/shared/commonQuestions/OptionalMeasureStrat/context.ts
services/ui-src/src/shared/commonQuestions/OptionalMeasureStrat/omsUtil.tsx
services/ui-src/src/shared/types/TypeCategories.tsx
services/ui-src/src/shared/types/TypeQualifiers.tsx

Due to the label to data id migrations that were done recently for 2021 & 2022, the displaying and saving of the Other Performance Measures - Optional Measure Stratification data structure broke. It was looking for the data type to be an object for determining the structure but since it is all a LabelData object now, it did not propagate correctly.
This is the code that fixes it, the rest is just cleaning up types now that we don't pass in string[] for categories or qualifies.
```
const cleanedFieldName = isLegacyLabel()
? cleanString(description)
: `${DC.OPM_KEY}${cleanString(description)}`;
const key = isLegacyLabel()
? `${name}.rates.${cleanedFieldName}.OPM`
: `${name}.rates.OPM.${cleanedFieldName}`;
```
CMDCT-3839
---
Test this locally as you'll need to check local db
Run in the …

'21 and '22 OPM data is incorrect

---

services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.tsx

CMDCT-3795
---
- Confirm that the links are in the right order in the combined rates page (Medicaid then chip)
---
---
---

Combined Rates Page - Measure Link Order

---

services/ui-src/src/measures/2021/AIFHH/validation.ts
services/ui-src/src/measures/2021/IUHH/validation.ts
services/ui-src/src/measures/2021/globalValidations/ComplexValidations/ComplexNoNonZeroNumOrDenom/index.tsx
services/ui-src/src/measures/2022/AIFHH/validation.ts
services/ui-src/src/measures/2022/IUHH/validation.ts
services/ui-src/src/measures/2022/shared/globalValidations/ComplexValidations/ComplexNoNonZeroNumOrDenom/index.tsx
services/ui-src/src/measures/2023/AIFHH/validation.ts
services/ui-src/src/measures/2023/IUHH/validation.ts
services/ui-src/src/measures/2023/shared/globalValidations/ComplexValidations/ComplexNoNonZeroNumOrDenom/index.tsx
services/ui-src/src/measures/2024/AIFHH/validation.ts
services/ui-src/src/measures/2024/IUHH/validation.ts
services/ui-src/src/measures/2024/shared/globalValidations/ComplexValidations/ComplexNoNonZeroNumOrDenom/index.tsx

There is an issue with displaying the correct label for a complex validation, there was no path to get the description name. This is a left over issue from when QMR was using the label as an id but now that it has real ids, it needs to point to the actual label. 
It's the same changes repeated 4 times.
**Note**: I added legacy changes to all the files because I plan to merge them into one component in the future. So while its redundant and not serving a purpose now, it will make refactoring these components easier later.
CMDCT-3841
---
1) Sign into QMR using [stateuserWA@test.com](mailto:stateuserDC@test.com)
2) Add a Health Home CoreSet
3) Go into the AIF-HH measure
4) In the **Measure Specification** Section, select Other.
5) In the **Data Source** Section, check Other Data Source. This …

ComplexNoNonZeroNumOrDenom Validation - Incorrect Label

---

services/ui-src/src/measures/2024/shared/Qualifiers/data.ts

Content updates made to Qualifier portion of measures
- "title" capitalized
- "(Title XIX & XXI)" added to "Medicaid" titles
- lowecase "Separate"
- Column "Age 65 and older" removed from Adult Core Set Qualifiers: CHIP
- "Separate Chip" added to "Ages 21 to 64" column
- **For MCHIP states:**
-  **_Adult Core Set Qualifiers:_** "MEDICAID (TITLE XIX & XXI)" added to both age group columns
-  **_Child Core Set Qualifiers:_** "(TITLE XIX & XXI)" added to Medicaid column
CMDCT-3902
---
Upon selecting the Core Set Name from the Home Page with stateuser1@test.com
**The changes are in the following Core Set Qualifiers:**
1. Child Core Set Measures: Medicaid (Title XIX & XXI)
2. Child Core Set Measures: Separate CHIP
3. Adult Core Set Measures: Medicaid (Title XIX & XXI)
4. Adult Core Set …

QMR - Qualifier Questions Content Updates - Part 2

---

services/ui-src/src/views/CoreSet/index.tsx

This one has a history behind it and a few moving pieces.
Puzzle Pieces:
- HH Measures generate 5 placeholders
- These get turned into real measures as users enter optional measures, 5 max
- (Dev envs) Complete All Button marks all measures in the core set as complete, including placeholders
History:
- A past ticket was opened to fix the complete all button for dev. If used, the submit core set button would still be greyed out (CMDCT-3550 / [PR](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/pull/2233))
- By using the total measure count (incidentally including placeholders) the numbers now match, and by using the complete all button, you can proceed!
- This breaks the normal count, when users manually submit measures, they will have 13 complete, and 5 incomplete placeholders :( …

[CMDCT-3922] Submit HH Button Greyed Out

---

services/ui-src/src/measures/2024/COLAD/index.test.tsx
services/ui-src/src/measures/2024/COLAD/validation.ts
services/ui-src/src/measures/2024/COLHH/validation.ts

COL-AD and COL-HH have slightly different age ranges and the validation flag is triggering for the Age 51-65 rate, but it should be connected to the 66-75 rate. 
Please link the validation to the 66 to 75 rate (when the 66 to 75 rate is blank but the user selected “Individuals Dually Eligible for Medicare and Medicaid”) and update it.
**AC:**  For Measures COL-AD and COL-HH, correct the validation to read the correct age range.  
"Individuals Dually Eligible for Medicare and Medicaid" is selected in the "Definition of Denominator" question but you are missing performance measure data for Ages 66 to 75
CMDCT-3919
---
---
---
--- …

CMDCT-3919 - COL-AD and COL-HH Validation Update 

---

services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.tsx

CMDCT-3921
---
View Combined Rates > choose a measure > make sure combined rates text shows up and the link works
---
---
---

Combined Rates Page Language

---

services/ui-src/src/views/CoreSet/index.tsx

The Child banner and HH banner needs to have a link added to the text.
HH is linked to this pdf
https://www.medicaid.gov/sites/default/files/2024-03/smd24002.pdf
Child is linked to this pdf
https://www.medicaid.gov/sites/default/files/2023-12/sho23005_1.pdf
CMDCT-3920
---
Deploy Link: https://d1qqmduypn9ig7.cloudfront.net/
1) Sign into QMR, [stateuserWA@test.com](mailto:stateuserDC@test.com).
2) Add a Health Home CoreSet.
3) Go to the Health Home CoreSet measure list and see that there's a link and the link opens in a new tab.
4) Do the same for Child CoreSet measure list and see that there's a link and the link opens in a new tab.
---
---
--- …

Child and HH Banner Link

---

services/ui-src/src/measures/2024/shared/Qualifiers/data.ts

Content updates to MCHIP states only
CMDCT-3940
---
Deploy Link: N/A yet - erroring out
1. SIgn into QMR, with internaluser@test.com, 
2. Select an MCHIP state
a. MCHIP states:  Alaska (AK), American Samoa (AS), DC, Guam (GU), Hawaii (HI), New Hampshire (NH), New Mexico (NM), North Carolina (NC), North Dakota (ND), Northern Mariana Islands (MP), Ohio (OH), Puerto Rico (PR), South Carolina (SC), US Virgin Islands (VI), Vermont (VT), Wyoming (WY)
3. Select `Child Core Set Measures: Medicaid (Title XIX & XXI)` 
4. Click on `Child Core Set Questions: Medicaid (Title XIX & XXI)` at the top of the Measures list page
5. Confirm changes
6. Repeat **steps 3-5** for **Adult Core Set Measures: Medicaid (Title XIX & XXI)**
---
---

[QMR] Qualifier Questions Content Updates (part 3) 

---

services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.tsx

CMDCT-3939
---
1. Go to combined rates page and make sure there's a header (About the Combined Medicaid and CHIP Rate) and line breaks
---
---
---

[QMR] Combined Rates Content Formating

---

services/ui-src/src/views/CoreSet/index.tsx

CMDCT-3941
---
Confirm banner heading across all core sets now says "Mandatory Reporting" instead of "Mandatory Measure Instructions"
---
---
---

Banner Content Changes

---

services/app-api/handlers/rate/dataSourceAnalysis.test.ts
services/app-api/handlers/rate/rateCalculations.test.ts
services/app-api/handlers/rate/rateNDRCalculations.test.ts
services/app-api/handlers/rate/rateValueCalculations.test.ts
services/ui-src/src/shared/commonQuestions/AdditionalCombinedValues/AdditionalCombinedValues.tsx

This is what I get for bypassing merge requirements without checking that all is good
---
---
---
---

Prettier Fix

---

services/app-api/handlers/rate/rateNDRCalculations.ts
services/ui-src/src/shared/commonQuestions/DataSouceInformationBanner/DataSourceInformationBanner.tsx
services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.tsx

co-author with @benmartin-coforma 
There are two fixes in this PR:
1. Combined rates calculating even when value is invalid
@davidkoger pointed out that we forgot to check for numerator < denominator before doing the combined rates calculation so this PR fixes that.
2. The data source banner should be display by default on the combined rates even when no data has been entered. 
---
1) Sign into QMR, any separate user i.e.[stateuser1@test.com](mailto:stateuser1@test.com)
2) Before filling out any measure, go to the combined rates page for APM-CH. It should look like the image below:
3) Fill out APM-CH (or any measure that has a combined rate): 
- For the data source select **Administrative Data**
- In the N/D/R, set the values of **numerator > denominator**
4) Go to the combined rates page …

Combined Rate - Small Fixes

---

services/app-api/package.json
services/app-api/yarn.lock
services/database/package.json
services/database/yarn.lock
services/ui-auth/package.json
services/ui-auth/yarn.lock
services/ui-src/package.json
services/ui-src/yarn.lock
services/uploads/package.json
services/uploads/yarn.lock

Addressing snyk PR:
https://github.com/Enterprise-CMCS/macpro-mdct-qmr/pull/2456

update aws-sdk dependencies

---

services/ui-src/src/components/LocalLogins/index.tsx

BEFORE:
AFTER:
CMDCT-funsies
---
Run and open login page!
I did a rough eyeball/code match of MCR styling for the login pages. Open to changes 🤷 
---
- ~[ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary~

add qmr heading to login page

---

.env.tpl
serverless-compose.yml
services/app-api/handlers/rate/migrateExistingCombinedRates.ts
services/app-api/serverless.yml
services/app-api/storage/table.test.ts
services/app-api/storage/table.ts
services/database/scripts/transformRateTable.ts
services/database/serverless.yml
services/uploads/serverless.yml
services/uploads/src/dynamoSync/handler.js
yarn.lock

rekeying rate table to match the primary key convention of the new coreset and measure tables. We didn't really need to do this but it's nice to be on the same page as the other db tables
CMDCT-3069, CMDCT-4019, CMDCT-4029
---
General smoke testing involving combined rates

CMDCT-4029: rekey rates table

---

services/uploads/serverless.yml
services/uploads/src/dynamoSync/handler.js

The current mathematica integration runs every 30 minutes across all data. It takes that data and stores it in an s3 bucket forever. This PR does two things:
1. Sets up a high and low frequency mode for the lambda. This should make it obvious what to switch when higher rates are needed for the QMR testing period (June-Sept), and provides a single value to flip. I debated allowing any cron but it felt less obvious what was going on.
2. Adds a cleanup process to the lambda. After running, the lambda will check the bucket files and remove any older than 1 week. We can shift this if we want. This only will chunk 1000 max for deletion each run, but over time that should vastly outpace the new file rate.
---
I can walk through testing with anyone who wants to try it.
- Add a file with a …

[CMDCT-2535] S3 Integration Proposal

---

services/app-api/libs/updateCoreProgress.ts

Just a little syntactical cleanup!
---
If the unit tests pass, we're all set!
---
- ~[ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary~
- ~[ ] I have performed a self-review of my code~
---
- ~[ ] Design: This work has been reviewed and approved by design, if necessary~
- ~[ ] Product: This work has been reviewed and approved by product owner, if necessary~
- ~[ ] These changes are significant enough to require an update to the SIA.~
- ~[ ] These changes are significant enough to require a penetration test.~

Remove unneeded exclamation marks for coreSet.progress

---

services/ui-src/index.html
services/ui-src/src/components/DeleteWrapper/index.tsx
services/ui-src/src/index.scss
services/ui-src/src/index.tsx
services/ui-src/src/theme.ts

This PR will fix the UI issues that popped up when we upgraded to both react and chakra.
Examples: 
**1)** Missing background color for the banner
**2)** Different Colors
**3)** Too much margins
**4)** Off center icons
CMDCT-4178
---
Test this locally as this won't make a new deploy link for these changes. it uses the parent branch deploy link.
**Note:** you may need to delete the **node_modules** folder in `services/ui-src` and do a `yarn install` if you don't see any of the changes.
1) Sign into QMR, any user.
2) Click around to make sure nothing looks weird.
---
---
--- …

Reinstate UI look/feel since upgrade to react v18 and chakra v2

---

services/ui-src/src/components/DeleteWrapper/index.tsx

A state user pointed out during a round of user testing that it would be nice to have a delete button in the OMS section when you're adding additional categories & sub-categories. In a surprising twist, there was a always a delete button, it was just off the page.
Did I cause this from my refactoring or was it always just slightly out of everyone's reach; we'll never know.
(it was me)
---
Deploy Link: https://d38899hkqraip2.cloudfront.net/
2) Select AAB-CH
3) In the **Measure Specification** section, pick the first radio button. This will enable the **Performance Measure** section
4) Scroll down to the **Performance Measure** section, fill out the N/D/R section. This will enable the OMS section
5) In the OMS section, check any category and there will be an …

OMS Additional Category Delete

---

services/ui-src/src/measures/2025/CBPAD/index.tsx
services/ui-src/src/measures/2025/CBPHH/index.tsx
services/ui-src/src/measures/2025/CCSAD/index.tsx
services/ui-src/src/measures/2025/CISCH/index.tsx
services/ui-src/src/measures/2025/DEVCH/index.tsx
services/ui-src/src/measures/2025/HBDAD/index.tsx
services/ui-src/src/measures/2025/HPCMIAD/index.tsx
services/ui-src/src/measures/2025/IMACH/index.tsx
services/ui-src/src/measures/2025/LSCCH/index.tsx
services/ui-src/src/measures/2025/PPC2AD/index.tsx
services/ui-src/src/measures/2025/PPC2CH/index.tsx
services/ui-src/src/measures/2025/WCCCH/index.tsx

Updates were made to these hybrid measures: CBP-AD, CBP-HH, CCS-AD, CIS-CH, DEV-CH, HBD-AD, HPCMI-AD, IMA-CH, LSC-CH, PPC2-AD, PPC2-CH, WCC-CH.
The question: 
_If you are reporting as a hybrid measure, provide the measure eligible population and sample size._ 
will only display now if the user selects **Hybrid (Administrative and Medical Records Data)** in the Data Source section.
https://github.com/user-attachments/assets/38cc1640-8d7d-4b95-8408-c84110d4e4a6
CMDCT-4202
---
Deploy Link: https://d2njed52er96c9.cloudfront.net/
1) Sign into QMR, any state user (i.e. [stateuser1@test.com](mailto:stateuser1@test.com))
2) Go to reporting year 2025, select CBP-AD or any of the measures listed above
3) Scroll to the **Definition of Population Included in the Measure** section
4) Check to see that …

All Hybrid-Possible Measures - "If you are reporting..."

---

services/ui/serverless.yml
services/uploads/serverless.yml

Makes sure that all s3 buckets have no public access and are versionsed
CMDCT-4303
---
NA
---
---

CMDCT-4303 - adds correct s3 config

---

services/app-api/handlers/rate/migratePqiMiscalculations.ts

Add some helpful comments to the PQI combined rate migration script

---

.github/workflows/scan_security-hub-jira-integration.yml

Old ubuntu being retired. Let's get the latest version!
CMDCT-4333
---
Run the Github Action once it's merged like so:
NA
---
---
---

CMDCT-4333 upgrading ubuntu for security hub jira integration

---

run
services/ui/serverless.yml
src/run.ts
src/slsV4BucketPolicies.ts

S3 Bucket Fixes from Serverless V4 and making s3 not a website because CloudFront is what serves the website
CMDCT-4311
---
Verify the deployed website loads https://dvyrs9p5ilot6.cloudfront.net/
---
---
---

S3 Bucket Fixes from Serverless V4 and making s3 not a website because CloudFront is what serves the website

---

services/topics/handlers/createTopics.js
services/topics/handlers/deleteTopics.js
services/topics/handlers/listTopics.js
services/topics/libs/topics-lib.js

Fix delete topics after serverless v4 upgrade
CMDCT-4339
---
---
---
---

Fix delete topics after serverless v4 upgrade

---

services/app-api/handlers/dynamoUtils/measureList.ts
services/ui-src/src/measures/2025/GSDAD/data.ts
services/ui-src/src/measures/2025/GSDAD/validation.ts
services/ui-src/src/measures/2025/index.tsx
services/ui-src/src/measures/2025/measureTemplateData.tsx
services/ui-src/src/measures/2025/rateLabelText.ts
services/ui-src/src/measures/measureDescriptions.ts
tests/cypress/support/constants.ts

Guess which measure a shiny new name, that's right HBD-AD is now GSD-AD!
CMDCT-4237
---
Deploy Link: https://d2oxpmgzy7mafd.cloudfront.net/
---
---
---

Rename HBD-AD to GSD-AD

---

services/app-api/handlers/rate/dataSourceAnalysis.test.ts
services/app-api/handlers/rate/dataSourceAnalysis.ts
services/app-api/handlers/rate/rateNDRCalculations.ts
services/app-api/types.ts
services/ui-src/src/labels/2025/commonQuestionsLabel.tsx
services/ui-src/src/shared/commonQuestions/DataSouceInformationBanner/DataSourceInformationBanner.test.tsx
services/ui-src/src/shared/commonQuestions/DataSouceInformationBanner/DataSourceInformationBanner.tsx

There are two changes to the combined rates calculation this year.
1. Rates reported with an ECDS data source _are_ eligible for combination. ECDS uses the entire measure-eligible population, so it uses the same calculation as Administrative- or EHR-sourced data. No weighting is required, as it would be for Hybrid- or CMRR-sourced data.
2. The new EDV-AD rate introduced this year is displayed as "per 100,000", just like the PQI rates. It does not use the standard percent as most rates. This will need to be handled within the measure, but it also needs to be handled here, when combining rates.
The fact that ECDS data _was_ unusable, but is no longer, required a bit of tweaking to the DataSourceInformationBanner. We don't want to say "This measure used ECDS, so we couldn't calculate it" (as …

Combined Rates changes for 2025

---

services/ui-src/src/dataConstants.ts
services/ui-src/src/measures/2025/ADDCH/data.ts
services/ui-src/src/measures/2025/APMCH/data.ts
services/ui-src/src/measures/2025/BCSAD/data.ts
services/ui-src/src/measures/2025/CCSAD/data.ts
services/ui-src/src/measures/2025/COLAD/data.ts
services/ui-src/src/measures/2025/COLHH/data.ts
services/ui-src/src/shared/commonQuestions/DataSouceInformationBanner/DataSourceInformationBanner.test.tsx
services/ui-src/src/shared/commonQuestions/DataSouceInformationBanner/DataSourceInformationBanner.tsx
services/ui-src/src/shared/types/TypeDataSource.tsx

New Data Sources have been added for a couple of measures:
- CCS-AD 
- COL-AD 
- BCS-AD 
- ADD-CH 
- APM-CH 
- COL-HH 
CMDCT-4402
---
Deploy Link: https://d3er1x5q0xlnx0.cloudfront.net/
2) Stay in Reporting Year 2025 
3) Go to ADD-CH measure
4) Scroll down to the **Data Source** section
5) Check that the data source matches what it looks like in the screenshot above.
---
---
---

ECDS Data Source Updates

---

services/app-api/handlers/banners/create.ts
services/app-api/utils/sanitize/sanitize.test.ts
services/app-api/utils/sanitize/sanitize.ts
services/ui-src/src/components/Banner/Banner.tsx
services/ui-src/src/utils/parser.tsx

The BO's want to be able to add bullet points to text.
---
Deploy Link:https://d3luq4el4al37a.cloudfront.net/
1) Sign into admin user
2) Go the the banner editor
3) Enter this in the Description text:
`<ul><li>bullet 1</li><li>bullet 2</li></ul>`
4) Start Date: 1/1/2025
5) End Date: 12/1/2025
6) Create the banner and you should see bullets
---
---
---

Banner With HTML

---

services/ui-src/src/measures/2025/BCSAD/data.ts

This PR covers content updates to BCS-AD (2025):
-  Update measure description to:
> Percentage of beneficiaries ages 50 to 74 who were recommended for routine breast cancer screening and had a mammogram to screen for breast cancer.
- Remove "Administrative" from Data Source
CMDCT-4397
---
**Deploy Link:** https://d2cfoohuehmlx4.cloudfront.net/
1. Select **BCS-AD** from 2025 coreset
1. Adult Core Set Measures: "Separate CHIP or Medicaid (Title XIX & XXI)"
2. Answer - `National Committee for Quality Assurance (NCQA)/Healthcare Effectiveness Data and Information Set (HEDIS)` for following question: 
> Measurement Specification
> If your state substantially varied from the measure specifications (including different methodology, timeframe, or reported age groups), please report your data …

[QMR] BCS-AD Update

---

services/app-api/utils/sanitize/sanitize.ts
services/ui-src/src/measures/2025/PPC2AD/data.ts

New Data Source options added to PPC2-AD
Also, changes in sanitize.ts. Not relevant to this ticket, this is related to a quick fix we did for the QMR BO's last friday and I wanted to expand on it a tiny bit before I forget.
CMDCT-4401
---
Deploy Link: https://d3oy4hsn3phv52.cloudfront.net/
2) Stay on reporting year 2025
3) Go to PPC2-AD
4) Scroll to the **Data Source** section
5) Check that data source matches the image above
---
---
---

PPC2-AD Update

---

services/app-api/types.ts
services/ui-src/src/dataConstants.ts
services/ui-src/src/measures/2025/OUDAD/data.ts
services/ui-src/src/shared/commonQuestions/MeasurementSpecification.test.tsx
services/ui-src/src/shared/commonQuestions/MeasurementSpecification.tsx

OUD-AD is under a brand new measure specification "_Substance Abuse and Mental Health Services Administration (SAMHSA)_"
And has an updated performance measure text
CMDCT-4400
---
Deploy Link: https://d33u2ii8co94dv.cloudfront.net/
2) Stay on reporting year 2025
3) Go to OUD-AD
4) Go to the **Measure Specification** section. Select  _Substance Abuse and Mental Health Services Administration (SAMHSA)_ . 
5) Scroll to the **Performance Measure** section. Check text matches the changes listed in the jira ticket
---
---
--- …

OUD-AD Update

---

services/ui-src/src/measures/2025/ADDCH/data.ts
services/ui-src/src/measures/2025/APMCH/data.ts

This PR covers tiny updates to ADD-CH & APM
For both: 
- **Data Source**
- Remove Administrative Data 
- **Performance Measure**
- Replace "Percentage" --> "The percentage"
For ADD-CH
- **Performance Measure**
- Update "10-month period" --> "300-day (10-month) period"
CMDCT-4405
CMDCT-4406
---
**Deploy Link:** https://d1rova2rjjvmx8.cloudfront.net/
1. Login with any state user
2. Select any Child Core Set for 2025
3. Select ADD-CH then APM-CH to confirm changes
4. Confirm content changes match Jira tickets (in green)
---

[QMR] ADD-CH & APM-CH Updates

---

services/ui-src/src/measures/2025/CCSAD/data.ts
services/ui-src/src/measures/2025/COLAD/data.ts
services/ui-src/src/measures/2025/rateLabelText.ts

This PR covers content updates to CCS-AD & COL-AD (2025):
- Add data collection method: ECDS (this one was already previously done)
- <img width="400" alt="data-source-with-ECDS" src="https://github.com/user-attachments/assets/2d12ac7c-1131-4fc2-a177-4701954f15eb">
- Performance Measure Question
- women --> beneficiaries
- screened --> recommended for routine ....
- Performance Measure Question List Items
-  women --> beneficiaries
- addded to each list item --> were recommended.... 
- Remove "Administrative" from Data Source
CMDCT-4398 CCS-AD
CMDCT-4399 COL-AD
---
**Deploy Link:** https://djptwoclxmbo2.cloudfront.net/
1. Login to QMR with state user
2. Select **CCS-AD** from 2025 coreset
1. Adult Core Set Measures: "Separate CHIP or Medicaid (Title XIX & XXI)"
3. Answer - `National …

[QMR] CCS-AD & COL-AD Updates

---

services/ui-src/src/measures/2025/MSCAD/validation.ts

In MSC-AD when the user does not select an answer for "**Did you collect this measure?**" but still answers "**Did you submit your CAHPS survey data to the AHRQ CAHPS Database during the June 2025 submission period?**", this validation needs to popup.
The error
CMDCT-4490
---
Deploy Link: https://d18ao043xre5uc.cloudfront.net/
2) In reporting year 2025, got to MSC-AD
3) Fill out the top two questions like this:
4) Scroll down and click validate
5) You should see this error
---
---
---

MSC-AD Validation Bug

---

services/ui-src/src/libs/spaLib.ts

New SPA ids have dropped. What are spa ids? It's the title and id a health home coreset is associated with.
CMDCT-4613
---
Deploy Link: https://d44f0a086lxm6.cloudfront.net/
Note: To truly see all of the changes, you need to log into ~11 users. It should be fine if you check like 2 or 3 of them and make sure that the .ts file has been updated correctly.
1) Sign into a [stateuserID@test.com](mailto:stateuserID@test.com), or any of the states listed in the SPA changes.
2) These all should have the ability to add a Health Home Core Set. Click the [Add Health Home Core Set] button
3) You would be taken to a new page with a drop down. Check that the dropdown value matches the value in the jira ticket.
---
---
_If either of the following are true, notify the team's ISSO (Information System …

New SPA Updates for States

---

services/ui-src/src/measures/2025/PRSAD/data.ts
services/ui-src/src/measures/2025/PRSAD/validation.ts
services/ui-src/src/measures/2025/index.tsx
services/ui-src/src/measures/2025/measureTemplateData.tsx
services/ui-src/src/measures/2025/rateLabelText.ts

This PR covers adding PRS-AD as a new measure
CMDCT-4436
---
**Deploy Link:** https://d32ar59irqa0nj.cloudfront.net/
1. Sign into QMR, any state user
2. In FY 2025, go to the Adult Core Set
3. Select PRS-AD
5. Fill out the measure
6. Make sure that the requirements, performance measure text is and rate labels match the jira ticket
---

2025 New Measure - PRS-AD Details

---

services/ui-src/src/measures/2025/PRSCH/data.ts
services/ui-src/src/measures/2025/PRSCH/validation.ts
services/ui-src/src/measures/2025/index.tsx
services/ui-src/src/measures/2025/measureTemplateData.tsx
services/ui-src/src/measures/2025/rateLabelText.ts

-- This is a re-do -- as previous [PR](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/pull/2612) was failing via AWS stack
This PR covers adding PRS-CH as a new measure.
CMDCT-4456
---
**Deploy Link:** 
1. Sign into QMR, any state user
2. In FY 2025, go to the Child Core Set
3. Select PRS-CH
5. Fill out the measure
6. Make sure that the requirements, performance measure text is and rate labels match the jira ticket
---

[Retry] 2025 New Measure - PRS-CH Details

---

deployment/deployment-config.ts

CMDCT-4363 patch to deploy for production

---

deployment/deployment-config.ts
deployment/stacks/uploads.ts
services/app-api/handlers/rate/rateNDRCalculations.test.ts
services/app-api/handlers/rate/rateNDRCalculations.ts
services/ui-src/src/labels/2025/commonQuestionsLabel.tsx
services/ui-src/src/measures/2025/LRCDAD/index.tsx
services/ui-src/src/measures/2025/PDSAD/data.ts
services/ui-src/src/measures/2025/PDSAD/validation.ts
services/ui-src/src/measures/2025/index.tsx
services/ui-src/src/measures/2025/measureTemplateData.tsx
services/ui-src/src/measures/2025/rateLabelText.ts
services/ui-src/src/shared/commonQuestions/DateRange.tsx
services/ui-src/src/shared/commonQuestions/DefinitionsOfPopulation.tsx
services/ui-src/src/shared/commonQuestions/MeasurementSpecification.tsx
services/ui-src/src/shared/types/GlobalTypes.tsx
services/ui-src/src/shared/types/MeasureTemplate.tsx
services/ui-src/src/shared/types/TypeMeasureSpecification.tsx
services/ui-src/src/shared/types/index.tsx

---
- New Measure: PDS-AD  (CMDCT-4435)
- Patch for CDK isDev (CMDCT-4363)
- LRCD-AD Details (CMDCT-4452)
- Combined Rates Update for 0 (CMDCT-4460)
- Measure Steward Question Update (2025) (CMDCT-4481) (CMDCT-4482) (CMDCT-4483) (CMDCT-4484) (CMDCT-4485) (CMDCT-4486) (CMDCT-4487) (CMDCT-4488) (CMDCT-4489)
- Mathematica Access Fix (CMDCT-4646)

Test -> Val

---

services/ui-src/src/measures/2025/CPAAD/index.tsx
services/ui-src/src/shared/commonQuestions/DefinitionsOfPopulation.tsx

Update the language of the definition of denominator question in the Adult separate CHIP report ONLY
CMDCT-4671
---
https://d2993uo6a2ax2z.cloudfront.net/
Go to a measure in Adult Core Separate Chip, and scroll down to Definition of Populations section. 
confirm that the text matches the asked changes: https://jiraent.cms.gov/browse/CMDCT-4671
---
---
---

2025 - Update the Denominator Question

---

.github/workflows/deploy.yml
.github/workflows/destroy.yml
.github/workflows/update-code-json.yml
code.json

ShareIT compliance is required
CMDCT-4692
---
See that this worked:
https://github.com/Enterprise-CMCS/macpro-mdct-qmr/actions/runs/15303550341
Also feel free to check out code.json in the project root now.
NA
---
---
---

CMDCT-4692 ShareIT compliance

---

services/ui-src/src/measures/2025/GSDAD/data.ts
services/ui-src/src/measures/2025/HPCMIAD/data.ts
services/ui-src/src/measures/2025/rateLabelText.ts
services/ui-src/src/measures/measureDescriptions.ts

**Text updates for GSD-AD** 
Performance Measure
_Percentage of beneficiaries ages 18 to 75 with diabetes (type 1 and type 2) whose most recent glycemic status ( hemoglobin A1c [HbA1c] or glucose management indicator [GMI]) was at the following levels during the measurement year:_
- _Glycemic Status (<8.0%)_
- _Glycemic Status (>9.0%)_
Updated Rate Text Labels
- _Glycemic Status (< 8.0%)_
- _Glycemic Status (>9.0%)_
**Text Updates for HPCMI-AD**
New Title: _HPCMI-AD: Diabetes Care for People with Serious Mental Illness: Glycemic Status (>9.0%)_
Performance Measure
_Percentage of beneficiaries ages 18 to 75 with a serious mental illness and diabetes (type 1 and type 2) who had a glycemic status assessment result of (>9.0%)._
CMDCT-4693
CMDCT-4694
---
Deploy Link: …

[CMDCT-4693, CMDCT-4694] GSD-AD & HPCMI-AD Update

---

services/ui-src/src/measures/2025/rateLabelText.ts

Add Combination 3,7,10 to the CIS-CH Performance Measure section in 2025 
CMDCT-4685
---
cloudfront link: https://d1lf7o81qk9uqc.cloudfront.net/
1. Go to CIS-CH (Medicaid (Title XIX & XXI))
2. Click **Yes** to reporting on this measure and **Yes** to the Measurement Specification question
3. Confirm that you see Combination 3,7, and 10 in the N/D/R section
4. Fill out entire N/D/R section to trigger OMS section - confirm that you can see Combination 7 and 10 added as sub options
---
---
---

UAT Defect - CIS-CH Combination Rates

---

services/ui-src/src/components/Footer/index.tsx

Removing weird spacing from email
---
---
---
---

Remove space from email

---

src/run.ts

add verbose to deploy command.  This is temporary to help us get more information when a deploy fails.
CMDCT-
---
---
---
---

add verbose to deploy command

---

services/ui-src/src/components/Inputs/RadioButton/index.tsx
services/ui-src/src/shared/commonQuestions/MeasureStratification/index.tsx
services/ui-src/src/shared/commonQuestions/MeasureStratification/omsNodeBuilder.tsx
services/ui-src/src/shared/commonQuestions/OptionalMeasureStrat/additionalCategory.tsx
services/ui-src/src/shared/globalValidations/omsValidator/index.ts

This PR handles re-attaching validation back to the measure stratification and also cleaning it up to validate correctly for accordions vs checkboxes.
This also adds in the additional notes textbox.
https://github.com/user-attachments/assets/30053a85-fa65-4d55-abb2-7c2bd9690029
Note:
- I took out initializing a single Add Category as it causes issues with the current validation set up. Since the user can still add one from a button instead, it's not a blocker to let the BOs test functionality. I'm going to need to noodle on this a little more later on.
- When you save, the Accordion closes itself. I'm not sure what's causing that atm so it's also something I plan to noodle on some more.
CMDCT-4774
---
Deploy Link: https://d2pm7h03o81bpm.cloudfront.net/
2) …

[CMDCT-4774] New Stratification - Reattach Validation

---

services/ui-src/src/components/Inputs/RadioButton/index.tsx
services/ui-src/src/shared/commonQuestions/MeasureStratification/omsNodeBuilder.tsx

A follow up to this [PR #1](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/pull/2663), and then when i rewrote it slightly in this [PR #2](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/pull/2667).
The issue with the clear button is that it functions differently before you have saved values and after you have saved values. PR #1 addressed clearing before you have any data saved and PR #2 addressed clearing after you have data saved but neither took into account to do both.
This PR combines them both. 
My running theory is that if you try to clear before saving anything, it means there's no data structure to actually clear so the RadioButton is having a hard time rendering what doesn't exist. This causes it to leave remnants of in the radio selection like this:
Setting it to a …

[Bug] OMS Not Clearing

---

services/ui-src/src/measures/2025/SSHH/data.ts

For SS-HH, which is the Health Home measures a user can create, we want to add in the ECDS options.
sidenote: i made a mistake in the naming the branch so ignore the cmdct # on it.
CMDCT-4803
---
Deploy Link: https://d3j6uej15nhyhh.cloudfront.net/
1) Sign into QMR, any user that has Health Homes (i.e. [stateuserWA@test.com](mailto:stateuserDC@test.com))
2) Add a Health Home Core Set
3) Enter the Health Home measure table and scroll down until you see [**Add State Specific Measure**] button
4) Add a new state specific measure, name is anything you want.
5) Enter the measure you just created and scroll to **Data Source**
6) See that the selection looks like this:
---
---
---
_convert to a …

 [CMDCT-4803] Add ECDS to data source options to SS-HH

---

deployment/constructs/lambda-dynamo-event.ts
deployment/constructs/lambda.ts
deployment/stacks/ui-auth.ts

add forceDockerBundling to esbuild bundling
CMDCT-
---
---
---
---

add forceDockerBundling to esbuild config

---

services/ui-src/src/measures/2025/CISCH/validation.ts
services/ui-src/src/measures/2025/GSDAD/validation.ts
services/ui-src/src/measures/2025/PPC2AD/validation.ts
services/ui-src/src/measures/2025/PPC2CH/validation.ts

- Added missing validation to CIS-CH, PPC2-CH, PPC2-AD, and GSD-AD
CMDCT-4877
---
- Login: https://d3nnako8p7f2vz.cloudfront.net/
- In reporting year 2025, select measure CIS-CH
- In the Measure Specification section, select the first radio button, this will enable the Performance Measure section
- Scroll down to the Performance Measure section and fill out the N/D/R sets. This will enable the Measure Stratification section
- Go to the Measure Stratification section and in the radio button section select either 1997 or 2024
- Fill out one of the optional num/denom under race/Amarican/Alaska
- Click validate, verify that you get an error if all denominators are not the same.
- Verify the error goes away if all denominators are the same
- Repeat steps for measures PPC2-CH, PPC2-AD, and …

CMDCT-4877 - added missing validations

---

services/ui-src/src/measures/2025/CCWAD/validation.ts

CMDCT-4878
---
- Login: https://d1ehnglulib5pw.cloudfront.net/
- In reporting year 2025, select measure CCW-AD
- In the Measure Specification section, select the first radio button, this will enable the Performance Measure section
- Scroll down to the Performance Measure section and fill out the N/D/R sets. This will enable the Measure Stratification section
- Go to the Measure Stratification section and in the radio button section select either 1997 or 2024
- Fill out one of the optional num/denom under race/Amarican/Alaska so that the denominators are the same, but LARC rate is higher than the Most Effective rate
- Verify that an error shows when you click validate
---
---
---
_convert …

CMDCT-4878 - add missing CCW-AD validation

---

services/ui-src/src/labels/2024/commonQuestionsLabel.tsx
services/ui-src/src/labels/2025/commonQuestionsLabel.tsx
services/ui-src/src/measures/2024/CPAAD/index.tsx
services/ui-src/src/measures/2025/CPAAD/index.tsx
services/ui-src/src/measures/2025/CPCCH/questions/DefinitionOfPopulation.tsx
services/ui-src/src/shared/commonQuestions/DefinitionsOfPopulation.tsx

This PR is for changing any instance of `Medicaid Expansion CHIP (Title XXI)` to `Title XXI-funded Medicaid Expansion CHIP` in the Definition of Population section's text.
**Note:**
- I moved the options text into the `labels/{year}/commonQuestionsLabel.tsx` so that we can update the labels for the current year but also keep the text for the previous years.
CMDCT-4933
---
Deploy Link: https://d3k8spkbrlwdb6.cloudfront.net/
1) Sign into QMR, any state user (i.e. [stateuser1@test.com](mailto:stateuser1@test.com))
2) Go into AAB-CH measure and scroll down to the **Definition of Population Included in the Measure** section,
3) Check that the text has been uploaded to this.
4) Go to AAB-AD measure and scroll down to the **Definition of Population Included in the Measure** section,
5) Check …

[CMDCT-4933] Definition of Population Text Change

---

services/ui-src/src/labels/2025/qualifierFormsData.tsx
services/ui-src/src/shared/Qualifiers/Common/generalAge.tsx
services/ui-src/src/shared/Qualifiers/index.tsx
services/ui-src/src/shared/types/TypeQualifierForm.tsx

The qualifier's has more content changes.
**Child Core Set Qualifiers: Medicaid**
**Child Core Set Qualifiers: CHIP**
**Adult Core Set Qualifiers: Medicaid**
**Adult Core Set Qualifiers: CHIP**
CMDCT-4934
---
Deploy Link: https://d2stmanqzz4iad.cloudfront.net/
1) Sign into QMR, any user with Health Home Core Set (i.e.[stateuserWA@test.com](mailto:stateuserDC@test.com))
2) Go to the qualifier page of Child - Medicaid core set
3) Review that the text matches what is listed in the jira ticket CMDCT-4934
4) Do the same for the rest of the Core Sets
---
---
--- …

[CMDCT-4934] Qualifier Question Text Changes

---

services/ui-src/src/utils/constants.ts

CMDCT-5019
---
- Deploy link: https://dze6sheifofmw.cloudfront.net/
- Login as DC user: stateuserDC@test.com
- Verify that "View Combined Rates" button is visible on the home page
---
---
---

CMDCT-5019 - removed DC from combined rates exception

---

deployment/constructs/dynamodb-table.ts
deployment/constructs/lambda-dynamo-event.ts
deployment/constructs/lambda.ts
deployment/constructs/waf.ts
deployment/deployment-config.ts
deployment/stacks/api.ts
deployment/stacks/customResourceRole.ts
deployment/stacks/deployFrontend.ts
deployment/stacks/parent.ts
deployment/stacks/topics.ts
deployment/stacks/ui-auth.ts
deployment/stacks/ui.ts

Update to manage all log groups, retain logs for 30 days, not create log groups in ephemeral environments
CMDCT-4974
CMDCT-4985
---
Open deployed environment, confirm it still works: https://d2g4t730knnx8t.cloudfront.net/
---
---
---

Update to manage all log groups, retain logs for 30 days, not create log groups in ephemeral environments

---

services/ui-src/src/components/CompleteMeasureFooter/index.tsx
services/ui-src/src/components/ContainedButton/index.tsx
services/ui-src/src/components/MeasureWrapper/index.tsx
services/ui-src/src/shared/commonQuestions/MeasureStratification/NDR/ndrFields.tsx
services/ui-src/src/shared/commonQuestions/MeasureStratification/index.tsx
services/ui-src/src/shared/commonQuestions/MeasurementSpecification.tsx

There's no consistent way to trigger this complete error bug but there was an error being triggered when you select the "I am not reporting measure stratification measure for this measure" when there was no oms data to clear.
Another possibility is that the user click validate and then try to complete the measure before validation/saving finished running. I disabled clicking the [**Validate Measure**], [**Complete Measure**] &  [**Clear Data**] button when saving is in progress in case the issue is slow saving with the user trying to click complete at the same time.
**Note**: I only added the spinner animation to [Validate Measure] as Complete Measure & Clear Data both quickly leaves the pages so I didn't see the need for it.
https://github.com/user-attachments/assets/3a56233f-3ffc-486c-b4 …

[CMDCT-5021] Complete Measure Navigation

---

services/ui-src/src/shared/commonQuestions/MeasureStratification/index.tsx

- Updated stratification warning to match design and wording
CMDCT-5029
---
- Login: https://d41fvi2yh6wxq.cloudfront.net/
- Go to a measure that requires stratification (like AAB-CH)
- Select yes under "Measurement Specification" and fill out the num/denom towards the bottom to reveal the stratification section
- Observe that the warning matches the one from the story
---
---
---

CMDCT-5029 - updated stratification warning

---

.github/setBranchName.sh
deployment/MASTER_TO_MAIN_INSTRUCTIONS.md
deployment/app.ts
deployment/deployment-config.ts
deployment/stacks/api.ts
deployment/stacks/empty/parent.ts
deployment/stacks/imports_included/data.ts
deployment/stacks/imports_included/parent.ts
deployment/stacks/imports_included/ui-auth.ts
deployment/stacks/imports_included/ui.ts
deployment/stacks/imports_included/uploads.ts
deployment/stacks/ui-auth.ts
deployment/stacks/ui.ts
deployment/stacks/uploads.ts
services/app-api/libs/kafka-source-lib.test.ts
services/app-api/libs/kafka-source-lib.ts
services/topics/handlers/createTopics.js
services/topics/handlers/deleteTopics.js
services/topics/handlers/listTopics.js
src/run.ts

Many updates to allow nearly all names of master to become main
CMDCT-5012
---
Make sure the app still works after the transition
NA
---
---
---

CMDCT-5012 - remove most remaining vestiges of master

---

deployment/constructs/lambda-dynamo-event.ts
deployment/constructs/lambda.ts
deployment/stacks/uploads.ts
src/runner.ts

Sync our CDK constructs across our apps
CMDCT-5014
---
---
---
---

Sync our CDK constructs across our apps

---

services/ui-src/src/App.tsx
services/ui-src/src/components/SkipNavigation/index.test.tsx
services/ui-src/src/components/SkipNavigation/index.tsx
services/ui-src/src/components/index.tsx

- Added a SkipNav link 
CMDCT-4805
---
- Login: https://d3466jyr1zo89z.cloudfront.net/
- When you tab it should select the SkipNav element first, and selecting it will focus the main section
---
---
---

CMDCT-4805 - Added a SkipNav link

---

services/ui-src/src/App.tsx
services/ui-src/src/components/Breadcrumbs/index.tsx
services/ui-src/src/components/Layouts/StateLayout/index.tsx
services/ui-src/src/utils/index.tsx
services/ui-src/src/utils/other/useBreakpoint.test.ts
services/ui-src/src/utils/other/useBreakpoint.ts

This PR:
- gets rid of some outdated sticky implementation 
- adds in useBreakpoints functionality consistent across all our apps 
- adjusts CSS settings via useBreakpoints to change stickiness of this subheader 
CMDCT-4815
---
cloudfront link: https://d1o0becny7rbsq.cloudfront.net/
1. Login to QMR, and test that the subheader (the light blue header) is sticky within standard desktop settings 
2. Zoom to 400% (this changes the breakpoints to recognize the page settings as mobile), and confirm that the header is no longer sticky and you can see the rest of the content on the screen when you scroll
---
---
--- …

Sticky header - Uncover content for 400%

---

services/topics/config.js
services/topics/handlers/createTopics.js
services/topics/handlers/deleteTopics.js
services/topics/handlers/listTopics.js
services/topics/libs/topics-lib.js
services/topics/package.json

Convert topics service to ESM
CMDCT-
---
---
---
---

Convert topics service to ESM
