Enterprise-CMCS/macpro-mdct-qmr

services/ui-src/src/measures/2021/FUAAD/questions/MeasurementSpecification.tsx
Added new drop down options for HEDIS 
https://qmacbis.atlassian.net/browse/OY2-15672
For FFY 2022 the list should be modified to:
HEDIS MY 2021 (FFY 2022 Core Set Reporting)
HEDIS MY 2020 (FFY 2021 Core Set Reporting)
HEDIS 2020 (FFY 2020 Core Set Reporting)
The business rule is to add the current year and drop the oldest year.
=> quick fix for HEDIS dropdown

services/ui-src/src/components/MeasureWrapper/index.tsx, tests/cypress/support/commands.js
the methods.reset() method doesnt reset the checkboxes or radio buttons. Without actually rewriting those components this may be a good option, it submits an empty data object and then goes back a page. 🤷 
also added that callback to the submit functionality because i think that makes sense
and updated a cypress command to clear measures and then go back into the measure.
Anyways, if you wanted to go this direction id be good with it. Just a suggestion.
=> Update clear data functionality

services/ui-src/src/components/Rate/index.tsx, services/ui-src/src/measures/2021/PQI01AD/questions/OtherPerformanceMeasure.tsx, services/ui-src/src/measures/2021/PQI01AD/questions/PerformanceMeasure.tsx, services/ui-src/src/measures/2021/PQI15AD/questions/OtherPerformanceMeasure.tsx, services/ui-src/src/measures/2021/PQI15AD/questions/PerformanceMeasure.tsx
Per our conversation with Dani this morning, the NDR manual sets needed to be slightly different with numerical numbers potentially greater than 100 with only one number after the decimal point.
=> adjusted logic to fit issue with manual NDR rate numerical input

destroy.sh
resolves issue with destroy script failing when destroying s3 buckets with +1000 versioned objects
=> recursively destroy versioned s3 objects

services/ui-auth/serverless.yml
Resolve issues from 3/16/2022 pen test allowing open user creation
[https://qmacbis.atlassian.net/browse/OY2-17149) ](https://qmacbis.atlassian.net/browse/OY2-17149)
Removes ability for user to sign themself up.
Since user pools are created for integration branches, may need to be adjusted in the console in addition to code change.
Also, may need to add to quickstart.
=> Add AllowAdminCreateUserOnly for Cognito user pool

.github/workflows/deploy.yml, .gitignore, README.md, tests/cypress/configureLocal.sh, tests/cypress/cypress.json, tests/cypress/support/commands/commands.js, tests/cypress/support/pages/LoginPage.js
this changes the output of configureLocal.sh in test/cypress to export a cypress.env.json file to be used locally and imports envars to be used in pipeline. This fixes an issue where env vars were not available when running tests (the cy.type() empty string thing)
as a result folks will prob need to run configureLocal.sh again or adjust the test-config file in place.
=> Update cypress env vars

services/app-api/handlers/dynamoUtils/measureList.ts, services/ui-src/src/dataConstants.ts, services/ui-src/src/measures/2021/FUAHH/data.ts, services/ui-src/src/measures/2021/FUAHH/index.tsx, services/ui-src/src/measures/2021/PCRHH/index.tsx, services/ui-src/src/measures/2021/PQI92HH/index.tsx, services/ui-src/src/measures/CommonQuestions/DefinitionsOfPopulation/index.tsx, services/ui-src/src/measures/CommonQuestions/Reporting/index.tsx, services/ui-src/src/measures/CommonQuestions/WhyAreYouNotReporting/index.tsx, services/ui-src/src/measures/measuresList.ts, tests/cypress/cypress/integration/measures/PCRHH.spec.ts, tests/cypress/cypress/integration/measures/QUALIFIERS_healthhome.spec.ts
Adding two selections to "Why are you not reporting on this measure" for all Health Home Measures/HH text updates: (115, 116, 117, 120, 121)
https://qmacbis.atlassian.net/browse/OY2-18262
=> Oy2 18262 - Adding two selections to "Why are you not reporting on this measure" for all Health Home Measures/HH text updates

services/ui-src/src/views/Qualifiers/HealthHome/costSavingsData.tsx, services/ui-src/src/views/Qualifiers/HealthHome/index.tsx
https://qmacbis.atlassian.net/browse/OY2-18434
Application endpoint:  https://d2wk89rcvizfao.cloudfront.net/
The function "handleSave" needs to be passed down as a prop so that the upload component in the HH qualifier is able to autosave when a file is uploaded.
=> Fix autosave on file upload for Health Home Qualifiers

services/ui-src/src/components/DateRange/index.tsx, services/ui-src/src/components/MonthPicker/calendarPopup.tsx, services/ui-src/src/components/MonthPicker/index.tsx
https://qmacbis.atlassian.net/browse/OY2-18576
Application endpoint:  https://d3tlh4tt4leyl7.cloudfront.net/
Passed the year as a prop to the calendar popup component so that it may dynamically update depending on the year of 
the measure
=> Allow Date Range to Select Year of current measure (allows 2022)

services/app-api/handlers/dynamoUtils/measureList.ts, services/ui-src/src/measures/2022/FUMCH/data.ts, services/ui-src/src/measures/2022/FUMCH/index.tsx, services/ui-src/src/measures/2022/FUMCH/types.ts, services/ui-src/src/measures/2022/FUMCH/validation.ts, services/ui-src/src/measures/2022/index.tsx, services/ui-src/src/measures/measureDescriptions.ts
Adding FUM-CH measure, closes [OY-17992](https://qmacbis.atlassian.net/browse/OY2-17992). 
Application endpoint: [Quality Measure Reporting](https://d1nz3gmcjkjs1v.cloudfront.net/).
Closes OY-17992.
Created a new measure.
How to create a new measure, how to differentiate between Child, Adult, and Health Home measures in the code.
N/A
=> OY017992: FFY2022 FUMCH Measure

services/ui-src/src/measures/2021/Qualifiers/deliverySystems.tsx, services/ui-src/src/measures/2022/Qualifiers/deliverySystems.tsx
Add a min-width prop to table heading to ensure text is not truncated.
[Oy2-19037](https://qmacbis.atlassian.net/browse/OY2-19037?atlOrigin=eyJpIjoiNjNjMzVmOTkwYWRkNDA4MDkwNTgwYjdjNGE4MjJjODgiLCJwIjoiaiJ9)
Row labels are read-only `QMR.TextInput`s. By extending the column width, the label in question has been made visible. 
Before:
After:
The problem with this approach is that an input will never wrap. A long label will always run the risk of being truncated. For those labels that are pre-populated, it might make sense to have these be wrapped by some tag other than input. This would allow us to word-wrap, perhaps be more mobile friendly (terminology used loosely), prevent us from having to potentially update this prop in the future.
Went the CSS route in the interest of affecting as few …
=> [Oy2-19037] Qualifier Styling Update

services/ui-src/src/measures/2021/SSHH/questions/PerformanceMeasure.tsx
Ensure all previously-saved performance measures display properly when loading a completed or saved state specific measure.
Resolves [OY2-19133](https://qmacbis.atlassian.net/browse/OY2-19133)
Instead of using `useForm()` to populate default values, we switched to `useFormContext()` which has access to the full form data. To create a "blank" default for users creating new state specific measures, we added a `useEffect()` hook that will auto-populate a blank performance measure field set in the same way it did before.
It was also important to add missing `key` values for the description and rate fields.
The result is that state specific measures that have no performance rates will open with an empty NDR set awaiting user input, and for saved state specific measure it will display the saved …
=> [OY2-19133] Missing NDR sets in saved state specific measures

services/ui-src/src/measures/2021/FUHAD/data.ts, services/ui-src/src/measures/2022/AMBCH/validation.ts, services/ui-src/src/measures/2022/FUHAD/data.ts
This solves two issues
1. FUH-AD measure change “of discharge” to “after discharge” for 2021 and 2022
2. AMB-CH FY 22 validation to allow for numerators larger than denominators 
[https://qmacbis.atlassian.net/browse/MDCT-1819](https://qmacbis.atlassian.net/browse/MDCT-1819)
[https://qmacbis.atlassian.net/browse/MDCT-1820](https://qmacbis.atlassian.net/browse/MDCT-1820)
1. I changed some words
2. I removed some validation logic
=> Mdct 1819 1820 dan

services/ui-src/src/measures/2022/SFMCH/index.tsx, services/ui-src/src/measures/2022/W30CH/index.tsx
Adds text box to specified performance measures 
[https://qmacbis.atlassian.net/browse/MDCT-1821](https://qmacbis.atlassian.net/browse/MDCT-1821)
It adds the text box
I learned the things to complete the ticket
If this is a thing that happens for all measures in their second year+ it might be worth looking into if we can automate this flag vs manually setting it each year
=> COMP: Updated 2022 measuers

services/ui-src/src/components/MeasureWrapper/index.tsx, services/ui-src/src/error.d.ts, services/ui-src/src/measures/2021/globalValidations/ComplexValidations/ComplexValidateDualPopInformation/index.tsx, services/ui-src/src/measures/2021/globalValidations/validateDualPopInformation/index.ts, services/ui-src/src/measures/2022/globalValidations/ComplexValidations/ComplexValidateDualPopInformation/index.tsx, services/ui-src/src/measures/2022/globalValidations/validateDualPopInformation/index.ts
To update the validation message for "Definition of Denominator Medicare/Medicaid Dually Eligibles" from an error to a warning.
**Note:** This is a duplicate PR, the other branch was having issues.
Application endpoint: https://d2i6sdy4antu38.cloudfront.net/
Closes [MDCT-496](https://qmacbis.atlassian.net/browse/MDCT-496).
There's an optional field for error types, if there needs to be a "Warning" or another custom field as opposed to "Error", that can now be done.
=> MDCT-496: Update Denominator Medicare/Medicaid Dually Eligibles Validation Message

services/ui/serverless.yml
Enable cloudfront logs. The bucket was already there, just didn't have it hooked up to the cloudfront distribution with the right permissions.
[MDCT-490](https://qmacbis.atlassian.net/browse/MDCT-490)
View this bucket `024259748323-ui-mdct-490-cloudfront-logs-cloudfront-logs` in qmr dev. It has logs!
=> Mdct 490 cloudfront logs

services/ui-src/src/components/Upload/index.tsx, services/uploads/src/antivirus.js, services/uploads/src/clamav.js, services/uploads/src/constants.js
Following [guidance from the quickstart ](https://github.com/CMSgov/macpro-quickstart-serverless/pull/556) we've bolstered the security for uploading files. 
You can test this by going to the link below. Navigate to any measure. Towards the bottom there should be an upload drop-in. Drag some files here. Try file names with invalid characters. Make sure the error message pops up. You can then check the cloudwatch logs in AWS [/aws/lambda/uploads-mdct-1842-sec-updates-avScan](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fuploads-mdct-1842-sec-updates-avScan) if you want to be extra thorough. (Need access to AWS QMR dev.)
[d1j27qj2dle7ng.cloudfront.net](d1j27qj2dle7ng.cloudfront.net)
Allowed characters: …
=> Mdct 1842 pt. 1 File upload security

services/ui-src/src/components/SubmitCoreSet/index.tsx, services/ui-src/src/views/CoreSet/index.tsx
User reported that after completing all measures and qualifier questions for a measure SPA, they were not able to submit because the "Submit" button was disabled. 
To test:
- `./dev local`
- Log in as a state user (e.g. `stateuserNJ@test.com`)
- Complete and submit any measure report (you can just select that you won't be reporting any of the measures under a report and it should let you submit)
No issues tracked.
There was a problem comparing the number of completed measures and the total measures expected, which is fixed now.
=> [Bug Fix]: Measures Submit Issue

services/ui-src/src/views/CoreSet/index.tsx
Fixes an issue where people couldn't submit when they completed all measures _and_ the coreset (because then the values were unequal)
According to David all measure sets should have a coreset so this check safely works for those, as well as when someone adds measures (because # completed must match # of measures + 1)
=> add coreset to completed check

services/ui-src/src/components/PCRRate/index.tsx
[MDCT-1914](https://qmacbis.atlassian.net/browse/MDCT-1914) Had an issue where a certain field that allows decimals was not calculating correctly. The reason was that we were parsing the field for integer, where the submitter is expected to provide a floating point. 
This will not impact fields that can only be integers because those do not allow you to enter a decimal.
Parsing float for both so that integer <-> float math doesn't mess with our float. Let me know if I'm wrong on that. See above point for why I'm not concerned.
=> MDCT 1914 - parse floats

services/app-api/serverless.yml
AWS Lambda seems to be timing out for `Prince PDF` requests due to a `serverless` configuration.
N/A
=> Fix AWS Lambda Timeout Configuration

services/ui-src/src/components/MeasureWrapper/index.tsx, tests/cypress/cypress/integration/measures/APMCH.spec.ts, tests/cypress/cypress/integration/measures/QUALIFIERS_adult.spec.ts, tests/cypress/cypress/integration/measures/WCCCH.spec.ts
Closes [MDCT-1961](https://qmacbis.atlassian.net/browse/MDCT-1961).
State-specific measures aren't pulling in filled data on refresh, but that should be fixed now. Will be testing in `dev` and `val` to ensure it's not an authentication issue.
To test:
- `nvm use`
- `./dev local`
- Log in as `stateuser4@test.com`
- Add **Health Home** measures to QMR report
- Scroll down, add **State Specific** measures (up to 5)
- Fill data for any of them, then **Complete Measure**
- Refresh and verify data is still populated
- Go back to list of measures, then back into the filled measure, verify again
=> Bug Fix: State Specific Measure Data

services/uploads/serverless.yml
The dynamoSync started failing silently on or around the 19th of December. This is the error message from Cloudfront. According to the [serverless docs](https://www.serverless.com/framework/docs/providers/aws/guide/functions/) this should buy us some runway. I think we need to evaluate a better solution for this long term. This just buys us a little more room over block leave.
`2022-12-19T06:33:36.193Z c6678057-41e8-42d6-a681-af706c80e79a Task timed out after 6.02 seconds`
I upped the memory as well as the time because we were danger close on size as well. I **think** this should work.
No changed dependencies, just some serverless attributes.
=> WIP: added power to the dynamoSync function

.github/workflows/deploy.yml
Cypress tests fail for dependabot. This is because when we deploy QMR the branch name is hashed, but when cypress runs it looks for the original branch name.
This PR solves that
N/A can only be validated by dependabot
NA
=> adding the branchname hash required for dependabot

services/ui-src/src/measures/2023/AABAD/data.ts, services/ui-src/src/measures/2023/shared/CommonQuestions/PerformanceMeasure/index.tsx
Client requested that the formula in the text be on a new line.
The solution was to add the prop  `dangerouslySetInnerHTML` in order to add the text in a way that would allow for a line break. We don't need to worry about opening up the app to injections here because this text is pulled from a local reference (not from the db) and not user input. [Reference here](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml)
You should see this text in one line and breaking at the container size.
=> set formula on a new line

.github/PULL_REQUEST_TEMPLATE.md, services/ui-src/src/index.tsx
Make LD flags work in deployed envs.
LD Flags were not working in the deployed envs, but were locally. They were keying off of process.env which, surprisingly, works locally, but is not available on deploy. This just swaps it over to pull from the config instead.
Unblocks https://qmacbis.atlassian.net/browse/MDCT-2217
The LD client should still configure correctly locally (check out the network tab / console logs).
N/A
=> LD flag fix

services/ui-src/src/measures/2023/shared/CommonQuestions/OtherPerformanceMeasure/index.test.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/OtherPerformanceMeasure/index.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/PerformanceMeasure/index.test.tsx
When `other` performance measures and `other` data sources are selected, the user can add `rates`.  There is no ability to delete any rate  that has been added by clicking the 'add another' button. This PR adds the option to delete a rate.
When `other` performance measures and `other` data sources are selected, the user can add `rates`. This allows them to delete any extra rates beyond the first one.
[jira link](https://qmacbis.atlassian.net/jira/software/c/projects/MDCT/boards/232?modal=detail&selectedIssue=MDCT-2254)
Go into AAB-AD and select 'other' in measures and data sources. In `Other Performance Measures`, you will see `Describe the rate`. Add more and see that there is a trash icon to delete the extras.
=> Add option to delete a rate - Mdct 2254

services/ui-src/src/measures/2023/shared/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/OtherPerformanceMeasure/index.tsx
This is the same fix as before, to get a line break for the formula. This was overlooked in my last PR.
Go to AAB-AD and get the other performance measures to show up. You'll see that the string has a line break and not a literal `<br>` tag in the browser.
> 
>  "Enter a number for the numerator and the denominator. The measure is reported as an inverted rate. 
> <br/> The formula for the Rate = (1 - (Numerator/Denominator)) x 100"
Test the same thing inside the Optional Measure Strat section as well
=> fix the text for other performance measures

services/ui-src/src/components/DateRange/index.test.tsx, services/ui-src/src/components/DateRange/index.tsx
adds inline validation for `YYYY` format in start and end date
When a user clicks the `validate` button at the bottom, they are informed of any errors. This PR adds inline validation so they are notified of the `YYYY` format error before getting all the way to the end of the page.
[jira](https://qmacbis.atlassian.net/jira/software/c/projects/MDCT/boards/232?modal=detail&selectedIssue=MDCT-2245)
Go to 2023, choose any of the measures, see that there is now inline validation after you start typing the year or start and end date.
=> add inline validation for YYYY

services/ui-src/src/measures/2021/CommonQuestions/PerformanceMeasure/index.test.tsx, services/ui-src/src/measures/2022/SSHH/questions/PerformanceMeasure.tsx, services/ui-src/src/measures/2023/SSHH/index.test.tsx, services/ui-src/src/measures/2023/SSHH/questions/PerformanceMeasure.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/PerformanceMeasure/index.test.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/PerformanceMeasure/index.tsx
2023 measures have the text and text box hidden by the flag `periodOfHealthEmergency2023`.
In 2023, the text `Describe any COVID-related difficulties encountered while collecting this data:` and textbox are hidden behind a flag.
[jira](https://qmacbis.atlassian.net/jira/software/c/projects/MDCT/boards/232?modal=detail&selectedIssue=MDCT-2248)
Measure CPB-AD has this text and text box. Go to this measure in 2021 or 2022, fill out all the fields and you will see the text and text box show up in Performance Measures. If you go into 2023's CPB-AD, you will not.
=> covid related description box hidden behind flag

services/ui-src/src/components/MeasureWrapper/index.tsx
Fix the Measure Wrapper "Complete Measure" functionality to submit the most recent data, rather than all preset data chunks.
When an invalid measure is manually set to "Complete" by clicking through the modal, a bad state could be sent alongside the request. Moved it to allow the form itself to handle the submission after validation. See testing instructions for more details.
MDCT-2340
---
The previous bad state could be triggered as followed:
* Pick a measure with nested items. The child measure WCC-CH, for example.
* Begin populating the measure, but leave some part, like the date fields incomplete to trigger validation warnings (important for the next part)
* In the Data sources, fill some root and nested fields
* Click Save. The database should reflect a populated DataSource, and …
=> [MDCT–2340] Complete Measure when Invalid - Save correct data

services/ui-src/src/measures/2023/SSHH/questions/PerformanceMeasure.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/PerformanceMeasure/index.tsx
Included a text section in the `periodOfHealthEmergency2023` flag
MDCT-2405
---
Go to a hybrid measure like CBA-AD, fill out the form to get `Performance Measures` to show up. You will not see the text when the flag is disabled. Have Brendan or Karla enable the flag `periodOfHealthEmergency2023` to see the text appear.
---
---
=> put text behind periodOfHealthEmergency2023 flag

services/ui-src/src/measures/2023/CCPAD/index.test.tsx, services/ui-src/src/measures/2023/rateLabelText.ts
Added / Updated N/D/R for the current measures :  
- CCP-AD
- IET-AD
Not updated here
- COL-AD : ignore, was completed in a separate ticket
- HBD-AD: updates will be made in HPC-AD-2023-Update branch due to abbr not existing currently.
MDCT-2359
---
1) Sign in and select Reporting Year to 2023
2) Select Adult Core Set Measures
3) Open CCP-AD
4) Fill in answers until N/D/R fields popup (Selecting the first answer for the first 3 questions should do the trick)
5) Confirm that it says **Ninety** Days Postpartum Rate instead of Sixty Days Postpartum Rate
For IET-AD
6) Repeat for steps 1-4 for IET-AD measures
7) Refer to page 3-5 pdf on ticket for text changes
N/A
---
--- …
=> Ndr changes

services/ui-src/src/measures/2023/AIFHH/index.test.tsx, services/ui-src/src/measures/2023/rateLabelText.ts
Added `(Age 18 and older)` to `Total` text in AIF-HH
MDCT-2260
---
Login as a state user that has Home Health (stateuserME), fill out the entire measure to see the rates come up, scroll down to  `Total` and see that 1(Age 18 and older)` has been added.
---
---
=> MDCT-2260 - update to text

services/ui-src/src/measures/2023/FUAHH/data.ts, services/ui-src/src/measures/measureDescriptions.ts
Text changes for FUA-HH (specifically FFY 2023 measures)
MDCT-2374
---
- Login using the stateuser4@test.com user
- Add health home core data set
- Open health home core data set, navigate to FUA-HH
- See corresponding text changes
- Title change: Follow-Up After Emergency Department Visit for *Substance Use*
- Measure description change: Choose HEDIS under "Measurement Specification", navigate down to Performance Measure section and confirm text changes
N/A
---
---
=> Tech Spec Changes - FUA-HH

services/database/package.json
Description
Updates dynamodb local to use direct override while we wait for serverless-dynamodb-local to be updated.
Related ticket(s)
Bugfix
How to test
Perform a fresh checkout
Follow the local build/deploy instructions
Validate that your dynamodb instance spun up without errors.
Important updates
---
---
=> package.json override of dynamodb local version

services/ui-src/src/measures/2023/IETHH/data.ts, services/ui-src/src/measures/measureDescriptions.ts
1. Text changes to Initiation and Engagement of Alcohol and Other Drug Abuse or Dependence Treatment (IET-HH) measure title for FY 2023
2. Amend the description of the measure
MDCT-[MDCT-2377](https://qmacbis.atlassian.net/browse/MDCT-2377)
---
* Login using the [stateuser4@test.com](mailto:stateuser4@test.com) user
* Add health home core data set
* Open health home core data set, navigate to IET-HH
**Title change**:  *Initiation and Engagement of Substance Use Disorder Treatment*
**Performance Measure description change:**
*Percentage of new substance use disorder (SUD) episodes that result in treatment initiation and engagement.  Two rates are reported:*
*Initiation of SUD Treatment.  The percentage of new SUD episodes that result in treatment initiation through an inpatient SUD …
=> Tech Spec Changes - IET-HH

services/ui-src/src/measures/2023/COLHH/data.ts, services/ui-src/src/measures/2023/rateLabelText.ts
Changes to NDR labels for Health Home measures for 2023.
MDCT-2384
---
1) Sign into QMR using user: stateuserWA@test.com
2) Go to Reporting Year 2023
3) Review each measure below. To see the changes, select the first radio button for the first 3 questions and that will enable the N/D/R inputs
COL-HH
- New N/D/R Set: **Ages 46 to 49**. 
- Note: Typo in PDF, confirmed with David that the number is suppose to 46 and not 45 for the sentence too.
IEH-HH
-  Review PDF for text changes, pages 1 - 5 (MDCT-2384)
AIF-HH 
- was completed in MDCT-2260
IU-HH
- Removed maternity as a column 
N/A
---
---
=> Tech Spec Changes - Changes to N/D/R Set(s) 

services/app-api/handlers/dynamoUtils/measureList.ts, services/ui-src/src/dataConstants.ts, services/ui-src/src/measures/2023/CPUAD/data.ts, services/ui-src/src/measures/2023/CPUAD/index.test.tsx, services/ui-src/src/measures/2023/CPUAD/index.tsx, services/ui-src/src/measures/2023/CPUAD/types.ts, services/ui-src/src/measures/2023/CPUAD/validation.ts, services/ui-src/src/measures/2023/index.tsx, services/ui-src/src/measures/2023/rateLabelText.ts, services/ui-src/src/measures/measureDescriptions.ts
CPU-AD is **Long-Term Services and Supports Comprehensive Care Plan and Update** for adults.
MDCT-2427
---
This is an adult measure for 2023, and it should line up with the story description.
n/a
---
=> Create new measure: CPU-AD

destroy.sh
Variables weren't being substituted correctly, causing the destroy script to fail.
[MDCT-2467](https://qmacbis.atlassian.net/browse/MDCT-2467)
---
N/A, destroy action should pass.
---
---
=> Update destroy.sh to fix bug w/ variable subsitutiton

services/ui-src/src/views/StateHome/__tests__/AddCoreSetCards.test.tsx, services/ui-src/src/views/StateHome/__tests__/index.test.tsx, services/ui-src/src/views/StateHome/index.tsx, tests/cypress/support/commands/commands.ts
removing the ability to add Home health Core Sets for FFY 23 for states CA, DE, and OK.
MDCT-2471
---
Log in as stateuser[STATE]@test.com (e.g.: stateuserCA@test.com) and see that in 2021 and 2022 you have the Health Home call to action and in 2023 it is gone. Login as a user not from CA, DE or OK (stateuserME has Home Health) and see that you still have the HH call to action in all reporting years.
---
---
=> Remove Health Home Core Sets for CA, DE, OK in 2023- Mdct 2471

services/ui-src/src/views/AddHHCoreSet/index.test.tsx, services/ui-src/src/views/AddHHCoreSet/index.tsx
https://qmacbis.atlassian.net/jira/software/c/projects/MDCT/boards/232?modal=detail&selectedIssue=MDCT-2553
"We would like to request a change in language for the Health Home landing page when a user goes to add a Core Set. Please replace the word SPA with "Health Home program" Please also remove the question mark so that the field reads: "Select the Health Home program you are reporting on."
Replace SPA on this page with Health Home program.
Remove ? mark after “on” 
---
1. Create a health home set and view landing page
=> Health home text changes

services/ui-src/src/utils/constants.ts
So there's a 2-char state/territory abbreviation showing up in the dropdown that should not be -- `FS`. The problem is that FS is not a valid ISO code or really anything else, so... why was it ever put there in the first place? We may never know.
Here's the PR where it was added in a few years ago: https://github.com/Enterprise-CMCS/macpro-mdct-qmr/pull/314
n/a
---
Pull down and run to make sure `FS` doesn't show up in the dropdown anymore.
n/a
---
---
=> remove 'FS' ISO code from constants (and dropdown)

services/ui-src/src/measures/2023/CPAAD/validation.ts, services/ui-src/src/measures/2023/CPCCH/validation.ts, services/ui-src/src/measures/2023/HPCMIAD/validation.ts, services/ui-src/src/measures/2023/IUHH/validation.ts, services/ui-src/src/measures/2023/SSDAD/validation.ts, services/ui-src/src/measures/2023/W30CH/validation.ts, services/ui-src/src/measures/2023/WCCCH/validation.ts, services/ui-src/src/measures/2023/WCVCH/validation.ts
IU-HH & HPCMI-AD have a hedis validation check despite not collecting hedis as information. 
MDCT-2619
---
1) Sign into QMR w/ an account that has HH (ex. [stateuserWA@test.com](mailto:stateuserDC@test.com))
2) Go to IU-HH measure
3) Fill out information and press validate
4) If you see "Version of HEDIS measurement year used must be specified" error message, it is broken. That error message should not popup
5) Repeat for **HPCMI-AD**
N/A
---
---
=> Removed Hedis Validation From Non Hedis Measures

services/ui-src/src/views/AddChildCoreSet/index.test.tsx, services/ui-src/src/views/AddChildCoreSet/index.tsx
Small change to capitalize the first 'S' in 'Core Sets' in the 'Add a Child Core Set' page
MDCT-2625
---
Login (stateuser1) and click 'Add a Child Core Set', see that the text is:
`Reporting Medicaid and CHIP measures in separate Core Sets
Reporting Medicaid and CHIP measures in combined Core Sets`
---
---
=> text change

services/ui-src/src/measures/2023/shared/CommonQuestions/CombinedRates/index.test.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/CombinedRates/index.tsx
Replacing instances of SPA-Level to Program-Level, only in FFY 2023
MDCT-2616
---
- Login: [(https://d1em988qnw7xrm.cloudfront.net/)]
- Add a Health home set in FFY 2023
- Pick a measure, scroll down to "Combined Rate(s) from Multiple Reporting Units"
- Confirm that "SPA-Level" is now "Program-Level"
---
---
=> Content Changes to HH - SPA replacement

services/ui-src/src/measures/2023/AABCH/index.test.tsx, services/ui-src/src/measures/2023/AABCH/validation.ts
Adding a validation flag to AAB-CH if a user does not select one of the indented buttons after selecting "Yes, we combined rates from multiple reporting units to create a State-Level rate."
MDCT-2622
---
- Add a child core set in 2023 and navigate to AAB-CH
- Under the section "Combined Rate(s) from Multiple Reporting Units" click "Yes, we combined rates from multiple reporting units to create a State-Level Rate" but *do not click* any of the sub options
- Click "Validate measure" and confirm that the Combined Rate(s) Error shows up
---
---
=> Combined Rates Validation Flag

services/ui-src/src/measures/2023/CPUAD/index.test.tsx, services/ui-src/src/measures/2023/CPUAD/validation.ts
CPU-AD has two rates: plans with core documentation, and plans with supplemental documentation. These rates are talking about the same universe of plans, so the denominators should be the same. And we assume that any plan with supplemental documentation will have core documentation, so the first rate should be larger. These two facts are now part of the validation for the measure.
While I was working on this, I noticed that CPU-AD still has OMS validation in place, despite its OMS section having been recently removed. That dead code is now deleted.
MDCT-2624
---
1. Open the CPU-AD measure for FFY 2023.
2. Enter a rate for Core, like 2/10
3. Enter a higher rate for Supplemental, with a different denominator. Like 4/8
4. Note the validation errors
5. Change the Supplemental rate to match …
=> Add missing validation for CPU-AD

services/ui-src/src/measures/2023/shared/CommonQuestions/OptionalMeasureStrat/data.ts, services/ui-src/src/measures/2023/shared/globalValidations/omsValidator/index.test.ts
Removed check box that said "add another subcategory". The Add Another Sub-category should be a button. Button was already added.
Previous display:
Fixed display:
https://qmacbis.atlassian.net/browse/MDCT-2442
`MDCT-2442`
---
Go to any measure and fill out form so that OMS is showing. Check the Ethnicity dropdown in the sequence shown in the screenshot. "Add another subcategory" should be shown as a button not a checkbox. 
---
---
=> [MDCT-2442] - OMS Bugfix

services/ui-src/src/components/IETRate/index.test.tsx, services/ui-src/src/components/IETRate/index.tsx
Missed a part during original ticket, IET-HH needed an extra set of calculations for the qualifiers. It needed to do a total calculation per qualifier set and as well as within the category type.
---
MDCT-2452
---
1) Login to a user with Health Home access (e.g. [stateuserWA@test.com](mailto:stateuserDC@test.com) )
2) Go to IET-HH measures
3) Trigger the performance measure section. (Selecting the first radio button for the first three questions)
4) Enter value in the N/D/R 
5) It should two sets of calculation, the "Total (age 13 and older)" qualifier in that category should update & either Initiation of SUD Treatment: Total OR Engagement of SUD Treatment: Total qualifiers will update depending on the category your value was entered in
---
--- …
=> Fix IETRate for IET-HH

services/ui-src/src/measures/2023/shared/globalValidations/ComplexValidations/ComplexValueSameCrossCategory/index.tsx
In IU-HH, the validation for comparing the number of enrollee months, which should be the same value across categories, is firing no matter if the value is the same or not. The error keeps showing **Value of "Number of Enrollee Months" in Ages 0 to 17 must be the same across all measurement categories.**, despite it being 0 to 17
MDCT-2620
---
1) Sign into QMR, use an account that shows HH ([stateuserWA@test.com](mailto:stateuserDC@test.com))
2) Add Health Home measures
3) Go to IU-HH
4) Under Measure Specification section, select the first radio button
5) In Performance Measure, enter values into the N / D / R sets. The Number of Enrollee Months if different across categories should trigger the correct error per qualifier. 
- All ages 0 to 17 qualifiers should have the same Number of …
=> Bug Fix: IU-HH Validation

services/ui-src/src/measures/2023/shared/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx
A bug is occurring when users attempt to preview the pdf on the `/pdf` route, which uses the `ExportAll` component. Nested deep inside the code for that part of the app was an issue where, if a user had entered any OMS data (thus requiring OMS data to be displayed on that page), an error would be thrown. This is because for OMS checkbox labels, where it looks for the label text to display, we were getting it 2 ways — a primary and a fallback. The problem was the specified label text was an `object` instead of a `string`, so the primary way was failing, then the backup way was grabbing the entire object where it was expecting just a string, and the app won’t render objects as children, and there you go: error.
Extent of this bug is limited to 2023 and OMS data when previewed on `/pdf` …
=> bugfix: ensure OMS checkbox displayValue is a string

services/ui-src/src/components/ComplexRate/index.test.tsx, services/ui-src/src/components/ComplexRate/index.tsx, services/ui-src/src/components/IETRate/index.test.tsx, services/ui-src/src/components/IETRate/index.tsx, services/ui-src/src/components/Rate/index.test.tsx, services/ui-src/src/components/Rate/index.tsx, services/ui-src/src/utils/getMeasureYear.ts
https://qmacbis.atlassian.net/browse/MDCT-2602
Within the Rates, ComplexRates & IETRates I added a category property to the rates data that links the "Rate category" to it's perspective "Qualifiers". This is only done for FFY 2023. 
Ex. The rates within the two columns will have the same category property of "Initiation of SUD Treatment..." (since they're both under that category).
---
1. Go to 2023 and select an measure. ( try /MA/2023/ACS/AAB-AD) 
2. Enter rates and check/console log the `prevRate` to see the new category
3. To see a measure with categories ( try /MA/2023/ACS/IET-AD)
4. Fill out all the rates and console log `prevRate` within `IETRate - index.tsx` to see the category show for rates that were filled in.
---
--- …
=> Include readable labels for Mathematica

services/uploads/package.json, services/uploads/yarn.lock
[Dependabot 86](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/86)
MDCT-
---
---
---
=> Dependabot Alert #86: Got allows a redirect to a UNIX socket

package.json, services/app-api/package.json, services/app-api/yarn.lock, services/database/package.json, services/database/yarn.lock, services/ui-auth/package.json, services/ui-auth/yarn.lock, services/ui-src/package.json, services/ui-src/yarn.lock, services/uploads/package.json, services/uploads/yarn.lock, yarn.lock
[Dependabot 173](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/173)
[Dependabot 174](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/174)
[Dependabot 175](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/175)
[Dependabot 176](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/176)
[Dependabot 177](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/177)
[Dependabot 178](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/178)
---
---
---
=> Dependabot Alerts #173 to #178: xml2js is vulnerable to prototype pollution

package.json, services/ui-src/package.json, services/ui-src/yarn.lock, yarn.lock
[Dependabot 142](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/142)
[Dependabot 146](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/security/dependabot/146)
---
---
---
=> Dependabot #142 + #146: Prototype Pollution in JSON5 via Parse Method

services/ui-src/src/measures/2023/LSCCH/index.tsx
LSC-CH turns out to be a hybrid so the hybrid text needs to be turned on.
MDCT-2686
---
1) Go to Reporting Year 2023
2) Select Child Core Set
3) Enter LSC-CH
4) Look at "Definition of Population Included in the Measure" section
5) Look and confirm the existence of text 
- "If you are reporting as a hybrid measure, provide the measure eligible population and sample size."
N/A
---
---
=> LSC-CH Hybrid Text

services/ui-src/src/components/Inputs/Checkbox/index.test.tsx, services/ui-src/src/components/Inputs/RadioButton/index.test.tsx, services/ui-src/src/measures/2023/CPAAD/questions/DataSource.tsx, services/ui-src/src/measures/2023/MSCAD/questions/DataSource.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/AdditionalNotes/index.test.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/AdditionalNotes/index.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/DataSource/index.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/DataSourceCahps/index.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/DefinitionsOfPopulation/index.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/DeviationFromMeasureSpecification/index.tsx
Adding an indicator label `(state-specific comment)` to certain fields for clarity on which data is state-specific. 
**Note:** Only applies to FFY2023.
MDCT-2332
---
---
---
=> MDCT-2332: Add State Reporting Fields Indicator Label

services/ui-src/src/measures/2023/shared/CommonQuestions/OptionalMeasureStrat/index.tsx
Update language in OMS section for FY2023
OLD
NEW
MDCT-2677
---
- Navigate to [deployed env](https://d1zkrdf8y5wdxu.cloudfront.net), or view locally
- Login -> Adult -> First option
- Under "Measure Specification" select HEDIS (first option)
- Select any from that dropdown
- Scroll down to "Performance Measure"
- Enter amounts into the first numerator/denominator fields
- This should make the OMS section pop up below
- Verify text updates under "Optional Measure Stratification"
n/a
---
---
=> Update copy for OMS FY23

services/ui-src/src/utils/getLabelText.tsx
This function returns `any`, which hamstrings the type checker. It should not return `any`.
This type hint _would_ have prevented the bug fixed by https://github.com/Enterprise-CMCS/macpro-mdct-qmr/pull/1845 . It's too late to prevent that bug, but we might as well add it now.
n/a
---
n/a - This function's behavior has been thoroughly tested, and this change does not affect that behavior at all.
n/a
---
=> Add a type hint to getLabelText

services/ui-src/src/measures/2023/shared/CommonQuestions/OptionalMeasureStrat/omsNodeBuilder.tsx
Add hyphen to word 'sub-categories'
BEFORE
AFTER
MDCT-2682
---
- Navigate to [deployed env](https://d17z68pmnn1088.cloudfront.net/), or view locally
- Login -> Adult -> First option
- Under "Measure Specification" select HEDIS (first option)
- Select any from that dropdown
- Scroll down to "Performance Measure"
- Enter amounts into the first numerator/denominator fields
- This should make the OMS section pop up below
- Verify text updates under "Optional Measure Stratification"
- Race
- Asian
- Native Hawaiian or Other Pacific Islander
- Ethnicity
- Hispanic, Latino/a, or Spanish origin
All of the above should have a hyphen in the word 'sub-categories' at the end of the second option (the 'No' option)
n/a
---
---
=> Add hyphen to "sub-categories" in OMS

services/ui-src/src/measures/2023/rateLabelText.ts
This was a request to remove the label text `All Women - Ages 21 to 44` from the rate sections.
MDCT-2253
---
Go to 2023 -> measure CCW-AD, fill it out to get OMS options, see that the text `All Women -Ages 21 to 44` does not appear as a label above Performance Measures and Optional Measure Stratification.
---
---
=> remove age label from rates

services/ui-src/src/components/Inputs/NumberInput/index.tsx, services/ui-src/src/measures/2023/shared/Qualifiers/Common/administrativeQuestions.test.tsx, services/ui-src/src/measures/2023/shared/Qualifiers/Common/administrativeQuestions.tsx
In Health Home qualifier questions, the state users want the total annual number of individuals to be auto sum but also changeable if desired. 
The NumberInput component has been updated to run an any function passed from it's layer up as to trigger the calculations for the sum.
MDCT-2243
---
1) Sign into QMR with an account that has HH (i.e. [stateuserWA@test.com](mailto:stateuserDC@test.com) )
2) Add a Health Home Measure
3) Click the text link in the gray box
4) Add random numbers to "total annual number of adults" and "total annual number of children"
5) "total annual number of individuals" should auto sum but still allow you to change the values to be different.
N/A
---
--- …
=> HH Qualifier - Individual Total 

services/ui-src/src/measures/2023/shared/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx
This fixes a bug in CIS-CH. Since previously we were associating OMS quals with PM quals by index, and CIS-CH has excludeFromOms on non-consecutive quals, we were seeing weird behavior. Completing the DTaP rate in PM would cause the MMR rate to show in OMS. Likewise IPV -> Combo 3, and MMR -> Combo 10.
Other measures seemed to be unaffected by this bug, and are likewise unaffected by the fix.
MDCT-2681
---
Log in and fill out some FFY 2023 performance measures. The appropriate rates should show up in OMS, as you fill out (or clear) rates in the main Performance Measure section. Some interesting measures are
* CIS-CH: OMS includes nonconsecutive qualifiers.
* DEV-CH: Multiple qualifiers and one category. All but the total qualifier are excluded from OMS.
* FUA-CH: One qualifier and two …
=> Associate OMS qualifiers with PM qualifiers by ID

services/app-api/handlers/kafka/get/forceKafkaSync.js, services/app-api/handlers/measures/get.ts, services/app-api/libs/dynamodb-lib.ts, services/app-api/libs/tests/dynamodb-lib.test.ts, services/app-api/types.ts
Defaults the scan operation to continue when LastEvaluatedKey is present. This should allow complete deleteion of measures in lower environments, in addition to preventing future oversights when LastEvaluatedKey is ignored.
Also retained the original operation as a scanOnce() operation, as it can still be useful to break early, or in the case of forceKafkaSync, handle the results of a batch one page at a time.
MDCT-2416
---
- Generate enough data locally to see the LastEvaluatedKey trigger which takes 1MB of data in a scan. One option for doing this is to find a large string (.5MB) to put in a free text area in the database directly. Do that a few times across items.
- All those results should still return in the UI when iterating through pages. You can do this by inflating a bunch of …
=> [MDCT-2416] default scan to iterate across results

services/ui-src/src/measures/2023/AABCH/index.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/PerformanceMeasure/index.tsx
Fixed the OMS rate calculation. Previously it was calculating using this formula N/D x 1000. The correct formula for AAB was 1 - (Numerator/Denominator) x 100. 
[MDCT-2680](https://qmacbis.atlassian.net/browse/MDCT-2680)
---
1. Create a 2023 child coreset 
2. Select AAB-CH measure
3. Enter N/D/R for OM 
4. Enter the same N/D/R for OMS
5. The ratio calculations should be the same
Before:
After:
---
---
=> Fix OMS Rate Calculation on AAB-CH

services/ui-auth/serverless.yml
The included portion of the redirect config breaks the IDM configuration. We're still retaining the ui redirect from #1863.
MDCT-2672
---
Merge to Dev and see if Dev IDM auth works again :(
---
---
=> [MDCT-2672] Trap Redirect config to UI

tests/cypress/cypress/integration/init/create_delete_child.spec.ts, tests/cypress/support/commands/commands.ts
create-delete-child.spec fails often. The failures are inconsistent. Added some wait commands to see if it's a timing issue. 
MDCT-2670
---
---
---
=> mdct 2670 e2e failure

services/ui-src/src/measures/2023/shared/CommonQuestions/AdditionalNotes/index.test.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/AdditionalNotes/index.tsx
Previously, the "Additional Notes/Comments on the measure (optional)" field content would persist even when the a user changes their Reporting status. The field now deletes it's content when ever a user switches Reporting status, similar to other fields in the form. 
https://qmacbis.atlassian.net/browse/MDCT-2259
MDCT-2259
---
1. Go to 2023 measure
2. In Measure select "Yes" from "Are you reporting on this measure?"
3. Scroll to "Additional Notes/Comments on the measure (optional)" and enter some content
4. Go back to "Are you reporting on this measure?" and change your selection to "No"
5. Scroll down to Additional Notes. The content should be deleted.
---
--- …
=> Removing Text in Additional Notes on Reporting Change

services/ui-src/src/components/Inputs/RadioButton/index.tsx, services/ui-src/src/components/MonthPicker/calendarPopup.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/DateRange/index.tsx
A couple of enhancements added to the date range
1) Update and moving the text "Information for each measure is available in the Measurement Period Table resource" to underneath the header text
2) have the calendar default year be current year - 1 (i.e. if the reporting year is 2023, the date range should default to 2022)
3) The date range min use to be 2021 but now it is 2020
MDCT-2763
---
1) Sign into QMR, any account will work
2) Select Reporting Year 2023
3) Go to adult measures AMM-AD
4) Scroll down to Date Range
5) Check for
- Text is the same as the one in the green box
- Calendar pop up, the **default year is 2022**
- The min amount of year back stops at 2020
---
--- …
=> Date Range Enhancements

services/ui-src/serverless.yml
Fix a misconfigured value in the serverless file 
MDCT-2638
---
---
---
=> [MDCT-2638] Use the custom param for the signout url

services/ui-src/src/components/ComplexRate/index.tsx, services/ui-src/src/measures/2023/AIFHH/data.ts, services/ui-src/src/measures/2023/IUHH/data.ts, services/ui-src/src/measures/2023/shared/CommonQuestions/OptionalMeasureStrat/context.ts, services/ui-src/src/measures/2023/shared/CommonQuestions/OptionalMeasureStrat/index.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/PerformanceMeasure/data.ts, services/ui-src/src/measures/2023/shared/CommonQuestions/PerformanceMeasure/index.tsx
IU-HH & AIF-HH have unique fields compare to the other measures. So the chain is Category -> Qualifier -> Fields. 
The ask is to add an id for the field as to prevent any issues if the field label changes. 
We have checked, and they don't require us to do chaining of the id name, so we're going with just the short id for the uid. 
So the data should look like the image below, in the database.
MDCT-2770
---
1) Sign into QMR, one with Health Home (i.e. [stateuserWA@test.com](mailto:stateuserDC@test.com))
2) Go to AIF-HH
3) Select the first radio button for the first 3 questions, this will open up performance measures
4) Fill out data for performance measures & OMS
5) Spin up local dynamo db
6) Find AIF-HH 2023 data in local dynamo db, there should now be uid keys in the data
N/A
---
--- …
=> Add UID to IU-HH & AIF-HH Field Data

services/ui-src/src/components/Inputs/Checkbox/index.test.tsx, services/ui-src/src/components/Inputs/RadioButton/index.test.tsx, services/ui-src/src/measures/2023/CPAAD/questions/DataSource.tsx, services/ui-src/src/measures/2023/MSCAD/questions/DataSource.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/AdditionalNotes/index.test.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/AdditionalNotes/index.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/DataSource/index.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/DataSourceCahps/index.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/DefinitionsOfPopulation/index.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/DeviationFromMeasureSpecification/index.tsx
BO wanted text to change from **(state-specific comment)** to **(text in this field is included in publicly-reported state-specific comments)**
MDCT-2782
---
2) Go to any measure
3) Changes where you can see the text
- Data Source > Other 
- Additional Notes
- Definition of Population Included in the Measure
- No, this denominator does not represent the total measure-eligible population as defined by the Technical Specifications for this measure.
---
---
=> State Specific Comment Change

services/ui-src/src/measures/2023/AABAD/data.ts, services/ui-src/src/measures/2023/AABCH/data.ts, services/ui-src/src/measures/2023/IUHH/data.ts
IU-HH
- Removed the word "maternity" from performance measure description
AAB-AD, AAB-CH
- Remore stray '/br' tag
MDCT-2783
MDCT-2789
---
MDCT-2783
- Sign into QMR with an account with HH, (i.e. [stateuserWA@test.com](mailto:stateuserDC@test.com))
- Go to IU-HH
- Select the first radio button in the first 3 questions to trigger the Performance Measure
- Scroll down to Performance Measure, the description text should read "(total, mental and behavioral disorders, surgery, and medicine)
MDCT-2789
- Go to AAB-AD
- Trigger the Performance Measure
- Scroll to Performance Measure, the bolded text should read "Enter a number for the numerator and the denominator. The measure is reported as an inverted rate. The formula for the Rate = (1 - (Numerator/Denominator)) x 100"
- The 'br/' tag should be …
=> Measure Text Updates

services/ui-src/src/measures/2023/CCWAD/validation.ts
CCW-AD is missing a validation to check if a state enters a LARC rate that is greater than the Most or Moderately Effective Contraception (MME) rate.
This error needs to show up.
MDCT-2778
---
2) Pick CCW-AD from measures
3) Select the first option of the radio buttons in the first 3 questions to open the Performance Measure section
4) In the Performance Measure section, fill out N/D/R set, example below. Just make sure LARC's numerator is higher. 
5) Validate and you should see 
6) When you make it lower, that validation should clear
---
---
=> CCW-AD Missing Validation

services/ui-src/src/dataConstants.ts, services/ui-src/src/measures/2023/CISCH/data.ts, services/ui-src/src/measures/2023/IMACH/data.ts
A data constant needed its text expanded for CIS-CH & IMA-CH. 
Since the data constant is stored in a shared variable between all 3 years, I created a new one for 2023.
The text has changed from:  
Immunization Registry → Immunization Registry/Immunization Information System (IIS)
MDCT-2785
---
2) Add Child CoreSet 
3) Go into child coreset and select CIS-CH
4) Scroll down to Data Source
5) Select Administrative Data, it should expand
6) You should see  "Immunization Registry/Immunization Information System (IIS)" as an option 
---
N/A
---
---
=> Update Data Constant

services/ui-src/src/measures/2023/AABAD/validation.ts, services/ui-src/src/measures/2023/AABCH/validation.ts, services/ui-src/src/measures/2023/LSCCH/validation.ts
AAB-AD, AAB-CH, and LSC-CH measures were missing a validation to check if a state user creates identical data labels for multiple Other Performance Section rates. 
MDCT-2779
---
- Navigate to either of those (AAB-AD, AAB-CH, LSC-CH)
- Under `Measurement specification`, pick `Other` and type in any description
- Scroll down to `Other performance measure` and click `Add another`
- Type in identical fields in `Describe the rate` like so:
Validate measure and you should see this error:
---
---
=> MDCT-2779: Add Missing Validation to AAB-AD, AAB-CH, LSC-CH

services/ui-src/src/measures/2023/shared/CommonQuestions/OptionalMeasureStrat/data.ts, services/ui-src/src/measures/2023/shared/CommonQuestions/OptionalMeasureStrat/index.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/OptionalMeasureStrat/omsNodeBuilder.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/types.ts, services/ui-src/src/measures/2023/shared/globalValidations/dataDrivenTools.ts, services/ui-src/src/measures/2023/shared/globalValidations/omsValidator/index.ts, services/ui-src/src/utils/testUtils/2023/validationHelpers.ts, tests/cypress/cypress/integration/measures/adult/HBDAD.spec.ts
The OMS classifications are using the label text as id, similar to how rateLabelText used label as both id and text. 
Added  a label key for each and replace the current id values to unique id values. A couple of components were updated to reflect this change.
Old
New
MDCT-2831
---
2) Pick any measure that has OMS, i.e. AAB-AD
3) Trigger Performance Measure section by selecting the first radio button in Measure Specification section
4) Scroll Down and fill our Performance Measure, this will enable OMS
5) Scroll Down to OMS
6) Fill out N/D/R and validate
7) Open local dynamodb
8) Check to make sure that the data is using 6 character ids and not words
N/A
---
---
_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | …
=> OMS Classification ID and Labels

services/ui-src/src/dataConstants.ts, services/ui-src/src/measures/2023/shared/CommonQuestions/OptionalMeasureStrat/ndrSets.tsx, services/ui-src/src/measures/2023/shared/globalValidations/omsValidator/index.ts, tests/cypress/cypress/integration/measures/adult/HBDAD.spec.ts
When saving other performance measure, if the user enters a rate name that is a number, that number ends being using as the length of the array instead of as a object key in the OMS OPM. Only happens if N/D/R is not filled out but option is selected.
I could not find any indication that it was done by QMR itself, it might be a rendering issue from the database. My solution was to add a variable (OPM_) in front on the string key to keep it from being a pure number.
MDCT-2828
---
2) Select a measure that has an Other performance measure, i.e. AAB-AD
3) In Measurement Specification, select "Other"
4) Scroll down to "Other Performance Measure"
5) Enter "12" in "Describe the Rate"
6) Select classification checkboxes in "Optional Measure Stratification" but DO NOT …
=> OPM Null Issue in DB

services/ui-src/src/measures/2023/rateLabelText.ts, services/ui-src/src/measures/2023/shared/globalValidations/validatePartialRateCompletion/index.ts
There is an extra comma being generated in a validator error for partial filled N/D/R sets. This only shows up in non category performance measure validation.
Also, tossed in some id changes to rateLabelText to the standard 6 character format that were missed
MDCT-2837
---
2) Select a measure with no category, i.e. AMR-AD
3) In **Measurement Specification** section, select the first radio button, that will open up **Performance Measure**
4) Scroll down to **Performance Measure**, only fill out only the numerator.
5) Validate
There should not be a comma in this validation error. 
---
---
=> Remove Extra Comma and ID changes

services/ui-src/src/components/IETRate/index.tsx, services/ui-src/src/components/Rate/index.tsx, services/ui-src/src/utils/rateFormulas/index.ts
When entering data into N/D/R if numerator and denominator is 0, the rate does not auto calculate. and leaves an empty input field. 
This change will have it fill the rate out with a zero
---
**Note:** AAB-AD & AAB-CH calculates a little differently, so the rate value would be 100%.
MDCT-2838
---
2) Select any measure that has a Performance Measure, i.e. AMR-AD
3) In the **Measurement Specification** section, select the first radio button to enable the **Performance Measure** section
4) In the Performance Measure section, enter 0 for Numerator and Denominator. Rate should now auto calculate to 0.0.
---
--- …
=> Calculate to Zero

.github/workflows/cypress-workflow.yml, tests/cypress/plugins/index.js
Following up on the discovery from [this PR](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/pull/1982)
[old headless plus container locked to chrome version](https://github.com/cypress-io/cypress/issues/27264#issuecomment-1732192738)
I guess the latest versions of chrome do "headless" differently so by pinning an older version using a container and choosing to run the "old" headless version it works
MDCT-2977
---
---
---
=> fix cypress tests hanging

.github/workflows/cypress-workflow.yml, .github/workflows/dependabot-auto-approve.yml, .github/workflows/deploy.yml, .github/workflows/destroy.yml, .github/workflows/git-secrets.yaml, .github/workflows/pullrequest-precommit-check.yml, .github/workflows/scan_security-hub-jira-integration.yml, .github/workflows/scan_snyk-jira-integration.yml, .github/workflows/unittest-workflow.yml
Updating versions to avoid warnings and deprecations
Note: these have already been tested in [another PR](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/pull/1982) and I'm migrating them here
DOCS:
[aws-configure-credentials readme](https://github.com/aws-actions/configure-aws-credentials) – no breaking changes between 1 and 4. ("By default, your account ID will not be masked in workflow logs. This was changed from being masked by default in the previous version. AWS does not consider account IDs as sensitive information, so this change reflects that stance." Let me know if you want to mask this still and I'll add that option)
[cache readme](https://github.com/actions/cache) – no breaking changes with v3
[codeclimate action changelog](https://github.com/paambaati/codeclimate-action/rel …
=> Update action versions

services/ui-src/src/views/AddHHCoreSet/index.tsx, services/ui-src/src/views/AdminHome/index.tsx, services/ui-src/src/views/Home/index.tsx, services/ui-src/src/views/StateHome/index.tsx
Removing the `release2023` feature flag from our codebase since they are no longer being used.
CMDCT-2985
---
Log in, you should land on the 2023 reporting year by default and you should see 2023 as an option on the year dropdown.
---
---
=> MDCT-2985: Cleaning Up LD Feature Flag

services/ui-src/src/measures/2023/AABCH/index.test.tsx, services/ui-src/src/measures/2023/AABCH/validation.ts
Entering 0/31 correctly sets the inverted rate but fails validation in both the nested rates and root for AAB-CH
Removed the extra validation logic to match AAB-AD, thus no longer triggering the error
CMDCT-3120
---
Edit AAB-CH and set the rate numerators to 0. Validate, error should not be present.
---
---
=> [CMDCT-3120] Remove zero validation errors from aab-ch validation set

services/ui-src/src/components/MeasureWrapper/index.tsx, services/ui-src/src/components/Rate/index.tsx, services/ui-src/src/measures/2023/AMRAD/index.test.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/OtherPerformanceMeasure/index.test.tsx, services/ui-src/src/measures/2023/shared/CommonQuestions/OtherPerformanceMeasure/index.tsx, tests/cypress/cypress/e2e/features/partially_completed_validation.spec.ts, tests/cypress/cypress/e2e/measures/adult/CCWAD.spec.ts, tests/cypress/cypress/e2e/measures/adult/COBAD.spec.ts
Other Performance Measure was crashing the render when you deleted a measure and saved because a null value got into the array. This fixes that issue. See video and How to Test for more info.
CMDCT-3062
---
On this branch:
- Sign in as a state user
- Generate Child core sets separately
- Go to Child core sets: medicaid and go to DEV-CH (note: fix applies to other measures. This is just what we've been testing)
- Select `Yes`, `Final Data`, `Other`, `Other` for the first four options
- Scroll down to Other Performance Measures and create three (description not necessary)
- Click save after creating three
- Delete the middle measure and save again
- Edit any other field and save once more. 
If you run this on `master`
- The render should crash.
- In dynamodb-admin you can see the `null` …
=> Othermeasure rates bug

services/database/package.json, services/database/scripts/remove2023QualifierHPCAD.ts, services/database/tsconfig.json, services/database/yarn.lock
Qualifiers for ND 2023 has HPC-AD in the array, HBD-AD is the new measure. The Mathematica ingestion chokes on the unexpected measure name.
Cause still unknown, but this script corrects for it and can get us back up and be re-used.
CMDCT-3142
---
- Run locally
- Create Adult CSQ
- Add auditing portion
- In the database manually stitch "HPC-AD" into the array of options
- Run script to correct
Run yarn in the db service before run
---
---
=> [CMDCT-3142] Add script to remove HPC-AD from 2023 CSQ

services/app-api/handlers/prince/pdf.ts, services/app-api/package.json, services/app-api/yarn.lock, services/ui-src/src/views/ExportAll/util.tsx
We recently discovered an issue in production where users are unable to print the export. That issue may come down to an incompatibility between the libraries we were using to sign the request. This PR trades those libraries for more basic, hopefully longer-lasting ones.
Note that we DO NOT use this API endpoint to print individual measures from their own pages; those print buttons use the browser's built-in print functionality. We may, at some point, wish to unify our printing approach; it feels odd to use Prince for some things and the browser for others.
CMDCT-3150
---
1. Log in and find yourself on the page for FFY 2023
2. In the table of coresets, open one of the context menus under "Core Set Actions"
3. Choose Export
4. Click the orange "PRINT PDF" button at the top of the page
n/a …
=> Attempt to switch Prince PDF call from axios to fetch

services/ui-src/src/dataConstants.ts, services/ui-src/src/measures/2024/CBPAD/validation.ts, services/ui-src/src/measures/2024/CBPHH/validation.ts, services/ui-src/src/measures/2024/CCSAD/validation.ts, services/ui-src/src/measures/2024/CISCH/validation.ts, services/ui-src/src/measures/2024/CPUAD/validation.ts, services/ui-src/src/measures/2024/DEVCH/validation.ts, services/ui-src/src/measures/2024/HBDAD/validation.ts, services/ui-src/src/measures/2024/HPCMIAD/validation.ts, services/ui-src/src/measures/2024/IMACH/validation.ts, services/ui-src/src/measures/2024/LSCCH/validation.ts, services/ui-src/src/measures/2024/PPCAD/validation.ts, services/ui-src/src/measures/2024/PPCCH/validation.ts, services/ui-src/src/measures/2024/WCCCH/validation.ts, services/ui-src/src/measures/2024/shared/globalValidations/index.ts, services/ui-src/src/measures/2024/shared/globalValidations/validateHybridMeasurePopulation/index.test.ts, services/ui-src/src/measures/2024/shared/globalValidations/validateHybridMeasurePopulation/index.ts
Certain measures have a data source option "Hybrid (Administrative and Medical Records Data)" or "Case management record review". When a user selects them, they new need to provide information here:
This PR adds a new validation that pops up if you don't fill that textbox
lidation
CMDCT-3294
---
2) In adult coreset, select CBP-AD or any measure that captures hybrid data.
3) In the Data Source selection, check [Hybrid (Administrative and Medical Records Data)]
4) Scroll all the way down and validate
5) This should cause the error message to show up
6) Fill out [What is the size of the measure-eligible population?]
7) Scroll back down to validate and that should clear the error message.
---
--- …
=> Measure Eligible Population Validation

services/ui-src/src/views/StateHome/AddCoreSetCards.tsx
For the FFY2024 landing page, the BOs have requested the removal of this text:
CMDCT-3295
---
You should not see that text area for 2024, but it should be visible for other years.
---
---
=> CMDCT-3295: Landing Page Content Update

services/ui-src/src/libs/spaLib.ts
Updating SPA IDs based on BO feedback.
CMDCT-3292
---
N/A
---
---
=> CMDCT-3292: Update Home Health SPA IDs

services/ui-auth/serverless.yml
Remove a chunk of the logic about where emails come from when signing up in cognito. This functionality is no longer used in seds, all test accounts in lower envs are created via seeding.
Proved it worked in SEDS [PR](https://github.com/Enterprise-CMCS/macpro-mdct-seds/pull/14810).
The stream functions service still references the ssm params for these emails, but not the ARNs and should continue to deploy fine. The functions there that trigger emails already do not work and are likely dead code, but I am in the process of verifying that officially.
This will unblock deployments for now.
---
---
---
=> Remove signup email configuration, unused, revert to default account

tests/cypress/support/commands.ts
Have you personally suffered from SS-HH cypress test just failing endlessly. The struggles of re-running the job over and over again because of this one script? The time wasted, the frustration, the senselessness of it all.
With this PR, I hope to fix this. Due to the inconsistent run order of the cypress test, the Health Home core measures sometimes gets deleted before its able to run the cypress test for HH, thereby causing the test to fail. SS-HH is trying to engage as if there's already a Health Home created when there isn't. This PR adds to the conditional that if there is no health home generated, go through the process to add it.
---
Cypress test should pass on this PR and locally
N/A
---
--- …
=> [Fix] SS-HH Cypress Test

tests/cypress/support/commands.ts
Recently failures have shown me that there might be another step where SS-HH gets caught and that is when "Add State Specific Measure" button becomes disabled. My running theory is that during the whole cypress cycle, somehow 5 SS-HH gets added (that's the max allowed) and that is why the button is disabled. This fix will remove the last added  SS-HH before trying to add a new one.
---
Cypress local and github actions needs to pass
N/A
---
---
=> Cypress SS-HH Fix 2

services/app-api/serverless.yml
Excludes the SizeRestriction_Body aws common rule that the waf plugin recently added. The rule is preventing PDF api calls from getting through.
CMDCT-3336
---
The PDF call should not error with a 403 forbidden on the deployed branch. It may still return an error if the ephem branches aren't configured for Prince, but it should at least be new and exciting. At that point, master and val should be back in business if we can remove the 403.
---
---
=> CMDCT-3336 - Disable size restriction for pdf

services/app-api/handlers/prince/pdf.ts, services/app-api/handlers/prince/tests/pdf.test.ts, services/app-api/package.json, services/app-api/yarn.lock
Resolves a security concern that a malicious user can intercept the network call containing base64 encoded HTML and insert dangerous iframes, scripts, etc that act on the downstream system. Now any received HTML is sanitized before sending downstream.
We use DOMPurify in MCR and MFP to [sanitize all api requests](https://github.com/Enterprise-CMCS/macpro-mdct-mcr/blob/main/services/app-api/handlers/handler-lib.ts#L31). May be worth considering for the future in other apps.
references:
[dompurify](https://github.com/cure53/DOMPurify)
CMDCT-3330
---
Tool for encoding/decoding base64 strings
https://examples.aswsec.com/tools/encode-decode.html#
- Add a `console.log("sanitizedBody", sanitizedBody);` on line 23 of pdf.ts
- Start QMR locally
- On the Homepage click on …
=> Purify incoming html body

services/ui-src/src/views/StateHome/AddCoreSetCards.tsx
The following text area should not be displayed for 2024 and onward:
N/A
---
- Verify that the highlighted text above isn't visible for FFY2024
N/A
---
---
=> Bug: Fix Display Logic for Core Set Text

.github/branchNameValidation.sh
The branch validation script has never worked.
The logic was wrong
if branch name not valid AND branch name longer than 64 chars
The regex was invalid
"^[a-z][a-z-0-9-]*$"
(the - between z and 0 is not valid)
It was also discovered that fully qualified function names must be less than 64 characters.  For instance, if a branch name is `test`, a service name is `database`, and a function name is `seedUsers`, the fully qualified name would be `database-test-seedUsers`.  The character limit for a branch has been set to 64 characters which won't prohibit fully qualified names from throwing errors, but is longer than Snyk and Dependabot generated branch nanes.
This PR fixes this, but it also adds the ability to filter on known reserved words.  I did some digging and wasn't able to locate a …
=> Fix branch name validation script

services/ui-src/src/measures/2024/ADDCH/data.ts, services/ui-src/src/measures/2024/shared/CommonQuestions/PerformanceMeasure/data.ts, services/ui-src/src/measures/2024/shared/CommonQuestions/PerformanceMeasure/index.tsx
Updating the `Performance Measure` description section of **ADD-CH** to include numbering as seen below:
CMDCT-3324
---
- Add child core sets
- Navigate to ADD-CH
Verify that the `Performance Measures` description matches the screenshot.
---
---
=> CMDCT-3324: ADD-CH Content Updates (FFY2024)

services/ui-src/src/measures/2024/FUMCH/data.ts, services/ui-src/yarn.lock
Removed text has been put into code segments:
Percentage of emergency department (ED) visits for beneficiaries ages 6 to 17 with a principal diagnosis of mental illness or intentional self-harm and who had a follow-up visit for mental illness. Two rates are reported: 
Percentage of ED visits `for mental illness` for which the beneficiary received follow-up within 30 days of the ED visit (31 total days)
Percentage of ED visits `for mental illness` for which the beneficiary received follow-up within 7 days of the ED visit (8 total days)
CMDCT-3331
---
Create child core set
Go to FUM-CH
Select first option in `Measurement Specification`
See text change matches the card
---
--- …
=> cmdct-3331 - text change

.env_example, services/app-api/handlers/prince/pdf.ts, services/app-api/handlers/prince/tests/pdf.test.ts, services/app-api/package.json, services/app-api/serverless.yml, services/app-api/yarn.lock, services/ui-src/yarn.lock
Instead of sending HTML to CMS's Prince instance to be rendered to PDF, send it to DocRaptor's instance.
CMDCT-3249
---
* Attempt to print a PDF
* There are two ways to do this in QMR. The big "print" button at the top of each measure page uses browser print, but the "export" option for an entire core set uses the API print. Don't do the browser print one.
* You should see a PDF
* If you don't, check your browser's address bar to see if it blocked a pop-up. That'll be it.
* The watermark on that PDF is expected
* Even though I didn't see one when I tested in this branch's environment? Maybe something to do with the DR pricing tier CMS selected.
* But I verified in DR's logs that the `test: true` parameter definitely came through, and it was counted as a test request.
There is a new …
=> Implement DocRaptor for PDF generation

tests/cypress/cypress/e2e/a11y/PPC2CHpage.spec.ts, tests/cypress/cypress/e2e/features/export_all_measures.spec.ts, tests/cypress/cypress/e2e/features/kebab_menu_measures.spec.ts, tests/cypress/cypress/e2e/features/reporting_in_FY24_tag_for_alt_data_sources.spec.ts, tests/cypress/cypress/e2e/features/submit_coreset.spec.ts, tests/cypress/cypress/e2e/init/create_delete_child.spec.ts, tests/cypress/cypress/e2e/measures/adult/PPCAD.spec.ts, tests/cypress/cypress/e2e/measures/child/ADDCH.spec.ts, tests/cypress/cypress/e2e/measures/child/PPC2CH.spec.ts, tests/cypress/cypress/e2e/measures/child/QUALIFIERS_child.spec.ts, tests/cypress/cypress/e2e/measures/healthhome/QUALIFIERS_healthhome.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/constants.ts
Currently the cypress test is looking at Reporting Year 2023. This will update cypress year to look at reporting 2024.
CMDCT-3362
---
The cypress test passes.
N/A
---
---
=> Cypress test to 2024

.github/waf-controller.sh
[The options configured for the waf-controller.sh script issue the '-u' flag for bett
](https://linuxcommand.org/lc3_man_pages/seth.html)
The options are configured as follows:  `set -o pipefail -o nounset -u`
As can be seen in the before-mentioned reference, in order to avoid attempting to process unset variables, we want to error should something not correctly be set:
`-u  Treat unset variables as an error when substituting.`
However, this produces an obtuse error message when the script's variables aren't correctly supplied: 
`./waf-controller.sh: line 11: 1: unbound variable`
In order to better inform an engineer when a build step is misconfigured, rather than the script failing to collect or set the parameters in the waf's ip-set, this pull request implements some very basic input …
=> Improve input validation

services/ui-src/src/measures/2024/rateLabelText.ts
missed from a previous PR, OEV-CH OMS needed the label updated as well
CMDCT-3332
---
2. Create child core set
3. go to OEV-CH
4. Select first radio option in Measure Specification to open up Performance Measure section
5. see text matches AC
6. Fill in a N/D/R to open the OMS section
7. See that the qualifier text says "Total ages <1 to 20 (required rate)"
N/A
---
---
=> OEV-CH Missing Label

services/ui-src/src/measures/2024/rateLabelText.ts, tests/cypress/cypress/e2e/measures/child/WCCCH.spec.ts
Change the lowercase p in:
Body mass index (BMI) percentile documentation
to uppercase p:
Body mass index (BMI) **P**ercentile documentation
CMDCT-3368
---
2. Create child measure
3. Go to CIS-CH
4. In Measure Specification section, select the first bullet
5. Scroll down to the Performance Measure
N/A
---
---
=> WCC-CH Content Change

services/ui-src/src/measures/2024/TFLCH/data.ts, services/ui-src/src/measures/2024/rateLabelText.ts, tests/cypress/cypress/e2e/a11y/TFLCHpage.spec.ts
Fun fact, TFL-CH does not have a cypress test so I added one for Accessibility.
TFL-CH has a performance measure content change to:
For FFY 2024 Child Core Set reporting, the following three rates are required: (1) Dental or oral health services: Total ages 1 through 20; (2) Dental services: Total ages 1 through 20; and (3) Oral health services: Total ages 1 through 20.
and the rate label 
Total ages 1 through 20
to
Total ages 1 through 20 **(required rate)**
CMDCT-3367
---
2. Create child measure
3. Go to CIS-CH
4. In Measure Specification section, select the first bullet
5. Scroll down to the Performance Measure
6. Check that the content update matches the jira ticket: https://jiraent.cms.gov/browse/CMDCT-3367
N/A
---
--- …
=> TFL-CH Text + Rate Label Change

services/ui-src/src/measures/2024/CDFHH/data.ts
For 2024 only: 
Percentage of enrollees age 12 and older screened for depression on the date of the encounter or 14 days prior to the date of the encounter using an age-appropriate standardized depression screening tool, and if positive, a follow-up plan is documented on the date of the `qualifying` encounter.
CMDCT-3400
---
Login as a state that has home health (stateuserMN)
make these selections:
See `Performance Measure` text appears like so:
---
---
=> cmdct-3400 tiny text change

.github/workflows/dependabot-auto-approve.yml, .github/workflows/snyk-auto-merge.yml
'Require linear history' control on the integration branch prohibits 'gh merge --merge' and requires 'gh merge --squash' in lieu.  This PR is to configure both Snyk and Dependabot jobs to be able to issue auto-merge on auto generated PRs with successfully completely checks.
CMDCT-3407
---
Hurry up and wait.  Observing PRs being automatically created and automatically merged is the only way to validate this change
---
---
=> Enable automerge for bot generated dependency fixes

services/ui-src/src/measures/2024/FUMHH/data.ts
Text change in Performance Measures for 2024:
Percentage of ED visits ~~for mental illness~~  for which the enrollee received follow-up within 30 days of the ED visit (31 total days)
Percentage of ED visits ~~for mental illness~~  for which the enrollee received follow-up within 7 days of the ED visit (8 total days)
CMDCT-3402
---
Login as stateuserMN
create Health Home Core Set
go to FUM-HH
Make these selections:
See that text matches from the description above
---
---
=> cmdct-3402 text change for FUM-HH 2024

services/ui-src/src/measures/2024/OUDHH/data.ts
Small text changes to performance measures for OUD-HH 2024
CMDCT-3403
---
Login as stateuserMN
create Health Home Core Set -> OUD-HH
Make these selections:
See that the text matches the card.
---
---
=> cmdct-3403 text change to OUD-HH

services/ui-src/src/measures/2024/IUHH/data.ts, services/ui-src/src/measures/2024/rateLabelText.ts
Text change, removal of some rates from IU-HH 2024
CMDCT-3404
---
Login as stateuserMN
Create Health Home Core Set -> IU-HH
Make these selections:
See that the text and NDR label rates match the card.
---
---
=> cmdct-3404 changes to IU-HH 2024

services/ui-src/src/measures/2024/COLHH/data.ts, services/ui-src/src/measures/2024/rateLabelText.ts
Text changes to COL-HH for 2024
CMDCT-3401
---
Login as stateuserMN
Create a Health Home Core Set
Make these selections:
See that the Performance Measures have this text and labels:
`Percentage of health home enrollees ages 45 to 75 who had appropriate screening for colorectal cancer. This measure applies to enrollees ages 46 to 75 to account for the look back period. (to ensure that the enrollee was at least age 45 for the entire enrollment period.)`
---
---
=> cmdct-3401 - COL-HH text changes

services/ui-src/src/measures/2024/FUMAD/data.ts
Text changes for FUM-AD: removed `for mental illness` from the performance measure text.
CMDCT-3395
---
2. Select Adult Measures
3. Go to FUM-AD
4. In Measure Specification section, select the first bullet
5. Scroll down to the Performance Measure
6. Check that the content update matches the jira ticket: https://jiraent.cms.gov/browse/CMDCT-3389
N/A
---
---
=> FUM-AD Content Change

services/ui-src/src/components/PrintableMeasureWrapper/index.tsx, services/ui-src/src/views/ExportAll/index.tsx
Currently, the export all page will stop rendering and provide a confusing error message if there is a measure in the database that's been removed. This fix will send an error alert message if the measure isn't there but continue rendering the pages and removing any calls to the missing measure. 
Note: i will write a cypress/unit test as part of the overall QMR refactoring, so ignore the lack of them for now.
---
1) Test this locally so that you can alter the database. Run dynamoDb:
`DYNAMO_ENDPOINT=http://localhost:8000 dynamodb-admin`
2)Open the dynamodb page, click the table [local-measures], in the table, click [Create Item]. Copy & Paste this chunk and then save it:
```
{
"createdAt": 1711115060613,
"compoundKey": "MA2024ACSFVA-AD",
"measure": "FVA-AD",
"year": 2024,
"lastAltered": …
```
=> Export Fix - Component & Cypress

services/ui-src/public/index.html, services/ui-src/src/utils/tracking/tealium.js
Corrects the url param used when in production from `production` to `prod`. This is not the same as the site_environment flag, and the two have been flipped back and forth together in the past.
CMDCT-3440
---
Only testable in production, tealium script should no longer return an empty file and a cloudfront error.
---
---
=> [CMDCT-3440] Tealium correct param

.github/audit-account.sh, .github/workflows/audit-account.yml
The purpose of this PR is to prototype a scheduled job which produces an automated report.   The report is scheduled to run once a week, on Monday morning, and will create a downloadable zip file containing four distinct CSV files.  The job also posts JSON output for each of the four reports within the build log, allowing viewing without needing to download and subsequently open the spreadsheets.
Under the hood, this report is scanning the tagging API output which returns all active resources.  Two other approaches were investigated and the result of that work can be reviewed in comments in this [ticket](https://jiraent.cms.gov/browse/CMDCT-3318).  The tagging API is a relatively new feature and allows for querying and applying tags to resources.  
In our application stack, our CI …
=> Auotmate resource auditing for account

services/app-api/handlers/prince/pdf.ts, services/app-api/handlers/prince/tests/pdf.test.ts, services/ui-src/src/views/ExportAll/util.tsx
We apply DOMPurify to print requests to avoid forwarding potentially-dangerous HTML to DocRaptor. But DOMPurify strips out rather a lot from our HTML. This PR puts some of it back.
1. DOMPurify, by default, returns only the sanitized inner HTML of the `<body>`. The outer `<html>` is restored by passing the `WHOLE_DOCUMENT` option, and the `<head>` is restored with `ADD_TAGS: ["head"]`.
2. DOMPurify removes any `<style>` tag that contains a `<` character. This is a problem because we include styles with example HTML, embedded as comments within the CSS. This is addressed by stripping out CSS comments on the browser side, before making the call to our API's print endpoint.
* This removes a few dozen CSS comments. Most are linter directives, and a few are explanations or examples. Nothing is …
=> Change styles and DOMPurify config to make PDFs look better

services/ui-src/src/labels/2021/commonQuestionsLabel.tsx, services/ui-src/src/labels/2022/commonQuestionsLabel.tsx, services/ui-src/src/labels/2023/commonQuestionsLabel.tsx, services/ui-src/src/measures/2024/PCRAD/questions/PerformanceMeasure.tsx, services/ui-src/src/measures/2024/PCRHH/questions/PerformanceMeasure.tsx, services/ui-src/src/measures/2024/shared/CommonQuestions/PerformanceMeasure/index.tsx, services/ui-src/src/shared/commonQuestions/DefinitionsOfPopulation.tsx, services/ui-src/src/shared/commonQuestions/__snapshots__/DefinitionsOfPopulation.test.tsx.snap
For FFY2024 onwards, removing the following text box from `Definition of Population Included in Measure` section of a measure:
CMDCT-3478
---
- Navigate to any measure in 2024
- Verify that the text box is not visible
N/A
---
---
---
=> CMDCT-3478: Content Removal (Global)

services/ui-src/src/labels/2021/commonQuestionsLabel.tsx, services/ui-src/src/labels/2022/commonQuestionsLabel.tsx, services/ui-src/src/labels/2023/commonQuestionsLabel.tsx, services/ui-src/src/labels/2024/commonQuestionsLabel.tsx, services/ui-src/src/shared/commonQuestions/DeviationFromMeasureSpecificationCheckboxes.test.tsx, services/ui-src/src/shared/commonQuestions/DeviationFromMeasureSpecificationCheckboxes.tsx, services/ui-src/src/shared/commonQuestions/DeviationFromMeasureSpecificationTextField.test.tsx, services/ui-src/src/shared/commonQuestions/DeviationFromMeasureSpecificationTextField.tsx
Updating verbiage from `Deviations` to `Variations` for FFY2024, as well as refactoring how these labels are displayed within each component by moving them to the `commonQuestionLabels` files. 
CMDCT-3479
---
In the FFY2024 measures, the `Deviations from Measure Specifications` section should be updated to look like this:
N/A
---
---
---
=> CMDCT-3479: Deviations -> Variations (FFY2024 Content Change)

services/ui-src/src/measures/2023/shared/globalValidations/validateAtLeastOneDataSourceType/index.test.ts, services/ui-src/src/measures/2023/shared/globalValidations/validateAtLeastOneDataSourceType/index.ts, services/ui-src/src/measures/2024/shared/globalValidations/validateAtLeastOneDataSourceType/index.test.ts, services/ui-src/src/measures/2024/shared/globalValidations/validateAtLeastOneDataSourceType/index.ts
`Update the language in the validation that flags when a state selects "Other Data Source" but doesn't enter text in the box provided. Currently, the flag says "Data Source Error: You must select a data source" which may be confusing to states because a data source has already been selected. Can you please update the flag language to say "Data Source Error: Please describe the Other Data Source"? `
CMDCT-3480
---
---
---
---
=> validation text change

services/ui-src/src/libs/spaLib.ts, services/ui-src/src/shared/coreSetByYear.tsx, services/ui-src/src/views/StateHome/AddCoreSetCards.tsx, services/ui-src/src/views/StateHome/__tests__/AddCoreSetCards.test.tsx, services/ui-src/src/views/StateHome/index.tsx
**Deploy Link**
https://d4kbxh9soszcy.cloudfront.net/
The generation of the add coreSet buttons are now being controlled in coreSetByYear.tsx file (including the text blob).
Here's the data chunk to correlate:
```
"2023": [
{
type: "coreSet",
label: "Adult",
loaded: true,
abbr: ["ACS"],
},
{
type: "coreSet",
label: "Child",
path: "add-child",
abbr: ["CCS", "CCSC", "CCSM"],
},
{
type: "coreSet",
label: "Health Home",
path: "add-hh",
abbr: ["HHCS"],
stateList: getHHStates("2023"),
},
{
type: "text",
label:
"Only one group of Adult Core Set Measures can be submitted per FFY",
},
],
```
**So what changed?**
1) **spaLib.ts** - This file wasn't suppose to be part of this PR but some spa ids did not get removed correctly last year, so its being removed now. This was the original source for …
=> Refactor AddCoreSetCards.tsx 

services/app-api/libs/kafka-source-lib.js
We create Kafka messages from AWS event streams, which can be triggered by activity in DynamoDB. Usually, the event contains both a "before" and "after" of the object - but when the event is an insert, there is no "before". That is, `event.Records[n].dynamodb.OldImage` will be `undefined`. Unless we account for this, it will cause an error when we attempt to unmarshall it.
This is a low-impact bug; subsequent updates to that record will go through just fine, because they will have an OldImage. This PR just cleans up the initial edge case.
CMDCT-3431
---
🤷‍♂️  I guess we just merge it, and then watch the logs from our postKafkaData lambda?
n/a
---
---
- ~[ ] Design: This work has been reviewed and approved by design, if necessary~ …
=> Allow for undefined OldImage in Dynamo stream events

.github/workflows/cypress-workflow.yml, .github/workflows/deploy.yml
This gave me a mild panic attack yesterday....
I found some Snyk PRs that were automerged that were indicated to have failed tests.  After playing with this quite a bit, it seems that the failures for the matrix are produced asynchronously, so a build will go green when the matrix runners fail to build, then go red a few seconds later, which was enabling PRs to merge in that interim, and in the case of Snyk PRs, they are set to auto-merge when all checks pass, so this little blip let them slip through.  
This little change just asserts that the files are identified before the cypress-workflow passes off the config to the deploy workflow.  An example of it successfully failing can be seen here:  [deploy workflow](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/actions/runs/8710353652) …
=> Assert failure on matrix when test files not present

services/app-api/types.ts, services/ui-src/src/Routes.tsx, services/ui-src/src/types.ts, services/ui-src/src/views/AddAdultCoreSet/index.test.tsx, services/ui-src/src/views/AddAdultCoreSet/index.tsx, services/ui-src/src/views/AddChildCoreSet/index.test.tsx, services/ui-src/src/views/AddHHCoreSet/index.test.tsx, services/ui-src/src/views/CoreSet/index.tsx, services/ui-src/src/views/StateHome/AddCoreSetCards.tsx, services/ui-src/src/views/index.tsx
just the route for the new adult core sets
CMDCT-3450
---
In `AddCoreSetCards.tsx`, add a new `AddCoreSetCard` component, you should see the option appear and it will take you to the new page route.
---
---
---
=> Cmdct 3450

services/ui-src/src/components/AutocompletedMeasureTemplate/index.tsx
Add word 'reporting' to text for auto-completed measures
Note: since this is a shared component it will apply to all years. Product approved ✅ 
CMDCT-3560
---
Deployed url: https://dqmq01a4f7v3s.cloudfront.net/
- Create child core sets of any flavor
- View the LRCD-CH core set
- Verify the text at the bottom has the word "reporting" added after "Core Set"
---
=> Add word 'reporting' to autocompleted measure template

services/ui-src/src/Routes.tsx, services/ui-src/src/views/CombinedRatesPage/index.test.tsx, services/ui-src/src/views/CombinedRatesPage/index.tsx, services/ui-src/src/views/StateHome/__tests__/index.test.tsx, services/ui-src/src/views/StateHome/index.tsx, services/ui-src/src/views/index.tsx
- Add route for combined-rates
- Add button to state home page to view combined rates
- Update styling (open to any better ideas here!)
- Add tests
CMDCT-3454
---
Deployed url: https://d313thmob07q2p.cloudfront.net/
- Log in as any state user
- Verify the button "View Combined Rates" shows up below the year dropdown
- Change to any year other than 2024 and verify the button goes away
- Shrink the view to mobile size and make sure the button looks okay
- Check views against [Figma](https://www.figma.com/file/AJweEUn95IZFAN3ldIcZDH/MDCT---General?type=design&node-id=2666-2508&mode=design&t=NrRav96Mrll5wRT4-4)
---
---
=> Add "View Combined Rates" button to state home page

services/ui-src/src/measures/2024/NCIIDDAD/index.tsx
content changes made:
- Add registered icon after "The National Core Indicators"
- Delete two extra **
- Add Comma between  “who receive I/DD supports, and a State of the Workforce Survey.”
CMDCT-3559
---
sentence should read: "The National Core Indicators® – Intellectual and Developmental Disabilities (NCI-IDD) provide information on beneficiaries’ experience and self-reported outcomes of long-term services and supports for individuals with intellectual and/or developmental disabilities (I/DD) and their families. NCI-IDD includes an in-person survey, family surveys for parents and guardians of adults and children who receive I/DD supports, and a State of the Workforce Survey.  For the purposes of the Adult Core Set, only data from the NCI-IDD In-Person Survey will be reported."
---
--- …
=> [QMR] NCIIDD-AD Content Change

services/ui-src/src/measures/2024/OUDAD/data.ts
Change "assistance" to "assisted"
CMDCT-3561
---
Deployed url: https://d2jnwq276p7qy.cloudfront.net/
- Navigate to Adult core sets -> OUD-AD
- Select the first radio option for "Measurement Specification"
- Scroll down and see the "Performance Measure" section
- Verify the paragraph that starts with "A total (overall) rate" says "medication assisted treatment" (instead of 'assistance')
---
=> Change text in OUD-AD

services/ui-src/src/labels/2021/commonQuestionsLabel.tsx, services/ui-src/src/labels/2022/commonQuestionsLabel.tsx, services/ui-src/src/labels/2023/commonQuestionsLabel.tsx, services/ui-src/src/labels/2024/commonQuestionsLabel.tsx, services/ui-src/src/shared/commonQuestions/AdditionalNotes.test.tsx, services/ui-src/src/shared/commonQuestions/AdditionalNotes.tsx
The Additional Notes section now shows different label text for the text area depending on if the user is reporting that measure. This only applies to 2024 and beyond.
I decided to move all of the `section` labels to objects. Even though 2021-2023 have duplicates for that text, it removes the need to check `year` in the component, and it simplifies the branching logic for the display text.
Disabled eslint for `react-hooks/exhaustive-deps` on the useEffect, which wanted to depend on `section`, because our text files won't change once deployed
CMDCT-3570
---
Deployed url: https://dsrfviz68nar1.cloudfront.net/
- Select any measure that needs information in 2024
- Verify the Additional Comments box at the end has the label
`Please add any additional notes or comments …
=> Update additional notes text area label logic

services/ui-src/src/measures/2024/FUAAD/data.ts
CMDCT-3563
---
Confirm that in FUA-AD (2024) there is a space before (SUD), so the text now says: "....principal diagnosis of Substance Use **Disorder (SUD)**, or any diagnosis..."
---
---
---
=> [QMR] FAU-AD - Add Space

services/ui-src/src/measures/2023/IETAD/data.ts, services/ui-src/src/measures/2023/IETHH/data.ts, services/ui-src/src/measures/2023/shared/CommonQuestions/PerformanceMeasure/index.tsx
As the title says, I forgot to enable the changes in IETRate for 2023. This is why the same component should not be copied over every year 😭 
CMDCT-3571
---
2) Select reporting year 2023
3) Go to IET-AD 
4) In the Measure Specification section, select the first radio button
5) Scroll down to performance measure, you should be able to enter value and trigger summation in the total categories
---
---
---
=> Forgot To Bring IETRate Changes to 2023

tests/cypress/cypress/e2e/userflow_adult.spec.ts, tests/cypress/cypress/e2e/userflow_child.spec.ts, tests/cypress/helper.d.ts, tests/cypress/support/commands.ts
Due to the addition of a deletable Adult Core Set, the cypress test have started to fail. The delete code we were using only had to worry about one core set per user as there would only be one set of deletes in the system. Because adult measures have a delete option now, if both adult and child cypress is run at the same time and is generated at the same time, it creates an issue.
We were using:  `cy.get('[data-cy="Delete"]').first().click({ force: true });` to delete the first in the stack order, but this is indifferent to whether the button is visible or not. So it didn't matter if the child menu or the adult menu was made visible, we would still delete the adult measure as that menu still exist even if it is hidden; it will usually be the first in the stack. 
Another issue is that …
=> Cypress Dropdown Fix

.github/workflows/destroy.yml, run
After merging in the destroy fix, a bug popped up because we weren't using node for destroy before, and the node upgrade made the .nvmrc file not agree with the default packaged node version on the GHA runner.  This just asserts that the destroy action uses the same version as the code base.
CMDCT-
There is no ticket, this a bush fix.
---
[Here](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/actions/runs/9083010808/job/24960739138) is proof that this fix worked.  This is a manually dispatched event using this fix against `improve-destroy` branch.
---
---
--- …
=> Nvmrc mismatch

services/ui-src/src/views/CoreSet/index.tsx, tests/cypress/cypress/e2e/userflow_healthhome.spec.ts
Complete All Measure is now enabled when Health Home core set is completed.
CMDCT-https://jiraent.cms.gov/browse/CMDCT-3550#
---
1. Log in as stateuserWA@test.com
2. Create a Health Home core set
3. Fill out all measures in core set and submit
4. 
---
---
---
=> Fix disabled submit core set on completion

services/ui-src/src/measures/2024/shared/globalValidations/validateAtLeastOneDataSourceType/index.ts
CMDCT-3630
---
For FFY 2024, go to HBD- AD --> data source section. Click "Administrative Data Other" for both **Administrative Data** and **Hybrid (Administrative and Medical Records Data)**, but do not type anything in either text box. 
Validate the measure and confirm that the new validation error message is showing up for each text box: "Data Source Error: Please describe the Administrative Other Data Source".
Also confirm that this validation error label is not affecting any other existing error message.
---
---
---
=> Global Data Source - Validation content correction

services/ui-src/src/index.scss, services/ui-src/src/measures/2024/CPUAD/data.ts, services/ui-src/src/measures/2024/CPUAD/questions/PerformanceMeasure.tsx, services/ui-src/src/measures/2024/shared/CommonQuestions/PerformanceMeasure/data.ts
Updated Performance Measure question text for CPU-AD measure
Previous
Updated Screenshot:
CMDCT- https://jiraent.cms.gov/browse/CMDCT-3622
---
1. Go to CPU-AD measure 
2. Select Measurement Specification
3. Scroll down to see Performance Measure section. (Text should be updated to look like screenshot)
---
---
---
=> CPU-AD Update Performance Measure Text Formatting 

services/ui-src/src/measures/2024/shared/CommonQuestions/PerformanceMeasure/index.tsx
The performance measure section has a textbox that went missing during a change we made. This just adds it back in.
✅ product
CMDCT-3626
---
Deploy Link: https://dy4e0cun8m9mb.cloudfront.net/
2) Select any measure, BCS-AD is the one being used in the ticket as the example
3) In the Measure Specification, select the first radio button
4) Scroll down to the performance measure section and you should see the textbox.
---
---
---
=> Global Change - Performance Measure Missing Text Box

services/ui-src/src/Routes.tsx, services/ui-src/src/components/Table/index.tsx, services/ui-src/src/hooks/api/useGetMeasures.tsx, services/ui-src/src/theme.ts, services/ui-src/src/types.ts, services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.test.tsx, services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.tsx, services/ui-src/src/views/CombinedRatesPage/index.test.tsx, services/ui-src/src/views/CombinedRatesPage/index.tsx, services/ui-src/src/views/CoreSet/index.tsx, services/ui-src/src/views/index.tsx
This PR sets up the landing page for the combined rates for the Adult and Child coresets. 
This also sets up the routes for the individual measures within the combined rates page. 
Known Issues:
1) This does not prevent manually go to combined rates route for 2023, I still need to figure out how to stop that.
2) For some reason AAB-AD goes to the measure, will fix in another branch focused on the routes
✅ Product & Design
CMDCT-3633
---
Deploy Link: https://d3u4ms57g8dvwk.cloudfront.net/
2) In reporting year 2024, select the Combined Rates button
3) You should now be able to see a table with toggles for Child & Adult Core Set
4) Click on any of them and it will take you to a route similar to, "MA/2024/combined-rates/AAB-CH" and the page should say TBD.
---
--- …
=> Combined Rates Landing Page 

services/ui-src/src/measures/2024/shared/globalValidations/validateAtLeastOneDataSourceType/index.test.ts, services/ui-src/src/measures/2024/shared/globalValidations/validateAtLeastOneDataSourceType/index.ts
There was an issue where Administrative Data sub checkboxes could be unselected after previously being selected and there would be no validation errors. 
This was happening because the `selected` array would get set from `undefined` to an array containing the checkbox. 
THEN, if you unselected the nested checkbox you had previously selected, it would set the `selected` array to an empty array and not to undefined as it was before. Therefore, on unchecking that box and setting `selected` to an empty array, it was not being caught in validation because the validation was checking for undefined. 
I added a simple fix here to also check for array lengths and if the array length is 0, it will throw an error properly. 
---
1. Navigate to any Reporting measure page
2. Under `Data Source`, select …
=> CMDCT-3692: adding validation for when selected checkbox array length is 0

services/ui-src/src/Routes.tsx, services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.test.tsx, services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.tsx
This page will display the combined rates for a QMR user that are associated with the separated or combined measures. This story only covers the initial sections (Header, Copy, Links back to the measures).
CMDCT-3637
---
1. In FFY 2024, go to the "View Combined Rates" section 
2. Click into one of the measures and make sure that the layout looks correct, specifically the header and a section with h2 and two links, one that redirects to the chip coreset measure page and another to the medicaid coreset measure page. Confirm that the links are redirecting to the correct pages.  
3. The body text is a placeholder and there's a followup ticket that will address that. 
---
---
---
_convert to a …
=> [QMR] Combined Rates Measurement Page - Initial

services/ui-src/src/views/CoreSet/index.tsx
I was passing the wrong parameter (HHCS_<random numbers> instead of HHCS) into the coreSetTitles function and it couldn't find the correct label because of that. This is a simple fix for it.
CMDCT-3723
---
1) Sign into QMR, any stateuser with HHCS (i.e. [stateuserWA@test.com](mailto:stateuserDC@test.com))
2) Add a Health Home CoreSet
3) Click it and make sure that the label on the blue banner looks says Health Homes and not undefined
N/A
---
---
---
=> Health Home Landing Page Undefined label

.github/workflows/deploy.yml, .github/workflows/unittest-workflow.yml
Our unit tests workflow was only running on `master`
Now it will run in feature branches, val, and prod as well.
It runs alongside the deploy command so there is no time spent waiting for unit tests to finish before deploying
See [this branch's deploy action](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/actions/runs/9500897568) as an example
CMDCT-3575
CMDCT-3576
---
See [this branch's deploy action](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/actions/runs/9500897568) as an example
---
=> remove unit test branch lock

run
I noticed a recent [destroy step installed serverless 4.1.0](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/actions/runs/9569334659/job/26381646603#step:8:24). Let's lock this to v3.38.0 to prevent breaking changes from affecting us until we decide if we are migrating to v4
=> Lock serverless version to 3 in run actions

services/ui-src/src/components/SupportInfo/index.tsx, services/ui-src/src/measures/2021/Qualifiers/Common/administrativeQuestions.tsx, services/ui-src/src/measures/2022/shared/Qualifiers/Common/administrativeQuestions.tsx, services/ui-src/src/measures/2023/shared/Qualifiers/Common/administrativeQuestions.tsx, services/ui-src/src/measures/2024/shared/Qualifiers/Common/administrativeQuestions.tsx
Super simple PR to capitalize Health Home in the health home qualifier questions view
---
1. Log into a state that has Health Home such as DC
2. Add a health home core set and then click on the core set
3. Click on the `Health Home Core Set Questions` link in the Core Set Qualifiers box 
4. In the Health Home Core Set Qualifiers paragraph, make sure that every instance of `Health Home` or `Health Home Program` is capitalized
5. In the Administrative Questions section, make sure that all instances of `Health Home Program` are capitalized
---
--- …
=> CMDCT-3724; CMDCT-3725: capitalizing health home program in the health home measures

services/uploads/package.json, services/uploads/src/dynamoSync/handler.js, services/uploads/src/libs/dynamodb-lib.js, services/uploads/src/libs/handler-lib.js, services/uploads/yarn.lock
Uploading combined rate data (from dynamo rate table) to mathematica s3 bucket.
Also slightly not part of the scope of this ticket, but this dynamo sync functionality has been broken since qmr switched from AWS sdk v2 to v3. This PR includes Ben's changes to fix that (thank you @benmartin-coforma)
---
1. Login to the mdct-qmr-dev AWS console, go to s3 and find the dynamosnapshot bucket for my branch (link [here](https://us-east-1.console.aws.amazon.com/s3/buckets/uploads-cmdct-3727-dynamosnapshots-024259748323?region=us-east-1&bucketType=general&tab=objects))
2. Make sure that along with `CSVmeasures` and `CSVcoreSet` you see a `CSVrate` folder in the bucket
3. Click into the `CSVrate` folder and make sure there is at least one <date>.csv file in there and that at least one timestamp is …
=> CMDCT-3727: adding rate data from dynamo table to mathematica s3 bucket

run, services/app-api/serverless.yml, services/database/serverless.yml, services/ui-auth/serverless.yml, services/ui-src/serverless.yml, services/ui/serverless.yml, services/uploads/serverless.yml, src/run.ts
The pull request introduces additional tags to each serverless service, which for the moment will largely appear as a noop change for most individuals, but it does pave the groundwork for future work items such as deploying multiple distinct projects into a single AWS account while avoiding conflicts.
But for the purpose of this PR, the main change is that destroy operations better target resources, and the `run destroy` command can now target specific services.
CMDCT-3642
---
This was tested in one environment by executing the destroy workflow against an ephem using the branch the changes were applied to.  It was also tested running from a workstation against a single service ('ui-src').
To destroy a single service, execute the following from a workstation:
`./run destroy --stage …
=> Improve resource tagging

services/ui-src/src/views/CoreSet/index.tsx
CMDCT-3775
---
1. Add a HH core set page for FFY 2024 and confirm that the banner exists. Banner should match [Figma design](https://www.figma.com/design/CaKupDWdVLgmnFZyhBSdGm/MDCT_QMR?node-id=313-2339&t=nqgSCIgA14HNsDl1-0). Info text should be: **"States with approved Health Home Programs in operation by June 30, 2023 are required to report all of the measures on the Health Home Core Set. More information on mandatory reporting requirements is included in the Initial Core Set Mandatory Reporting Guidance for the Health Home Core Sets."**
2. Confirm that the banner does not exist prior to 2024
---
---
--- …
=> Mandatory Measure Instructions - Home Health

services/ui-src/src/measures/measureDescriptions.ts, services/ui-src/src/shared/commonQuestions/CombinedRateNDR/CombinedRateNDR.tsx, services/ui-src/src/shared/commonQuestions/DataSouceInformationBanner/DataSourceInformationBanner.tsx, services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.tsx
This super simple PR contains label changes for 3 tickets:
1. CMDCT-3784: Changed "CHIP" to "Separate CHIP"
2. CMDCT-3786: Changed "Not answered" to "Not reported"
3. CMDCT-3789: Changed 2024 FUA-AD measure to capitalize the up in "Follow-Up"
---
1. Navigate to combined rates page and click into any measure for child or adult
2. Observe that any reference to CHIP now says Separate CHIP
3. Observe that anything that doesn't have a value says "Not reported" instead of "Not answered"
1. Navigate to core sets and click on Adult Medicaid
2. Scroll down to the FUA-AD measure and make sure the title has "up" capitalized in "Follow-Up"
3. Click into the measure and make sure that the title and the first question all have "Follow-Up" capitalized correctly
=> CMDCT-3784, CMDCT-3786, CMDCT-3789: updating labels for combined rates and other things

services/ui-src/src/views/ExportAll/util.tsx
This actually ended up being a pretty contained PR so I am not going to say sorry for it even though it is truly an abomination. 
Prince PDFs have a long and well known limitation that it does not recognize certain css properties like `background-color` (see [this](https://stackoverflow.com/questions/20653871/background-color-is-not-showing-in-prince-xml) stack overflow post describing the issue and solution). I understand this stack overflow post is 10 years old, but our PDFs were having the EXACT issues described in that post with certain chakra elements like radio buttons and checkboxes. Someone mentioned that you can override these styles using !important, so that's what this PR is. Any styles that aren't properly coming through are recreated in the custom prince styling that we are …
=> CMDCT-3472: adding some nightmarish manual brute force styles to pdfs

services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.tsx, services/ui-src/src/views/CombinedRatesPage/index.tsx
CMDCT-3768
---
1. Click the View Combined Rates button (top right), and confirm that the page defaults to the "Child Core Set" tab view.
2. Switch between the two tabs and confirm that the parameter in the URL changes appropriately 
3. Click a measure. When you click the back button, you should return to the child tab if you are looking at a child measure, and you should return to the adult tab if you are looking at an adult measure. There's two ways to return to this page - a) with the browser back button and b) the back arrow button in the header. Confirm that the two ways of going back result in the same experience and take you back to the appropriate tab. 
4. Confirm that there are no console errors or warnings
---
---
_If either of the following are true, notify the team's ISSO …
=> [QMR] Combined Rates - Track CoreSet Tab Selection

services/ui-src/src/labels/RateTextLabels.tsx, services/ui-src/src/shared/commonQuestions/CombinedRateNDR/CombinedRateNDR.tsx, services/ui-src/src/utils/testUtils/useApiMock.tsx, services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.test.tsx, services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.tsx
The BO's want the table in Combined Rates to display the labels of the N/D/R set the same way it is listed in the Performance Measure section. This PR will address that.
How this works is we grab the categories and qualifies from the rateLabelText of whatever year the user is looking at by doing a semi-dynamic import:
Then we build an ordered array containing the uid and do a sort to reorganize the table to match the N/D/R order in the PM section.
How the data looks in the Measure (example AMM-AD):
Currently what it's doing:
What it should look like:
CMDCT-3782
---
Deploy Link: https://d1bhfisusdxz9x.cloudfront.net/
1) Sign into QMR, any user with combined rates. i.e. [stateuser@test.com](mailto:stateuser@test.com)
2) Fill in N/D/R information for any of these measures: AMM-AD, FUM-AD, …
=> Combined Rates Page - Rates showing in wrong order

services/app-api/package.json, services/app-api/yarn.lock
`jsdom` has a downstream dependency called `ws` that had a denial of service vulnerability until a few days ago. Should be fixed in this latest version of `jsdom`. You also have to pin `ws` to v18.8.0 to match because `jsdom` only specifies `ws@^18.7.0` and `jest` has a lower version that it would otherwise also install. 
CMDCT-3845
---
Ensure no loss of functionality.
n/a
---
---
---
=> upgrade jsdom to resolve ws vulnerability

services/ui-src/src/views/CombinedRatesPage/index.tsx
Simple PR to filter out measures that should not be displayed on combined rates page and then updated helper text to reflect removed measures
---
1. On coreset page, select View Combined Rates
2. Confirm that the text under Core Set Measures Combined Rates is updated to what is in the [ticket](https://jiraent.cms.gov/browse/CMDCT-3822)
3. For Child Core Set tab, make sure that CPC-CH, LBW-CH and LRCD-CH measures are no longer displayed in the list
4. For Adult Core Set tab, make sure that CPA-AD, and NCIIDD-AD measures are no longer displayed in the list
=> CMDCT-3822: removing particular measures for combined rates page and updating helper text to reflext the removed measures

services/ui-src/src/utils/constants.ts, services/ui-src/src/views/CombinedRatesPage/index.test.tsx, services/ui-src/src/views/CombinedRatesPage/index.tsx, services/ui-src/src/views/StateHome/__tests__/index.test.tsx, services/ui-src/src/views/StateHome/index.tsx
Certain states do not have separate medicaid and chip measures so they do not need access to combined rates page. This PR removes the "View Combined Rates" button from those state coreset pages.
It also gives users from said states an unauthorized error if they happen to navigate manually to the /combined-rates page:
---
1. Log in as adminuser@test.com
2. Select any of the following states: AK, AS, DC, GU, HI, NH, NM, NC, ND, OH, PR, SC, VI, VT or WY
3. Confirm that when you get to the state coreset homepage, there is no "View Combined Rates" button
4. Navigate manually to `http://<url>/<STATE>/2024/combined-rates` and make sure that you see the unauthorized error in the screenshot above
=> CMDCT-3821: removing combined rates page for states that do not have combined rates

services/ui-src/src/views/CoreSet/index.tsx
New mandatory banner added to the top of adult coreset. @ajaitasaini did such a great job setting up the functionality for the banner that adding the language for the adult was very straightforward.
CMDCT-3855
---
Deploy Link: https://d10zdtpxg23u5l.cloudfront.net/
2) Click into the Adult CoreSet
3) Check that the mandatory banner exist, the language matches the jira ticket and the link works
N/A
---
---
---
=> Banner - Adult Core Set

services/app-api/handlers/rate/calculations/adminstrativeCalculation.test.ts, services/app-api/handlers/rate/calculations/adminstrativeCalculation.ts, services/app-api/handlers/rate/calculations/hybridCalculation.test.ts, services/app-api/handlers/rate/calculations/hybridCalculation.ts, services/app-api/handlers/rate/calculations/index.ts, services/app-api/handlers/rate/calculations/rateCalculation.ts, services/app-api/handlers/rate/calculations/types.ts, services/app-api/handlers/rate/shared/calculateAndPutRate.ts, services/app-api/test-util/testData.ts, services/app-api/types.ts, services/ui-src/src/shared/commonQuestions/CombinedRateNDR/CombinedRateNDR.tsx, services/ui-src/src/shared/commonQuestions/CombinedRateNDR/CombinedRateTypes.ts, services/ui-src/src/shared/commonQuestions/DataSouceInformationBanner/DataSourceInformationBanner.tsx
This PR contains the hybrid measure calculation used in the Combined Rates section. Despite the careful planning withe administrative calculation, we still needed to do a couple of rewrites to accommodate `HybridMeasurePopulationIncluded` field we are pulling from the measures.. Its located in the **Definition of Population Included in the Measure** section.
**New Feature**
- The Combined Rates N/D/R table will add extra rows based on whether the data source has a hybrid selected.
**Side Issue Fix**: There was an issue with CHIP data source displaying in the data source information banner. It was caused by the naming update from CHIP to Separate CHIP
CMDCT-3652
---
1) Sign into QMR, [stateuser1@test.com](mailto:stateuser1@test.com)
2) Select a Hybrid Measure to fill out, i.e. IMA-CH
Here …
=> Combine Rates - Hybrid Data Source Only 

.github/workflows/audit-account.yml
In the audit workflow, a failing first conditional produces an exit code of 1 which will cause the job to fail if it's last in line.  This has never happened, because the only step that would produce no results is ci_inactive and is not last.  This change fixes all cases regardless of execution order.  This is a tangental task for operations, does not affect the application nor the CI process, so I'm going to up my YOLO badge.
None, found during dev elsewhere.
---
---
---
---
=> Add or statement to prevent non 0 exit code if no results

services/app-api/handlers/dynamoUtils/measureList.ts, services/app-api/handlers/measures/get.ts, services/app-api/types.ts, services/ui-src/src/components/Table/columns/measures.tsx, services/ui-src/src/components/Table/types.ts, services/ui-src/src/types.ts, services/ui-src/src/views/CoreSet/index.tsx
Adding mandatory column with mandatory chip to 2024 measures
CMDCT-3854
---
1. Navigate to 2024 coreset and select any adult measure
2. Make sure that the Mandatory column is present and that there are Mandatory chips for the following measures:
```
AMM-AD
CDF-AD
FUA-AD
FUH-AD
FUM-AD
HPCMI-AD
IET-AD
MSC-AD
OUD-AD
SAA-AD
SSD-AD
```
3. Navigate back to 2024 coreset and select child measures. Make sure that every child measure has the mandatory chip
4. Do step 3 for HH measures
5. Make sure that the mandatory column is not present for years 21, 22 and 23
=> CMDCT-3854: Adding mandatory column to 2024 measures table

services/ui-src/src/measures/2024/shared/Qualifiers/data.ts
the simplest PR to update wording in qualifier under delivery system question. basically just using specific medicaid or separate chip language if they're separate
CMDCT-3644 and CMDCT-3879
---
1. For 2024, go to to adult medicaid core set qualifiers. Make sure the description under Delivery System starts with 
`As of September 30, 2023, what percentage of your Medicaid (title XIX & XXI) enrollees (age 21 and older)`
2. Go to adult chip core set qualifiers. Make sure the description under Delivery System starts with
`As of September 30, 2023, what percentage of your separate CHIP enrollees (age 21 and older)`
3. Go to child medicaid core set qualifiers. Make sure the description under Delivery System starts with
`As of September 30, 2023, what percentage of your Medicaid (title XIX & XXI) …
=> CMDCT-3644, CMDCT-3879: updating qualifier content for separate chip and medicaid

package.json, yarn.lock
Custom Lambdas are triggering warnings in security hub. These are used by the serverless framework as part of the deployment process. Upgrading to 3.39 should resolve it.
CMDCT-3898
---
Deployments succeed. Custom lambdas for cw-role || existing-s3 are on node 18, not 16.
Verified:
---
---
---
=> [CMDCT-3898] Upgrade Serverless - Custom Lambda Runtime

services/app-api/handlers/rate/calculations/hybridCalculation.ts
TLDR: For all measures where a hybrid data source is selected, users have an option to manually override the auto-calculated rate. Originally, the combined rates table was not using the manually overrode rate, it was re-calculating the rate using the numerator and denominator, which caused discrepancy between what was actually entered in the individual measure page and the combined rates table. This PR fixes that so that the combined rates table does use a manually entered rate, otherwise defaults to the auto-calculated rate. Here's an example:
For the CHIP column, the auto-calculated rate was 3.3 and 4.4 was manually entered by a user. For a manually entered rate of 4.4, the weighted rate for the column should be 1.1, not 0.8.
For the Medicaid column, the auto-calculated rate was 0 and …
=> [QMR] Combined Rates - Hybrid Nuance

services/app-api/handlers/rate/calculations/hybridCalculation.ts, services/ui-src/src/shared/commonQuestions/CombinedRateNDR/CombinedRateNDR.tsx, services/ui-src/src/shared/commonQuestions/CombinedRateNDR/CombinedRateTypes.ts
If one source uses hybrid data, and another source uses admin data, the current state of the app is that there will be an MEP for hybrid and no MEP for admin. This will in turn not have a weighted rate calculation in combined rates. This needed to be updated so that if admin source does not have MEP, we instead use the denominator to calculate weighted rate.
Before:
After:
Questions to ask David:
1.  do we allow users to enter MEP for admin data source and should we calculate weighted rate with that user entered MEP
2. do we want to support a 0 MEP value
CMDCT-3903
---
1. Find a medicaid measure with total measure eligible population (an adult one is CBP-AD and a child one is IMA-CH) and fill it out using a Data Source type of Hybrid. make sure to fill in the total measure eligible …
=> CMDCT-3903: if one admin and one hybrid data source, make sure admin mep uses denominator to calculate weighed rate

services/ui-src/src/shared/commonQuestions/DefinitionsOfPopulation.tsx
Super simple PR to update options for coresets that don't have separate medicaid and chip measures
CMDCT-3929
---
1. Log in as a user with state that doesn't have separate coresets for medicaid and chip (such as stateuserDC)
2. Navigate to adult coreset and click on any measure and scroll to Definition of denominator section and make sure it matches the updates noted in the [ticket](https://jiraent.cms.gov/browse/CMDCT-3929)
3. repeat step 2 with the child coreset
=> CMDCT-3929: making definition of denom text changes for not separated coresets

services/ui-src/src/measures/2024/shared/globalValidations/validateNDRTotalsMatchSum/index.test.ts, services/ui-src/src/measures/2024/shared/globalValidations/validateNDRTotalsMatchSum/index.ts
When the numerators don't sum properly, update the validation language to:
-  "The numerators for each diagnosis cohort should sum to the total SUD numerator." 
When the denominators don't sum properly, update the validation language to: 
- "The denominators for each diagnosis cohort should sum to the total SUD denominator."
CMDCT-3931
---
N/A
---
---
=> QMR - Additional Validation Content Change for IET-AD

services/ui-src/src/labels/2021/commonQuestionsLabel.tsx, services/ui-src/src/labels/2022/commonQuestionsLabel.tsx, services/ui-src/src/labels/2023/commonQuestionsLabel.tsx, services/ui-src/src/labels/2024/commonQuestionsLabel.tsx, services/ui-src/src/shared/commonQuestions/DefinitionsOfPopulation.tsx
This is gross and I hate it. Basically adding a healthHomeQuestion label to 2024 labels and rendering that if it exists and is a health home measure. otherwise rendering the question
CMDCT-3918
---
1. Navigate to user with HH measures (DC is one)
2. Click into any health home measure and make sure that the "Does this denominator represent..." question has the same wording that is requested in the [ticket](https://jiraent.cms.gov/browse/CMDCT-3918)
3. Click into any adult measure and make sure the "Does this denominator represent..." question does not reference health home
=> CMDCT-3918: adding gross ternary to render health home question

services/ui-src/src/measures/2024/CPAAD/questions/WhyDidYouNotCollect.tsx, services/ui-src/src/measures/2024/MSCAD/index.tsx, services/ui-src/src/measures/2024/MSCAD/questions/HowDidYouReport.tsx, services/ui-src/src/measures/2024/MSCAD/questions/Reporting.tsx, services/ui-src/src/measures/2024/MSCAD/validation.ts
For MSC-AD if the user selects no on the first question we should be showing them the same options as when a user decides to not report a measure, Including the questions currently nested under "no" on the second question.
- Fix behavior when a user is not reporting
- Move nested questions out of "no" option in question 2
CMDCT-3926
---
Deploy link: https://d1iqzk6i53axpx.cloudfront.net/
1. Sign into QMR, with stateuser1@test.com
3. Click on Adult Core Set Measures: Medicaid (Title XIX & XXI) and/or Adult Core Set Measures: Separate CHIP
4. Click on MSC-AD measure
5. Select No for "Did you collect this measure?"
6. Click "Validate Measure" button & this should prompt an error
7. Select an option for question: "Why are you not reporting on this measure?"
8. Click "Validate Measure" button …
=> CMDCT-3926 - MSC-AD Question Order

services/ui-src/src/measures/2024/shared/Qualifiers/data.ts
The tiniest content update. 
Remove the word "optional" from the banner for Child Core Set Qualifiers.
CMDCT-3942
---
Deploy Link: https://d2bhc7t034vv5w.cloudfront.net/
1. Sign into QMR, with stateuserWA@test.com and/or stateuser1@test.com
2. Click on `Child Core Set Measures: Medicaid (Title XIX & XXI)`
3. Click on `Child Core Set Questions: Medicaid (Title XIX & XXI)`
4. Confirm `(optional)` is removed from the following sentence: 
> 1. Delivery System
> As of September 30, 2023, what percentage of your Medicaid (Title XIX & XXI) enrollees (under age 21) were enrolled in each delivery system (optional)?
---
=> [QMR] Remove content - Child core set qualifiers 

services/ui-src/src/measures/2024/CPAAD/index.tsx, services/ui-src/src/measures/2024/CPAAD/questions/DefinitionOfPopulation.tsx, services/ui-src/src/shared/commonQuestions/DefinitionsOfPopulation.tsx
CPA-AD needs custom definition of denominator options and helper text. I did this by adding custom options to the CPA-AD index file and passing them in as an optional prop to DefinitionsOfPopulation common component. Then either render the prop or default coreset specific ones. Thanks to @ailZhou for that solution!
CMDCT-3928
---
1. Login as user with separate medicaid and chip coresets
2. Navigate to adult medicaid and to the CPA-AD measure
3. Make sure that the text under "Definition of Denominator" matches what is in the [ticket](https://jiraent.cms.gov/browse/CMDCT-3928)
4. Repeat steps 2 & 3 for adult chip
=> CMDCT-3928: Adding specific language to definition of denom for CPA-AD measure because why not

services/ui-src/src/components/MeasureWrapper/index.tsx, services/ui-src/src/shared/coreSetByYear.tsx
The BOs want the breadcrumb bar to display a different title for separated Adult and Child CoreSet so that it's more clear if they are looking at a Medicaid or a Chip measure. 
The descriptive long time is now added to the measure page itself, under the breadcrumb bar.
CMDCT-3937
---
Deploy Link: https://d31k45qp5ojk8b.cloudfront.net/
1) Sign into QMR, any separate coreSet users i.e. [stateuser1@test.com](mailto:stateuser1@test.com) 
2) In reporting year 2024, go to any adult or chip measure
3) The title will look like this if the measure's program type is _Medicaid_
- and like this for _CHIP_
4) Check that the other years and non-split coreSets still have the old style title
---
---
--- …
=> Measure Header Updates 

services/ui-src/src/labels/2024/commonQuestionsLabel.tsx, services/ui-src/src/shared/commonQuestions/CombinedRates.test.tsx, services/ui-src/src/shared/commonQuestions/CombinedRates.tsx, tests/cypress/cypress/e2e/userflow_adult.spec.ts, tests/cypress/cypress/e2e/userflow_child.spec.ts, tests/cypress/cypress/e2e/userflow_healthhome.spec.ts, tests/cypress/helper.d.ts, tests/cypress/support/commands.ts
CMDCT-3930
---
1. Add Health home core set for 2024
2. Pick a HH measure, fill it out and confirm that the "Combined Rate(s) from Multiple Reporting Units" section does not display (more details about how the section looks is in the ticket) 
3. Check other reporting years and confirm section exists for 2021,2022, and 2023
---
---
---
=> Remove Combined Rate(s) Question From Measures (Health Home)

services/app-api/handlers/rate/rateNDRCalculations.test.ts, services/app-api/handlers/rate/rateNDRCalculations.ts
For certain measures with multiple age group qualifiers, CMS uses unique calculations for combining the rates. Our calculated combined rates do not match theirs, for those individual qualifiers. However, ours _do_ match theirs for the "total" qualifiers on those measures.
Since our final, total combined rates are correct, the most expedient fix is to hide those intermediate, individual rates. We will skip the calculation, and therefore they will not display on the Combined Rates page.
This applies to DEV-CH and WCC-CH.
CMDCT-3946
CMDCT-3947
---
1. Fill out individual medicaid and chip measures for DEV-CH
2. Look at the combined rates page. Note that only the "total" rate is present.
3. Repeat for WCC-CH. Note that only the three "total" rates (one per category) are present.
n/a
---
- ~[ ] …
=> Skip combined rate calculations for DEV-CH and WCC-CH age groups

services/ui-src/src/labels/2023/commonQuestionsLabel.tsx, services/ui-src/src/labels/2024/commonQuestionsLabel.tsx, services/ui-src/src/shared/commonQuestions/PerformanceMeasure/index.test.tsx, services/ui-src/src/shared/commonQuestions/PerformanceMeasure/index.tsx
There was an issue seeing period of health emergency text that is controlled by a launch darkly flag. This text is only visible in a hybrid measure. 
So what happened is the year was not being returned when using `useParams()` so I switched it over to `usePathParams()`
The BO's also wanted the text updated for 2024. So it should look like this now under the performance measure.
---
Deploy Link: https://dggnsm7sl3vbr.cloudfront.net/
2) Go to CCS-AD (a hybrid measure)
3) Select the first radio button in the **Measurement Specification** section
4) Scroll down to the **Performance Measure** section
5) The text from the image above should be displayed
---
---
--- …
=> PHE Flag Text Update

services/ui-src/src/shared/commonQuestions/OptionalMeasureStrat/NDR/ndrSets.tsx
There was an unexpected bug in IU-HH which was causing the render to error out. `ageGroupOptions` object somehow got into the render and it is not suppose to be there. Might have been a merge issue, might have been a refactoring error, who knows.
---
1) Sign into QMR, [stateuserWA@test.com](mailto:stateuserDC@test.com)
2) Add a Health Home CoreSet
3) Go to IU-HH, fill out: 
- Measure Specification - Select the first radio button
- Performance Measure - Fill out an N/D/R set that is not the total
- Optional Measure Stratification - Fill out any of them
4) Save
If you were able to fill out OMS without the page turning white, that means the bug is fixed.
---
---
---
_convert to a different …
=> [BUGFIX] IU-HH OMS Render Bug

.env.tpl, services/database/scripts/transformMeasureTable.ts
The DB migration script for the measures table was failing when coming across bad measure data in dev that doesn't have fields for state, year and measure. Since the new `measure` table requires a `measure` field as the sort key, it could not create a new item so the script would fail and only part of the data would be properly migrated.
The fix here is if those fields don't exist for a particular measure, I extract all those fields out of the compoundKey because the compoundKey for the old measures table """""SHOULD"""" always have all 4 concated together (like `AL2024ACSMAAB-AD`). @ailZhou or @benmartin-coforma can correct me if I am wrong about the compoundKey being guaranteed to always have all 4 values. If it's not somehow guaranteed, then this script needs to further revised to …
=> [NO TICKET]: updating transform measure table script to handle missing state, year, measure fields

services/ui-src/public/browserconfig.xml, tests/cypress/package.json, tests/cypress/yarn.lock
@benmartin-coforma confirmed that while previously we had discovered `browserify` was a dependency for cypress tests, that removing them shouldn't affect cypress from working. It turns out, the tests are still passing after successfully removing the browserify package and devDependencies. As long as we don't need `cypress-tags`, we should be good to push this update.
CMDCT-3856
---
commands ran to confirm browserify removed
- Confirming dependencies so that `yarn install` doesn't re-install `browserify`
`yarn why browserify`
`yarn why cypress-tags`
`yarn remove cypress-tags`
`yarn remove browserify`
- To confirm no lingering dependencies
`grep browserify yarn.lock`
- Clean up `node_modules` and ensure consistency across `package.json` and `yarn.lock` files
`yarn install --check-files`
=> [QMR] CMDCT-3856 Remove browserify

services/ui-src/src/components/DateRange/index.tsx
A fix for the issue with 2023+ date pickers where the component rendering is being half hidden due to it being layered as a child of the radio button.
CMDCT-3873
---
Deploy Link: https://d7i4tmshon0x.cloudfront.net/
2) Go into any measure that has the Date Range section
3) Select "No, our state used a different measurement period." to open up the date picker
4) Use the date picker to select the month of reporting, make sure there's no issue with the rendering of the date picker component.
N/A
---
---
---
=> Date Picker Rendering

services/ui-src/src/components/ComplexRate/index.tsx, services/ui-src/src/components/MeasureWrapper/index.tsx, services/ui-src/src/components/Rate/index.tsx, services/ui-src/src/components/Table/columns/measures.tsx, services/ui-src/src/hooks/api/useGetCoreSets.tsx, services/ui-src/src/shared/Qualifiers/deliverySystems.tsx, services/ui-src/src/shared/commonQuestions/DateRange.test.tsx, services/ui-src/src/shared/commonQuestions/DateRange.tsx, services/ui-src/src/shared/commonQuestions/OptionalMeasureStrat/omsNodeBuilder.tsx, services/ui-src/src/shared/commonQuestions/PerformanceMeasure/index.tsx, services/ui-src/src/shared/coreSetByYear.tsx, services/ui-src/src/shared/globalValidations/ComplexValidations/ComplexValidateDualPopInformation/index.tsx, services/ui-src/src/shared/globalValidations/validateDeviationTextFieldFilled/index.ts, services/ui-src/src/shared/globalValidations/validateDualPopInformation/index.ts, services/ui-src/src/utils/featuresByYear.ts, services/ui-src/src/utils/getLabelText.tsx, services/ui-src/src/utils/typing.ts, services/ui-src/src/views/CoreSet/index.tsx, services/ui-src/src/views/StateHome/__tests__/index.test.tsx, services/ui-src/src/views/StateHome/helpers.ts, services/ui-src/src/views/StateHome/index.tsx
Instead of checking what year it is and rendering something for that year like:
```
if (year >= 2024) { 
// render something specific to years 2024 and beyond
}
```
we want to create a `featuresByYear` file that has a bunch of functions. These functions do the same exact year check, except the value add is that they document the feature. So for example for showing the combined rates button for years 2024+, instead of doing that year check (if year >= 2024, render combined rates button), we have a function in the featuresByYear folder that is called `hasCombinedRates` or something. Then that function returns year >= 2024, but when we call it in app, we'll call `featuresByYear.hasCombinedRates` which will document the feature and will make it easier to read and figure out what the code is …
=> CMDCT-3883: Adding a featuresByYear that will replace year checks around the application

.env.tpl, services/app-api/serverless.yml, services/database/serverless.yml
This is the cleanup work involved with all the table rekeying we did last month. Just removing the old tables that aren't being used anymore. 
CMDCT-4101
---
https://dvvnje2vq4dct.cloudfront.net/
No functionality changes. Just a general smoke test to make sure everything looks good.
=> CMDCT-4101: removing unused measures, coreSets and rates tables

README.md, services/ui-src/src/components/AutocompletedMeasureTemplate/index.test.tsx, services/ui-src/src/components/AutocompletedMeasureTemplate/index.tsx, services/ui-src/src/components/MeasureWrapper/index.tsx, services/ui-src/src/components/SubmitCoreSet/index.test.tsx, services/ui-src/src/components/SubmitCoreSet/index.tsx, services/ui-src/src/components/Table/columns/measures.tsx, services/ui-src/src/labels/2025/commonQuestionsLabel.tsx, services/ui-src/src/measures/2025/CPAAD/questions/Reporting.tsx, services/ui-src/src/measures/2025/CPCCH/questions/Reporting.tsx, services/ui-src/src/measures/2025/MSCAD/questions/HowDidYouReport.tsx, services/ui-src/src/measures/2025/MSCAD/questions/Reporting.tsx, services/ui-src/src/measures/2025/OEVCH/data.ts, services/ui-src/src/measures/2025/TFLCH/data.ts, services/ui-src/src/shared/Qualifiers/Common/costSavingsData.tsx, services/ui-src/src/shared/commonQuestions/AdditionalNotes.test.tsx, services/ui-src/src/shared/commonQuestions/NotCollectingOMS.test.tsx, services/ui-src/src/shared/commonQuestions/NotCollectingOMS.tsx, services/ui-src/src/shared/commonQuestions/Reporting.test.tsx, services/ui-src/src/shared/commonQuestions/Reporting.tsx, services/ui-src/src/utils/featuresByYear.ts, services/ui-src/src/views/AddAdultCoreSet/index.tsx, services/ui-src/src/views/AddChildCoreSet/index.tsx, services/ui-src/src/views/AddHHCoreSet/index.tsx, services/ui-src/src/views/AddStateSpecificMeasure/index.tsx, services/ui-src/src/views/CombinedRatesPage/CombinedRatesMeasure.tsx, services/ui-src/src/views/CombinedRatesPage/index.tsx, services/ui-src/src/views/CoreSet/index.tsx, services/ui-src/src/views/StateHome/index.tsx
Created one of those featureByYear flag things that will not display "FFY" string when the year is 2025 or beyond. 
CMDCT-4034
---
https://djh52euni05mh.cloudfront.net/
1. Go around 2025 and make sure there is no mention of `FFY 2025` (you will see some instances of `FFY 2024` and that is ok and expected)
2. Make sure all other years do have FFY displayed
=> CMDCT-4034: Removing FFY language for 2025

services/ui-src/src/labels/2023/commonQuestionsLabel.tsx, services/ui-src/src/labels/2024/commonQuestionsLabel.tsx, services/ui-src/src/labels/2025/commonQuestionsLabel.tsx, services/ui-src/src/measures/2021/SSHH/index.test.tsx, services/ui-src/src/measures/2022/SSHH/index.test.tsx, services/ui-src/src/measures/2023/CPAAD/questions/WhyDidYouNotCollect.tsx, services/ui-src/src/measures/2023/SSHH/index.test.tsx, services/ui-src/src/measures/2023/SSHH/questions/PerformanceMeasure.tsx, services/ui-src/src/measures/2024/CPAAD/questions/WhyDidYouNotCollect.tsx, services/ui-src/src/measures/2024/SSHH/index.test.tsx, services/ui-src/src/measures/2024/SSHH/questions/PerformanceMeasure.tsx, services/ui-src/src/measures/2025/CPAAD/questions/WhyDidYouNotCollect.tsx, services/ui-src/src/measures/2025/CPCCH/questions/WhyDidYouNotCollect.tsx, services/ui-src/src/measures/2025/SSHH/index.test.tsx, services/ui-src/src/measures/2025/SSHH/index.tsx, services/ui-src/src/measures/2025/SSHH/questions/PerformanceMeasure.tsx, services/ui-src/src/shared/commonQuestions/PerformanceMeasure/index.test.tsx, services/ui-src/src/shared/commonQuestions/PerformanceMeasure/index.tsx, services/ui-src/src/shared/commonQuestions/WhyAreYouNotReporting.test.tsx, services/ui-src/src/shared/commonQuestions/WhyAreYouNotReporting.tsx, services/ui-src/src/utils/featuresByYear.ts, services/ui-src/tsconfig.json
2025 measures shouldn't have any reference to COVID related questions. This is a PR to remove them from 2025.
I also removed all instances of the periodOfEmergency feature flag as per request of the ticket
CMDCT-4084
---
1. Log in as any user
2. Make sure that in the hybrid measures for 2025, there are no COVID related questions (see [ticket](https://jiraent.cms.gov/browse/CMDCT-4084) for list of measures that are hybrid)
3. Make sure there is no "Limitations with data collection, reporting, or accuracy due to the COVID-19 pandemic" option for why did you not report
4. Make sure for all other years, the same covid questions and options are present
=> CMDCT-4084: removing covid language from 2025

services/ui-src/src/components/SupportInfo/index.tsx
There were only two links i could find using the axe DevTools extension that were problematic. I added underlines and now I am not getting accessibility warnings. 
The rest of the links referenced in [this](https://docs.google.com/document/d/1YeCDzSYFkoudim5f3YyjsDidkPsP_xicr6H6nU50sqg/edit?tab=t.0) accessibility write-up do not give me errors so not exactly sure what is expected there.
CMDCT-3979
---
1. Install the axe DevTools chrome extension
2. Click around all the pages in all years and do a "Full Page Scan" on each page
3. Make sure on each page, there are no errors involving colors/contrasts of links
=> CMDCT-3979: adding underline to link so that accessibility warning goes away

services/ui-src/src/hooks/authHooks/userProvider.tsx
Garrett and I have been working on the Amplify logout issues and we think its because the call get cancelled due to the redirect happening. Amplifys signout seems to handle this redirect just fine with out it, so we're hoping by just removing that line the logout issue will be fixed!
---
**You'll need to do this in the dev environment after this PR is merged**
Sign into QMR with IDM
Click logout in the application
Wait until you're in the IDM site and log out of that too
Navigate to mdctqmrdev.cms.gov
Click sign into QMR with IDM
If you were taken to the login screen to input your username and password, it worked!
If you were taken directly into the application, it did not work :(
=> Amplify V6: Remove window.location call in logout to stop cancelling cognito call

services/ui-src/src/measures/2025/EDVAD/data.ts, services/ui-src/src/measures/2025/EDVAD/index.test.tsx, services/ui-src/src/measures/2025/EDVAD/index.tsx, services/ui-src/src/measures/2025/EDVAD/validation.ts, services/ui-src/src/measures/2025/index.tsx, services/ui-src/src/measures/2025/rateLabelText.ts, tests/cypress/support/constants.ts
This PR creates the page for EDV-AD. It is copied over from OEV-CH and I stripped out any information that was related to OEV-CH.
According to Cam, any performance measure and rateLabelText data will come at a later time.
CMDCT-4045
---
2) In reporting year 2025, select any Adult Core Set Measures
3) Go to EDV-AD and fill out the form.
4) If the form page works as normal, we are good
---
---
---
=> New Measure Page: EDV-AD

services/app-api/handlers/dynamoUtils/measureList.ts, services/ui-src/src/measures/2025/LRCDAD/index.test.tsx, services/ui-src/src/measures/2025/LRCDAD/index.tsx, services/ui-src/src/measures/2025/index.tsx, tests/cypress/cypress/e2e/userflow_adult.spec.ts, tests/cypress/support/constants.ts
This PR creates the page for LRCD-AD It is copied over from LRCD-CH and I stripped out any information that was related to OEV-CH.
According to Cam, any performance measure text and rateLabelText data will come at a later time.
CMDCT-4042
---
2) In reporting year 2025, select any Adult Core Set Measures
3) Go to LRCD-AD  and see that it's an autocompleted measure
4) There should be no form fill on the page. It is missing text, that's suppose to come later
---
---
---
=> New Measure Page: LRCD-AD

services/ui-src/src/measures/2025/OEVPAD/data.ts, services/ui-src/src/measures/2025/OEVPAD/index.test.tsx, services/ui-src/src/measures/2025/OEVPAD/index.tsx, services/ui-src/src/measures/2025/OEVPAD/validation.ts, services/ui-src/src/measures/2025/OEVPCH/data.ts, services/ui-src/src/measures/2025/OEVPCH/index.test.tsx, services/ui-src/src/measures/2025/OEVPCH/index.tsx, services/ui-src/src/measures/2025/OEVPCH/validation.ts, services/ui-src/src/measures/2025/index.tsx, services/ui-src/src/measures/2025/rateLabelText.ts, tests/cypress/support/constants.ts
Since OEVP-AD & OEVP-CH is the same atm, I decided to do them both together, and also cut down on the merge conflicts. 
It is copied over from OEV-CH and I stripped out any information that was related to OEV-CH.
According to Cam, any performance measure and rateLabelText data will come at a later time.
CMDCT-4044
CMDCT-4049
---
2) In reporting year 2025, select any Adult Core Set Measures
3) Go to OEVP-AD and fill out the form.
4) If the form page works as normal, we are good
5) Repeat for OEVP-CH
---
---
--- …
=> New Measure Page: OEVP-AD & OEVP-CH

services/ui-src/src/measures/2025/CPAAD/index.tsx, services/ui-src/src/shared/commonQuestions/DefinitionsOfPopulation.tsx
For CPA-AD, the BOs want the **deliver systems** question in the **Definition of Population Included in the Measure** section removed. This PR will add a boolean prop to control the showing/hiding of that question.
CMDCT-4201
---
2) In Reporting year 2025, go to CPA-AD
3) Scroll down to the **Definition of Population Included in The Measure** section and check that the question "Which delivery systems are represented in the denominator?" is not being rendered.
---
---
---
=> CPA-AD Remove question

services/ui-src/src/labels/2025/commonQuestionsLabel.tsx, tests/cypress/cypress/e2e/userflow_admin.spec.ts
This PR adds an extra line to **Definition of Population Included in the Measure** -> **Definition of denominator**. When you select Other, it will now have the added text _(text in this field is included in publicly-reported state-specific comments)_
CMDCT-4204
---
2) In reporting year 2025, select any measure
3) Scroll down to **Definition of Population Included in the Measure** section.
4) Select the Other checkbox and see that the text exist.
N/A
---
---
---
=> Global - Definition of Denominator Update

.github/workflows/destroy.yml, services/output.sh, services/uploads/serverless.yml
See this description:
https://github.com/Enterprise-CMCS/macpro-mdct-qmr/pull/2536#issue-2773307466
The only thing of note here is adding --raw-output to the jq call so that there is no quotes in the env variable which causes playwright problems. This came up while upgrading HCBS and so I'd like it fixed here so that we don't have it come back up when we add playwright to seds and it just keeps the files matching across repos which is a nice to have.
I also snuck in a removal of the env variable for serverless v4 since @JonHolman correctly pointed out does nothing.
=> CMDCT-4105 - adds raw output to jq for consistency and non-breaking when we add playwright

services/ui-src/src/components/KebabMenu/index.tsx, services/ui-src/src/shared/types/MeasureTemplate.tsx
Ignore the branch name, I forgot to rename it when I pushed it and that's on me.
This PR fixes the issues with the Delete Modal hanging after you press the delete button. The issue was caused by the fact that we deleted the flow from the process (hence the text is missing) but we never called the chakra command to close the modal so the render stayed while the text was removed.
The issue makes the modal look like this:
CMDCT-4192
---
2) Select reporting year 2022
3) Add Child Core Set, you can choose either combined or multiple
4) In the Core Set Actions menu, select [Delete]
5) A modal will pop up. Follow the instructions to Delete Core Set
6) It should delete with no render issues.
---
---
_If either of the following are true, notify the team's ISSO …
=> [CMDCT-4192] Core Set Delete Modal Render

.github/workflows/destroy.yml
Quick fix to QMR to allow destroy to work via github action
CMDCT-4303
---
NA
NA
---
---
---
=> CMDCT-4303 - destroy needs serverless key for QMR

services/app-api/handlers/rate/migratePqiMiscalculations.ts, services/app-api/handlers/rate/rateNDRCalculations.test.ts, services/app-api/handlers/rate/rateNDRCalculations.ts, services/app-api/libs/dynamodb-lib.ts, services/app-api/types.ts
This PR addresses an issue introduced by PR #2386.
Context: PQI rates differ from most. Rather than a percentage, the rate is displayed as per hundred thousand. Prior to the refactor in 2386, our combined rate code would use the 100k multiplier if the first three letters of the measure abbreviation were PQI. After my refactor, we only use that multiplier if the measure abbreviation is `PQI-AD` exactly. Unfortunately, there is no such measure. There are actually _four_ PQI measures: `PQI01-AD`, `PQI05-AD`, `PQI08-AD`, and `PQI15-AD`. This is now reflected in the code.
Since that refactor was done after UAT testing had begun, but before the feature went live, all existing combined rates for PQI measures in production are incorrect. Thus, this PR also contains a migration to recalculate all …
=> PQI Combined Rates fix

services/app-api/handlers/prince/pdf.ts, services/app-api/serverless.yml
Update the serverless build config to make `jsdom` happy. This fixes our issue with PDF rendering.
See the [ServiceNow ticket](https://cmsitsm.servicenowservices.com/now/nav/ui/classic/params/target/sn_customerservice_case.do%3Fsys_id%3D0e55b2d0975ca6d09260f21de053afff%26sysparm_view%3Dcase%26sysparm_domain%3Dnull%26sysparm_domain_scope%3Dnull) for the user report.
See the [Slack thread](https://coforma.slack.com/archives/C038M9GDA5T/p1741790543385289) for our discussion.
CMDCT-
---
https://d3hldhccohvxve.cloudfront.net/
1. Log in. I think either state user or admin would work. State user is slightly more convenient, so that's what I used.
2. When viewing the core sets for a year, click the triple-dot menu at the right end of the table
3. Choose "Export", and I think you have to, like, …
=> Fix issue with PDF endpoint

services/ui-src/src/views/ExportAll/util.tsx
A long time ago, I did some horrible stuff to brute force some css for pdf export since prince pdf has all sorts of issues and limitations with chakra elements. I did this by inspecting the checkbox and radio elements in the html pdf export page, grabbing the css class names (usually in the format of css-1jbejj2 or whatever) and then setting css manually in the util.tsx that you see in this PR. Well, chakra updates caused chakra css classes to change. Since the pdf export needs to override the chakra css and is grabbing the specific checkbox and radio css class names, I am updating the changed chakra classes to reflect the new classes.
This PR and my initial work to fix PDF ([here](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/pull/2316)) should be referenced any time qmr pdfs have a …
=> CMDCT-4420: fixing pdf display regressions after chakra updates

.github/workflows/destroy.yml
Serverless needs to be prompted to remove stacks that aren't there anymore.
CMDCT-4469
---
I did the test but you have to be using AWS for qmr creds and then `serverless usage` and see the stacks that you've created. Then destroy them using the github action and then do another `serverless usage` and see that they are no longer listed.
NA
---
---
---
=> CMDCT-4469 - adds serverless reconcile so the serverless accounting is correct

.github/workflows/git-secrets.yaml
**Per Garrett via this [ticket](https://github.com/Enterprise-CMCS/macpro-mdct-mcr/pull/12140):**
> The latest version of gitleaks is failing in our checks. There was a [change to the allowlist](https://github.com/gitleaks/gitleaks/pull/1777) settings that is causing ours to fail. 
> 
> In the future we can look into this more, or perhaps move back to latest when it's fixed. For now lets make sure these pass and not get used to ignoring them.
> 
> Docs:
> [gitleaks changelog](https://github.com/gitleaks/gitleaks/releases)
> [DockerHub gitleaks tag list](https://hub.docker.com/r/zricethezav/gitleaks/tags)
> 
---
- Verify gitleaks [passed](https://github.com/Enterprise-CMCS/macpro-mdct-mcr/actions/runs/14755875284/job/41423830609) with the locked version `v8.24.3`
- Verify gitleaks …
=> [QMR] Fix gitleaks

services/ui-src/src/measures/2025/CPCCH/questions/DefinitionOfPopulation.tsx
A quick fix for CPC-CH definition of population saving the wrong value. Cam says the mathematica does not need us to do an ETL for 2024, we just need to change this for 2025.
CMDCT-4459
---
Deploy Link: https://d3vojqyglu3p0t.cloudfront.net/
---
---
---
=> CPC-CH - Medicaid storing for Separate CHIP

services/ui-src/src/measures/2025/OEVCH/data.ts, services/ui-src/src/measures/2025/rateLabelText.ts
Performance Measure Question Text:
- Replace "ages < 1 to 20" --> "(<Age 21)"
Rate categories:
- Replace "Age <1" & "Ages 1 to 2" --> "Age < 3"
- Replace "Ages 6 to 7", "Ages 8 to 9", "Ages 10 to 11" & "Ages 12 to 14" --> "Ages 6 to 14" 
- Replace "Ages 15 to 18" & "Ages 19 to 20" --> "Ages 15 to 20" 
- Replace "Total ages <1 to 20 (required rate)" --> "Total (< Age 21) (required rate)"
Optional Measure Stratification rate label:
- Automatically updates from above change to rate ranges --> "Total (< Age 21) (required rate)"
CMDCT-4409
---
**Deploy Link:** https://do809kyukddsm.cloudfront.net/
1. Login with any state user
2. Select any Child Core Set for 2025
3. Select OEV-CH to confirm change
4. Scroll to "Measurement Specification" question and select "American Dental Association/Dental …
=> [QMR] OEV-CH Update

services/ui-src/src/measures/2025/OEVPAD/data.ts, services/ui-src/src/measures/2025/rateLabelText.ts
updating performance measure question and rate label text for OEVP-AD
CMDCT-4434
---
cloudfront link: https://dbt3tdm9w15ho.cloudfront.net/
1. Log in as any user
2. Navigate to 2025 adult measures and go to OEVP-AD
3. Make sure that under Performance Measure you see "Percentage of enrolled persons ages 21 to 44 with live-birth deliveries in the measurement year who received a comprehensive or periodic oral evaluation during pregnancy."
4. Also make sure you see "Ages 21 to 44" as the rate label
=> CMDCT-4434: OEVP-AD 2025 updates

services/ui-src/src/measures/2025/OUDHH/data.ts, services/ui-src/src/measures/2025/rateLabelText.ts
CMDCT-4411: updating rate labels for TFL-CH
CMDCT-4413: updating wording and measure steward for OUD-HH
CMDCT-4411, CMDCT-4413
---
cloudfront link: https://d2utz4njmp68fo.cloudfront.net/
CMDCT-4411 test:
1. Log in as any QMR user
2. Navigate to 2025 child measures and go to TFL-CH
3. Observe that the measure rates under Performance measure section now have the groups: 1-2, 3-5, 6-14, 15-20 and 1-20 total
CMDCT-4413 test:
1. Log into state with HH measures such as DC
2. Navigate to 2025 child measures and go to OUD-HH
3. Observe that the measure steward (first option under Measurement Specifications) is now "Substance Abuse and Mental Health  Services Administration (SAMHSA)"
4. Also observe that the wording under Performance Measure is "Percentage of health home enrollees _age 18 and …
=> CMDCT-4411, CMDCT-4413: 2025 updates for TFL-CH and OUD-HH

services/ui-src/src/measures/2025/EDVAD/data.ts, services/ui-src/src/measures/2025/EDVAD/validation.ts, services/ui-src/src/measures/2025/rateLabelText.ts
New Measure EDV-AD.
In this measure numerator can be larger than the denominator, so those validations have been removed.
**Changes**
Performance measure:
_Number of emergency department (ED) visits for ambulatory care sensitive non-traumatic dental conditions per 100,000 beneficiary months for adults age 18 and older_
Rate Labels
CMDCT-4451
---
2) In FY 2025, go to the Adult Core Set
3) Select EDV-AD
4) Fill out the measure 
5) Make sure that the performance measure text is updated and the rate labels match the jira ticket
---
---
--- …
=> 2025 New Measure - EDV-AD Details

services/ui-src/src/measures/2025/OEVPAD/data.ts, services/ui-src/src/measures/2025/OEVPAD/validation.ts, services/ui-src/src/shared/commonQuestions/OptionalMeasureStrat/omsNodeBuilder.tsx
New flag requested to hide the [+Add Another Sex] button.
Also added some changes to OEVP-AD measures, it doesn't capture totals so that shouldn't be there
CMDCT-4496
---
Deploy Link: https://d6snmp8xle1v2.cloudfront.net/
2) Go to any measure i.e. AAB-AB
3) Fill out **Measure Specification** Section to enable the performance measure
4) Scroll down to the **Performance Measure** Section and fill out an N/D/R set. This will enable the OMS section
5) Click the check box next to the option [ ] Sex and see that the  [+Add Another Sex] button is gone.
---
---
---
_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val …
=> Stratification - Hide "Add Another Sex" option behind a launch darkly flag

services/ui-src/src/components/AutocompletedMeasureTemplate/index.tsx, services/ui-src/src/measures/2025/LRCDCH/index.tsx, services/ui-src/src/measures/2025/rateLabelText.ts, services/ui-src/src/measures/measureDescriptions.ts
**CIS-CH updates**
- Remove Combination 3, Combination 7 & Combination 10
**LRCD-CH updates**
- Update measure name
- Update measure description
- Note the text change is universally applied and Cam confirmed "It should be on all the non-reportable measures": 
> States are not asked to report data for this measure for 2025 Core Set reporting in the online reporting system.
CMDCT-4407 (CIS-CH)
CMDCT-4408 (LRCD-CH)
---
**Deploy Link:** https://d29h2z31uv9jni.cloudfront.net/
1. Sign into QMR, any state user
2. In FY 2025, go to the Child Core Set
3. Select CIS-CH
5. Fill out the measure
6. Make sure that the rate labels are removed and match the jira ticket
7. Go back and select LRCD-CH
8. Make sure measure name, and description and additional text at the bottom match Jira ticket
---
=> [QMR] LRCD-CH & CIS-CH 2025 Updates

deployment/stacks/ui.ts
Follow up to CMDCT-4363 main big PR (https://github.com/Enterprise-CMCS/macpro-mdct-qmr/pull/2590)
Just makes master like ephemeral environments, which is to say, behind the VPN.
=> CMDCT-4363 master and isDev behind VPN (QMR only)

.github/workflows/destroy.yml
Follow on to:
https://github.com/Enterprise-CMCS/macpro-mdct-qmr/pull/2590
Basically destroy is broken because it is still using serverless. This removes that.
=> CMDCT-4363 - fixes broken destroy

services/ui-src/src/measures/2025/OEVPCH/data.ts, services/ui-src/src/measures/2025/OEVPCH/validation.ts, services/ui-src/src/measures/2025/rateLabelText.ts
This PR covers adding measure details for measure "OEVP-CH" NOT to be confused with "OEV-CH"
- Performance Measure text update
- Data source: Administrative
- Rate Label: "Ages 15 to 20"
CMDCT-4454
---
**Deploy Link:** https://jiraent.cms.gov/browse/CMDCT-4454
1. Sign into QMR, any state user
2. In FY 2025, go to either Child Core Set
3. Select OEVP-CH
4. Fill out the measure
5. Make sure that the performance measure text is updated and the rate labels match the jira ticket
Data Source
Performance Measure
Same for OMS section
=> [QMR] 2025 New Measure - OEVP-CH Details

services/ui-src/src/measures/2025/PDSAD/data.ts, services/ui-src/src/measures/2025/PDSAD/validation.ts, services/ui-src/src/measures/2025/index.tsx, services/ui-src/src/measures/2025/measureTemplateData.tsx, services/ui-src/src/measures/2025/rateLabelText.ts, services/ui-src/src/shared/globalValidations/validateOneQualDenomHigherThanOtherDenomOMS/index.ts
New measure:
CMDCT-4435
---
cloudwatch: https://d2ath12k8290wk.cloudfront.net/
1. Log in as any state user
2. Navigate to 2025 adult measures and find PDS-AD
3. Fill out the form, making sure it matches the content in the CMDCT-4435 ticket
4. For one special validation, try making the denominator of "Follow-up on Positive Screen" larger than "Depression Screening" denom. Click the validate measure button and you should see the following error:
=> CMDCT-4435: New 2025 measure PDS-AD

services/ui-src/src/labels/2025/commonQuestionsLabel.tsx, services/ui-src/src/shared/commonQuestions/DateRange.tsx, services/ui-src/src/shared/commonQuestions/DefinitionsOfPopulation.tsx, services/ui-src/src/shared/commonQuestions/MeasurementSpecification.tsx, services/ui-src/src/shared/types/GlobalTypes.tsx, services/ui-src/src/shared/types/MeasureTemplate.tsx, services/ui-src/src/shared/types/TypeMeasureSpecification.tsx, services/ui-src/src/shared/types/index.tsx
The **Measure Specification** section has some label changes needed. 
Pre-2025
2025+
What makes this complicated is that the text is dynamic and based on the measure itself instead of a static the static text we utilize from the label text file. There's restructuring to the Measure Specification component but the data being saved is still the same.
I've also sorted each the pieces of the render into its own function to make it more readable.
---
`MeasurementSpecificationQuestionYesNo` function renders this text
---
`MeasurementSpecificationOtherAlert` function renders this alert
---
`MeasurementSpecificationOtherTextbox` function renders this textbox
---
CMDCT-4481
CMDCT-4482
CMDCT-4483
CMDCT-4484
CMDCT-4485
CMDCT-4486
CMDCT-4487
CMDCT-4488
CMDCT-4489
---
Deploy Link: …
=>  2025 Measure Steward Question Update 

services/ui-src/src/libs/spaLib.test.ts, services/ui-src/src/views/ExportAll/index.test.tsx, services/ui-src/src/views/ExportAll/util.test.ts, services/ui-src/src/views/ExportAll/util.tsx
It does what it says.
`getSpaName`, I refactored for clarity. The test for spaLib, I added so that I could justify excluding the check previously on line 222 in `getSpaName`. It was checking to see, not only whether it found an object, but also whether that object had truthy id, name, and state. If those are always truthy for every object in `SPA`, then that check is unneeded. And the unit test for spaLib asserts that truthiness.
I would have liked to add more tests around the helper functions within util.tsx. But I wanted to try to test them from the actual call site, if possible. Helpers like `openPdf` and `cloneChakraVariables` are only ever called from within `usePrinceRequest`, so I wanted to test them by calling them indirectly. But writing tests for `usePrinceRequest` is hard, …
=> Add some unit tests around ExportAll

services/ui-src/src/measures/2025/PCRHH/index.tsx
For PCR-HH, the text Health Home didn't dynamically generate in the Measure Specification section.
Easy fix, the core set prop wasn't set for that measure. i checked all the other 2025 index.tsx files and this was the only one missing.
CMDCT-4687
---
Deploy Link: https://d2vr410j5k9t0q.cloudfront.net/
1) Sign into QMR, [stateuserWA@test.com](mailto:stateuserDC@test.com)
2) In reporting year 2025, add Health Home Core Set 
3) Go to PCR-HH
4) Check that Measure Specification section shows Health Home 
---
---
---
=> [CMDCT-4687] UAT Defect - PCR-HH Measure Section

.github/setBranchName.sh, .github/workflows/dependabot-auto-approve.yml, .github/workflows/deploy.yml
Undo the removal of dependabot:
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/507/files
This PR reenables the following:
- Branch names for dependabot are converted to an md5sum and shortened
- Dependabot branches deploy
- Dependabot branches auto-merge assuming required checks pass
CMDCT-4376
---
Once this is merged, monitor future PRs
---
---
=> [CMDCT-4376] Enable dependabot automerge on success

services/ui-src/src/labels/2021/qualifierFormsData.tsx, services/ui-src/src/labels/2022/qualifierFormsData.tsx, services/ui-src/src/labels/2023/qualifierFormsData.tsx, services/ui-src/src/labels/2025/qualifierFormsData.tsx, services/ui-src/src/shared/Qualifiers/Common/generalAge.tsx, services/ui-src/src/shared/Qualifiers/Common/index.tsx, services/ui-src/src/shared/Qualifiers/index.tsx, services/ui-src/src/shared/types/TypeQualifierForm.tsx
Updated text for the qualifier sections.
Adult - Medicaid
- New textbox added: _1. Generally, what are the ages of adults covered in the state’s Medicaid program (inclusive of CHIP-funded Medicaid Expansion) (Title XIX & XXI)?_
- Updated parts of Delivery system text to: _As of December 31, 2024, approximately what percentage of adults in your state’s Medicaid program (inclusive of CHIP-funded Medicaid Expansion) (Title XIX & XXI)_
- Change "Ages 21 to 64" to "Adults Under Age 65" in the table header beneath delivery system description.
Adult - Chip
- New textbox added: _Generally, what are the ages of adults covered in the state’s separate CHIP (Title XXI) program?_
- Updated parts of Delivery system text to: _As of December 31, 2024, approximately what percentage of adults in your …
=> QMR2025 - Changes to Qualifier Questions

services/ui-src/src/labels/2025/commonQuestionsLabel.tsx
Remove the text from the ECDS text box that reads, “(text in this field is included in publicly-reported state-specific comments)”? It should just say, “Optional – Describe the data source(s) used:” 
CMDCT-4833
---
https://d3p4iabyszeuqy.cloudfront.net/
1. Go to any ECDS measure (ADD-CH, APM-CH, CIS-CH, IMA-CH, PDS-CH, PRS-CH, CCS-AD, COL-AD, BCS-AD, AIS-AD, PRS-AD, PDS-AD, COL-HH)
2. Under Data source, click ECDS 
3. Check that the hint text for the optional text box no longer includes (text in this field is included in publicly-reported state-specific comments)”
---
---
--- …
=> 2025 - Remove Text on ECDS

services/ui-src/src/shared/commonQuestions/MeasureStratification/Stratification/index.tsx, services/ui-src/src/shared/commonQuestions/MeasureStratification/index.tsx, services/ui-src/src/shared/commonQuestions/MeasureStratification/omsNodeBuilder.tsx, services/ui-src/src/shared/commonQuestions/OptionalMeasureStrat/omsNodeBuilder.tsx
- More stratification text changes
CMDCT-4863
---
- Login: https://d2tkymnr9ew7bi.cloudfront.net/
- Go to measure AAB-CH
- Under Measurement Specification select the first radio "Yes, ..."
- Scroll down to Performance Measure and type something into the Text Area underneath, and fill out the numerator and denominator further below
- Under **Measure Stratification** select radio button 1 or 2
- Verify the text changes match the story
---
---
---
=> CMDCT-4863 - More stratification text changes

services/ui-src/src/shared/commonQuestions/MeasureStratification/NDR/ndrFields.tsx, services/ui-src/src/shared/globalValidations/omsValidator/index.ts
This PR tackles a couple more validation issues.
1) **Validation labels are showing object id's as part of the labels and also not showing the correct labels when switching between 1997 race categories and 2024 race categories.** 
This was caused by the `locationDictionary` using 2024 race categories data as the look up no matter which version we were on.
2) **Some of the stratification subcategories create one validation per rate, whereas other subcategories create one validation per subcategory.**
This was caused by pushing the same rates data multiple times when building the oms rates to run the error validation against. We only needed to see if one in the category set was filled and add that. 
CMDCT-4875
CMDCT-4876
---
Deploy Link: https://d2zewt27y5qhho.cloudfront.net/
1) Sign into …
=> Stratification - Validation Warning Issues

services/ui-src/src/labels/2025/qualifierFormsData.tsx
This PR covers a tiny content update.
For Adult Medicaid Qualifiers Introduction, it previously had the same language as Child Core Set. This has been updated to reflect the correct Core Set language.
CMDCT-5048
---
**Deploy Link:** https://ds70ocw7wyymr.cloudfront.net/
1. Check with both users: stateuser1@test.com & stateuser3@test.com
2. Select `Adult Core Set Measures: Medicaid (Title XIX & XXI)` for 2025
3. Select `Adult Core Set Questions: Medicaid (inclusive of both Title XIX-funded Medicaid and Title XXI-funded Medicaid Expansion CHIP)`
4. Confirm introduction paragraph matches Jira ticket
| Before |
| ------ |
| <img width="600" height="300" alt="Before-Adult-Medicaid_Qualifiers-Intro-Paragraph" src="https://github.com/user-attachments/assets/944cac66-7c49-466c-adc8-483540963402" …
=> [QMR] 2025 - Adult Core Set Qualifier Intro Bug

services/app-api/handlers/dynamoUtils/measureList.ts, services/app-api/handlers/measures/get.ts, services/app-api/handlers/rate/rateNDRCalculations.ts, services/app-api/types.ts, services/app-api/utils/filters.ts, services/app-api/utils/parseParameters.ts, services/ui-src/src/components/MeasureWrapper/index.tsx
This PR expands on when to display the Measure Stratification Required Banner. Before it was a boolean, but it needed to be expanded to filter whether to show it on CHIP, Medicaid or both. So now the type is CoreSetAbbr.
There's also a text update to the banner to remove the comma so the text should read:
_For 2025 Core Sets reporting, states are expected to report stratified data for this measure._
**Note:**
- I create a `filters.ts` file to move the functions stored in _types.ts_. The function `isValidYear` was calling measures from the _measureList.ts_ file which caused a circular loading issue as measureList.ts needed access to the _types.ts_ file.
CMDCT-5050
---
Deploy Link: https://d3gzciezg4ao4f.cloudfront.net/
1) Sign into QMR, any state user.
2) Check that measures: FUA-AD, …
=> [CMDCT-5050] Measure Stratification Required Banner Updates

.github/workflows/pr-notification.yml
Update the stack name and output key so that Cloudfront URL populates in `#mdct-integrations-channel`.
Based on https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/1020
CMDCT-5040
---
1. After this PR is opened, check the post in `#mdct-integrations-channel` for this PR
2. Confirm a Cloudfront URL is associated with this PR
---
=> [CMDCT-5043] Update stack name and output key in pr-notification.yml

services/app-api/handlers/rate/rateNDRCalculations.test.ts, services/app-api/handlers/rate/rateNDRCalculations.ts
Every measure in QMR has a fantastic, comprehensive amount of validation on the frontend. However, even data that has not passed validation can still be used for the Combined Rates page. When calculating combined rates, we just use whatever data was saved, without performing any validation - with one exception. We _do_ check to make sure that the numerator is not greater than the denominator. This is a simple check that applies to all measures, so it was not a huge cost to re-implement it within the combined rates code.
Well now, even that exception has an exception. There are a handful of measures to which that check does not apply. For EDV and PQI measures, it is possible and valid for the numerator to exceed the denominator. Most of our measures are about subsets (like, "Of the …
=> Allow numerator > denominator in Combined Rates for certain measures

deployment/PROD_TO_PRODUCTION_INSTRUCTIONS.md
Tiny update to this PR:
https://github.com/Enterprise-CMCS/macpro-mdct-qmr/pull/2722
=> CMDCT-5061 - updates instructions with missing branch name dependency

services/ui-src/src/components/Footer/index.tsx
This PR covers a tiny change to update footer header to h2 instead of h3
CMDCT-4816
**Deploy Link:** https://d1tjh4pzaqkn6i.cloudfront.net/
=> [QMR] Footer header should be h2

services/ui-src/package.json, services/ui-src/src/components/Banner/Banner.tsx, services/ui-src/yarn.lock
- Banner descriptions are now being sanitized before being sent to the parser. The sanitization config is setup to match the one in the backend, so now the user will get a preview of exactly what is saved in the DB.
- Changed the `<p>` to a `<span>` so there would be no errors if a user provides a `<ul>` (as a `<ul>` should not be inside a `<p>`)
CMDCT-4825
---
- Login as an admin: https://d1fv14y2db6spl.cloudfront.net/
- Modify the banner to something like:
```
<ul>
<li> list item </li>
</ul>
```
and verify there are no errors in the console
---
---
--- …
=> CMDCT-4825 - added html sanitizier to banner

services/ui-src/package.json, services/ui-src/src/utils/testUtils/reactHookFormRenderer.tsx, services/ui-src/yarn.lock
When running unit tests this error sometimes shows up:
```
console.error
Warning: `ReactDOMTestUtils.act` is deprecated in favor of `React.act`. Import `act` from `react` instead of `react-dom/test-utils`. See https://react.dev/warnings/react-dom-test-utils for more info.
```
This is caused by a version mismatch between react 18 and the testing library. Upgrading the testing library resolves this error.
---
- Unit tests pass
- This error no longer shows up in unit tests
run `yarn` in services/ui-src directory
---
---
=> Upgrade react testing library to reduce error noise in tests

services/ui-src/src/Routes.test.tsx
This PR covers adding coverage for Routes.tsx, ensuring that the paths are loading. 
In QMR, we use lazy loading, so we have to import suspense from react to test lazy loading, but totes open to feedback.
CMDCT-5094
- check out branch locally
- `git pull `
- `git checkout qmr-5094`
- ensure you're in ui-src: `cd services/ui-src`
- run tests: `yarn test Routes.test.tsx --no-cache  --coverage --collectCoverageFrom=src/Routes.tsx` or check the QLTY report.
Lines 50 and 55 are the ones remaining to be covered which is this section; otherwise this PR does cover this file above 90% 👍 
Maybe there's a way to cover this section, but this one broke my brain 🧠 
```
const MeasuresLoading = lazy(() =>
import("views/MeasuresLoading").then((module) => ({
default: module.MeasuresLoading,
}))
);
const …
```
=> [QMR] Increase Code Coverage - src/Routes.tsx

services/topics/config.js, services/topics/handlers/createTopics.js
CMDCT-5254: move topics config into a separate file
CMDCT-5254
---
---
---
---
=> CMDCT-5254: move topics config into a separate file
